# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

_variables:
  from12: &from12 marketplace.gcr.io/google/debian12@sha256:c2a5eb3516da4c3bb0cf2d6fea739bd7b2dc7b1ac444b5fbd7c4def2aa57d4a0

versions:
  - dir: '0/debian12/0.1'
    repo: peer-finder0
    tags:
      - '0.1-debian12'
      - '0.1'
      - '0'
      - 'latest'
    from: *from12
    packages:
      golang:
        version: '1.25.13'
      apimachinery:
        version: 0.25.0
    allowlist:
    - marketplace.gcr.io
    - deb.debian.org
    - dl.google.com
    - proxy.golang.org
    - sum.golang.org
    - k8s.io

cloudbuild:
  enable_parallel: false
