#!/bin/bash -eu
#
# Copyright 2023 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/c2d-utils || exit 1

declare -r tomcat_admin_password="$(get_attribute_value "tomcat-admin-password")"
declare -r tomcat_config_folder="/opt/tomcat/conf"

# Stop Tomcat for applying the configs
systemctl stop tomcat

# Apply the managers password
sed -i -e '$ i \
  <user username="tomcat" password="'"${tomcat_admin_password}"'" roles="manager-gui,admin-gui"/>
' "${tomcat_config_folder}/tomcat-users.xml"

# Binds tomcat to localhost
xmlstarlet ed -L -a "/Server/Service[@name='Catalina']/Connector[@port='8080']" \
  -t attr -n address -v "localhost" "${tomcat_config_folder}/server.xml"

# Starts Tomcat
systemctl start tomcat
systemctl restart apache2

until curl -s -f localhost > /dev/null; do
  sleep 3
done

echo "Installation complete!"
