#!/bin/bash -eu
#
# Copyright 2020 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/c2d-utils || exit 1

COUCHDB_PASSWORD="$(get_attribute_value "COUCHDB_PASSWORD")"
COUCHDB_USER="administrator"
INI_FILE="/opt/couchdb/etc/local.ini"

echo "$COUCHDB_USER = $COUCHDB_PASSWORD" >> $INI_FILE
sed -i 's/;bind_address.*/bind_address = 0.0.0.0/' $INI_FILE
sed -i 's/;WWW-Authenticate = Basic realm="administrator"/WWW-Authenticate = Basic realm="administrator"/' $INI_FILE
sed -i '/bind_address = 0.0.0.0/a require_valid_user = true' $INI_FILE

service couchdb start
