#!/bin/bash -eu
#
# Copyright 2021 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/c2d-utils || exit 1

export COMPOSER_HOME="/root/.config/composer"

function configure_php() {
  local -r php_version="$(php -v | awk '/PHP [0-9]+\.[0-9]+/ {print $2}' | grep -o -P "^[0-9]+\.[0-9]+")"
  local -r phpfpm_config="/etc/php/${php_version}/fpm/pool.d/www.conf"
  local -r php_config="/etc/php/${php_version}/cli/php.ini"

  # Configure PHP-FPM
  # sed -i -e "s/;daemonize\s*=\s*yes/daemonize = no/g" "${phpfpm_config}"
  sed -i -e "s/listen\s*=\s*.*$/listen = 127.0.0.1:9000/g" "${phpfpm_config}"
  sed -i "s/pm.max_children = 5/pm.max_children = 5000/" "${phpfpm_config}"
  sed -i "s/pm.start_servers = 2/pm.start_servers = 150/" "${phpfpm_config}"
  sed -i "s/pm.min_spare_servers = 1/pm.min_spare_servers = 100/" "${phpfpm_config}"
  sed -i "s/pm.max_spare_servers = 3/pm.max_spare_servers = 200/" "${phpfpm_config}"
  sed -i "s/pm = dynamic/pm = ondemand/" "${phpfpm_config}"

  # Configure PHP
  sed -i "s|;date.timezone =.*|date.timezone = UTC|" "${php_config}"
  sed -i "s|memory_limit =.*|memory_limit = 512M|" "${php_config}"
  sed -i "s|upload_max_filesize =.*|upload_max_filesize = 50M|" "${php_config}"
  sed -i "s|max_file_uploads =.*|max_file_uploads = 200|" "${php_config}"
  sed -i "s|post_max_size =.*|max_file_uploads = 100M|" "${php_config}"
  sed -i "s/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/" "${php_config}"
  echo 'sendmail_path = "/usr/sbin/ssmtp -t"' >> "${php_config}"

  # Restart php-fpm service
  systemctl restart "php${php_version}-fpm"
}

function configure_nginx() {
  declare nginx_config="/etc/nginx/nginx.conf"
  sed -i "s/worker_connections 768;/worker_connections 2048;/" "${nginx_config}"
  sed -i "s/keepalive_timeout 65;/keepalive_timeout 10;/" "${nginx_config}"
}

echo "Setting up PHP..."
configure_php

echo "Setting up NGINX..."
configure_nginx

echo "Enabling Website..."
rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/testlink.conf /etc/nginx/sites-enabled/

echo "Installation complete?"
