#!/bin/bash -eu
#
# Copyright 2021 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/c2d-utils || exit 1

export COMPOSER_HOME="/root/.config/composer"

function configure_php() {
  local phpfpm_config="/etc/php/7.4/fpm/pool.d/www.conf"
  local php_config="/etc/php/7.4/cli/php.ini"

  # Configure PHP-FPM
  # sed -i -e "s/;daemonize\s*=\s*yes/daemonize = no/g" "${phpfpm_config}"
  sed -i -e "s/listen\s*=\s*.*$/listen = 127.0.0.1:9000/g" "${phpfpm_config}"
  sed -i "s/pm.max_children = 5/pm.max_children = 5000/" "${phpfpm_config}"
  sed -i "s/pm.start_servers = 2/pm.start_servers = 150/" "${phpfpm_config}"
  sed -i "s/pm.min_spare_servers = 1/pm.min_spare_servers = 100/" "${phpfpm_config}"
  sed -i "s/pm.max_spare_servers = 3/pm.max_spare_servers = 200/" "${phpfpm_config}"
  sed -i "s/pm = dynamic/pm = ondemand/" "${phpfpm_config}"

  # Configure PHP
  sed -i "s|;date.timezone =.*|date.timezone = UTC|" "${php_config}"
  sed -i "s|memory_limit =.*|memory_limit = 512M|" "${php_config}"
  sed -i "s|upload_max_filesize =.*|upload_max_filesize = 50M|" "${php_config}"
  sed -i "s|max_file_uploads =.*|max_file_uploads = 200|" "${php_config}"
  sed -i "s|post_max_size =.*|max_file_uploads = 100M|" "${php_config}"
  sed -i "s/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/" "${php_config}"
  echo 'sendmail_path = "/usr/sbin/ssmtp -t"' >> "${php_config}"

  # Restart php-fpm service
  systemctl restart php7.4-fpm
}

function configure_nginx() {
  declare nginx_config="/etc/nginx/nginx.conf"
  sed -i "s/worker_connections 768;/worker_connections 2048;/" "${nginx_config}"
  sed -i "s/keepalive_timeout 65;/keepalive_timeout 10;/" "${nginx_config}"
}

echo "Setting up PHP..."
configure_php

echo "Setting up NGINX..."



echo "Installation complete?"

# -----
# readonly opencart_email="$(get_attribute_value "opencart-email")"
# readonly opencart_db_password="$(get_attribute_value "opencart-db-password")"
# readonly opencart_admin_password="$(get_attribute_value "opencart-admin-password")"
# readonly opencart_db_user="opencart"
# readonly opencart_db_name="opencart"
# readonly opencart_admin_user="admin"
# declare  opencart_url="http://$(get_internal_ip)/store/"

# # Setup website url
# if [[ has_external_ip ]]; then
#   opencart_url="http://$(get_external_ip)/store/"
# fi

# echo "Awaiting for MySQL be up..."
# wait_for_port "localhost" "3306"

# # Setup MySQL user
# echo "Setting up MySQL user..."
# setup_mysql_user "${opencart_db_user}" "${opencart_db_password}" \
#   "${opencart_db_name}"

# # Setup Opencart installer
# echo "Setting up OpenCart Installer..."
# setup_opencart_installer

# # Install Opencart
# echo "Setting up OpenCart DB..."
# install_opencart_db \
#   "${opencart_db_user}" "${opencart_db_password}" "${opencart_db_name}" \
#   "${opencart_admin_user}" "${opencart_admin_password}" \
#   "${opencart_email}" "${opencart_url}"

# # Prepare Apache and PHP configurations
# echo "Preparing Apache and PHP config..."
# prepare_apache_and_php

# # Fix storage location
# echo "Fix Storage Location..."
# fix_storage_location

# # Fix vendor modules
# echo "Fix vendor modules..."
# fix_vendor_modules

# # Grants ownership to user on whole folder
# echo "Granting access to www-data..."
# chown -R www-data:www-data /var/www/

# # Remove installation folder
# echo "Removing installation folder..."
# rm -rf /var/www/html/store/install

# # Restart Apache
# echo "Restarting Apache..."
# systemctl restart apache2

# echo "Installation complete!"
