#!/bin/bash -eu
#
# Copyright 2021 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/testlink-utils || exit 1

declare -r testlink_admin_password="$(get_attribute_value "testlink-admin-password")"

declare -r testlink_db_password="$(get_attribute_value "testlink-db-password")"
declare -r testlink_db_user="testlink"
declare -r testlink_db_name="testlink"

declare -r testlink_tmproot_username="tmproot"
declare -r testlink_tmproot_password="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 20 | head -n 1 | tr -d '\n')"

echo "Stopping webserver..."
systemctl stop nginx

echo "Setting up database user..."
setup_mysql_user "${testlink_db_user}" "${testlink_db_password}" "${testlink_db_name}"

echo "Creating app database configuration file..."
generate_config_file "${testlink_db_user}" "${testlink_db_password}" "${testlink_db_name}"

echo "Setting up PHP..."
configure_php

echo "Setting up NGINX..."
configure_nginx

echo "Enabling Website..."
rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/testlink.conf /etc/nginx/sites-enabled/

echo "Starting webserver..."
systemctl start nginx

# Check if install app is ready
wait_for_app

# Create temporary user for installing TestLink database
create_temp_user "${testlink_tmproot_username}" "${testlink_tmproot_password}"

install_testlink \
  "${testlink_db_name}" \
  "${testlink_tmproot_username}" "${testlink_tmproot_password}" \
  "${testlink_db_user}" "${testlink_db_password}"

# Update admin password
mysql -u root -e "UPDATE users SET password = md5('${testlink_admin_password}') WHERE id = 1;" "${testlink_db_name}"

# Remove temporary MySQL superuser
mysql -u root -e "DROP USER '${testlink_tmproot_username}'@'localhost';"

echo "Installation complete!"
