#!/bin/bash -eu
#
# Copyright 2022 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This script runs for about 3-4 minutes - it is time that is required to load
# Alfresco webapps on Tomcat

source /opt/c2d/c2d-utils || exit 1

postgresql_alfresco_password="$(get_attribute_value "postgresql-alfresco-password")"
alfresco_admin_password="$(get_attribute_value "alfresco-admin-password")"

declare -r postgresql_alfresco_password
declare -r alfresco_admin_password

declare -r ALFRESCO_HOME="/opt/alfresco"
declare -r TOMCAT_HOME="/opt/tomcat"
declare -r SOLR_HOME="/opt/solr/alfresco-search-services"


echo -e "Change PostgreSQL alfresco user password and update Alfresco configuration"
su - postgres -c "psql -c \"alter role alfresco with password '${postgresql_alfresco_password}'\""
export POSTGRESQL_ALFRESCO_PASSWORD=${postgresql_alfresco_password}
envsubst \
  < /opt/alfresco/alfresco-global.properties.template \
  > /opt/tomcat/shared/classes/alfresco-global.properties
rm /opt/alfresco/alfresco-global.properties.template

# Add hostname entries to /etc/hosts
echo "127.0.0.1 $(hostname)" >> /etc/hosts
echo "::1 $(hostname)" >> /etc/hosts

echo -e "Copying configuration and war files..."
mkdir -p "${ALFRESCO_HOME}"/modules/share
mkdir -p "${ALFRESCO_HOME}"/modules/platform

rm -rf "${TOMCAT_HOME}"/webapps/*

cp "${ALFRESCO_HOME}"/web-server/webapps/*.war "${TOMCAT_HOME}"/webapps/
cp -r "${ALFRESCO_HOME}"/web-server/conf/Catalina "${TOMCAT_HOME}"/conf/
cp -r "${ALFRESCO_HOME}"/web-server/shared "${TOMCAT_HOME}"

mkdir -p "${TOMCAT_HOME}"/shared/lib
cp "${ALFRESCO_HOME}"/web-server/lib/*.jar "${TOMCAT_HOME}"/shared/lib

echo -e "Configuring Solr6 for Non-SSL..."
sed -i 's/alfresco.secureComms=https/alfresco.secureComms=none/' "${SOLR_HOME}"/solrhome/templates/rerank/conf/solrcore.properties
sed -i 's/alfresco.port.ssl=8443/#alfresco.port.ssl=8443/' "${SOLR_HOME}"/solrhome/templates/rerank/conf/solrcore.properties
sleep 3

echo -e "Starting Solr6...Creating indexes..."
"${SOLR_HOME}"/solr/bin/solr start -a "-Dcreate.alfresco.defaults=alfresco,archive" -force
sleep 20

sed -i 's/#shared.loader=/shared.loader=${catalina.base}/shared/classes,${catalina.base}/shared/lib/*.jar/' "${TOMCAT_HOME}"/conf/catalina.properties

echo -e "Installing AMP files..."
java -jar "${ALFRESCO_HOME}"/bin/alfresco-mmt.jar install "${ALFRESCO_HOME}"/amps/alfresco-share-services.amp "${TOMCAT_HOME}"/webapps/alfresco.war
java -jar "${ALFRESCO_HOME}"/bin/alfresco-mmt.jar install "${ALFRESCO_HOME}"/rm-apts/alfresco-rm-community-repo-3.0.a.amp "${TOMCAT_HOME}"/webapps/alfresco.war
java -jar "${ALFRESCO_HOME}"/bin/alfresco-mmt.jar install "${ALFRESCO_HOME}"/rm-apts/alfresco-rm-community-share-3.0.a.amp "${TOMCAT_HOME}"/webapps/share.war

echo -e "Stopping Solr6..."
"${SOLR_HOME}"/solr/bin/solr restart -force 
/opt/activemq/apache-activemq-5.16.3/bin/activemq start
service tomcat start
