#!/usr/bin/python
"""Python script to generate the import json for a grafana dashboard.

Dashboard json files are generated by exporting each grafana dashboard from
the web UI (Share -> Export). Each dashboard can utilise two template
constants: DEPLOYMENT (the deployment name) and STORAGE_POOL (the name of the
data disk).

This script populates value of PRIMARY_HOSTNAME and STORAGE_POOL constants,
and adds graphite datasource configuration.

Reads exported dashboard from stdin.
Writes import json to stdout.
"""

# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import json
import sys

import singlefs_util as util


def main():
  dashboard_json = json.load(sys.stdin)
  import_json = {
      'dashboard': dashboard_json,
      'inputs': [
          {
              'name': 'DS_GRAPHITE',
              'type': 'datasource',
              'pluginId': 'graphite',
              'value': 'Graphite',
          },
          {
              'name': 'VAR_DEPLOYMENT',
              'type': 'constant',
              'value': util.get_metadata('DEPLOYMENT_NAME'),
          },
          {
              'name': 'VAR_STORAGE_POOL',
              'type': 'constant',
              'value': util.get_metadata('STORAGE_POOL_NAME'),
          }
      ]
  }

  print json.dumps(import_json)

if __name__ == '__main__':
  main()
