#!/bin/bash -eu
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/c2d-utils || exit 1

dokuwiki_admin_password=$(get_attribute_value "dokuwiki-admin-password")
declare -r dokuwiki_admin_password

export ADMIN_PASS_HASH=$(echo -n "${dokuwiki_admin_password}" | md5sum | awk '{print $1}')
export ADMIN_EMAIL="$(get_attribute_value "dokuwiki-admin-email")"
envsubst < /var/www/html/conf/users.auth.php.template > /var/www/html/conf/users.auth.php
rm /var/www/html/conf/users.auth.php.template