# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ospo_download 'Licenses and Source-code' do
  ref_repos <<-EOF
https://github.com/pysimplesoap/pysimplesoap
https://github.com/certifi/python-certifi
https://github.com/chardet/chardet
https://github.com/jenkinsci/constant-pool-scanner
https://docutils.sourceforge.io
https://github.com/jakartaee/expression-language
https://github.com/anchore/go-version
https://github.com/go-sql-driver/mysql
https://github.com/hashicorp/consul
https://github.com/hashicorp/errwrap
https://github.com/hashicorp/go-checkpoint
https://github.com/hashicorp/go-cleanhttp
https://github.com/hashicorp/go-immutable-radix
https://github.com/hashicorp/go-multierror
https://github.com/hashicorp/go-plugin
https://github.com/hashicorp/go-retryablehttp
https://github.com/hashicorp/go-rootcerts
https://github.com/hashicorp/go-uuid
https://github.com/hashicorp/go-version
https://github.com/hashicorp/golang-lru
https://github.com/hashicorp/hc-install
https://github.com/hashicorp/hcl
https://github.com/hashicorp/logutils
https://github.com/hashicorp/nomad
https://github.com/hashicorp/serf
https://github.com/hashicorp/terraform-exec
https://github.com/hashicorp/terraform-json
https://github.com/hashicorp/terraform-plugin-go
https://github.com/hashicorp/terraform-plugin-log
https://github.com/hashicorp/terraform-plugin-sdk
https://github.com/hashicorp/terraform-registry-address
https://github.com/hashicorp/terraform-svchost
https://github.com/hashicorp/yamux
https://github.com/eclipse/jetty.project
https://github.com/jenkinsci/jakarta-mail-api-plugin
https://github.com/eclipse-ee4j/common-annotations-api
https://github.com/eclipse-ee4j/mail
https://github.com/eclipse-ee4j/jstl-api
https://github.com/eclipse-ee4j/websocket-api
https://github.com/jenkinsci/javax-activation-api-plugin
https://github.com/jenkinsci/javax-mail-api-plugin
https://github.com/javaee/activation
https://github.com/javaee/javax.annotation
https://github.com/javaee/el-spec
https://github.com/javaee/javamail
https://github.com/javaee/servlet-spec
https://github.com/javaee/javaee-jsp-api
https://github.com/jakartaee/websocket
https://github.com/javaee/jaxb-spec
https://github.com/kohsuke/jcifs
https://github.com/jfree/jcommon
https://github.com/jetty/jetty.project
https://github.com/jfree/jfreechart
https://github.com/java-native-access/jna
https://github.com/AdoptOpenJDK/openjdk-jdk11
https://github.com/jakartaee/pages
https://github.com/lattera/glibc
https://github.com/pycurl/pycurl
https://github.com/romlok/python-debian
https://github.com/jakartaee/servlet
https://github.com/jglick/sezpoz
https://github.com/spotbugs/spotbugs
https://github.com/kohsuke/tiger-types
https://github.com/eclipse-ee4j/tyrus
https://github.com/mvo5/unattended-upgrades
https://github.com/jenkinsci/winstone
EOF
  licenses <<-EOF
PySimpleSOAP;https://github.com/pysimplesoap/pysimplesoap
PySocks;https://rawhubusercontent.com/Anorov/PySocks/master/LICENSE
Sphinx;https://rawhubusercontent.com/sphinx-doc/sphinx/master/LICENSE.rst
access_modifier_annotation;https://rawhubusercontent.com/jenkinsci/lib-access-modifier/master/LICENSE.md
actions_cache;https://rawhubusercontent.com/actions/cache/main/LICENSE
actions_checkout;https://rawhubusercontent.com/actions/checkout/main/LICENSE
actions_download_artifact;https://rawhubusercontent.com/actions/download-artifact/main/LICENSE
actions_setup_python;https://rawhubusercontent.com/actions/setup-python/main/LICENSE
actions_upload_artifact;https://rawhubusercontent.com/actions/upload-artifact/main/LICENSE
animal_sniffer_annotations;https://rawhubusercontent.com/mojohaus/animal-sniffer/master/LICENSE
annotation_indexer;https://github.com/jenkinsci/lib-annotation-indexer
annotations;https://android.kernel.org/
ant;https://gitbox.apache.org/repos/asf/ant
ant_launcher;https://gitbox.apache.org/repos/asf/ant
antisamy_markup_formatter;https://github.com/jenkinsci/antisamy-markup-formatter-plugin
antlr;https://rawhubusercontent.com/antlr/antlr4/dev/LICENSE.txt
antlr4_runtime;https://github.com/antlr/antlr4/tree/master
apache_httpcomponents_client_4_api;https://github.com/jenkinsci/apache-httpcomponents-client-4-api-plugin
argcomplete;https://rawhubusercontent.com/kislyuk/argcomplete/master/LICENSE.rst
argparse;https://rawhubusercontent.com/python/cpython/main/LICENSE
args4j;https://rawhubusercontent.com/kohsuke/args4j/master/LICENSE
asm;https://gitlab.ow2.org/asm/asm/-/raw/master/LICENSE.txt?ref_type=heads
asm_all;https://gitlab.ow2.org/asm/asm/-/raw/master/LICENSE.txt?ref_type=heads
asm_analysis;https://gitlab.ow2.org/asm/asm/-/raw/master/LICENSE.txt?ref_type=heads
asm_commons;https://gitlab.ow2.org/asm/asm/-/raw/master/LICENSE.txt?ref_type=heads
asm_tree;https://gitlab.ow2.org/asm/asm/-/raw/master/LICENSE.txt?ref_type=heads
asm_util;https://gitlab.ow2.org/asm/asm/-/raw/master/LICENSE.txt?ref_type=heads
attrs;https://rawhubusercontent.com/python-attrs/attrs/master/LICENSE
bcpkix_jdk18on;https://rawhubusercontent.com/bcgit/bc-java/main/LICENSE.html
bcprov_jdk18on;https://rawhubusercontent.com/bcgit/bc-java/main/LICENSE.html
bcutil_jdk18on;https://rawhubusercontent.com/bcgit/bc-java/main/LICENSE.html
bitbucket.org_creachadair_stringset;https://bitbucket.org/creachadair/stringset
black;https://rawhubusercontent.com/psf/black/master/LICENSE
bleach;https://rawhubusercontent.com/mozilla/bleach/master/LICENSE
bootstrap5_api;https://github.com/jenkinsci/bootstrap5-api-plugin
bouncycastle_api;https://github.com/jenkinsci/bouncycastle-api-plugin
bridge_method_annotation;https://github.com/jenkinsci/bridge-method-injector
bsf;http://svn.apache.org/viewvc/jakarta/bsf/tags/bsf-2.4.0
cachetools;https://rawhubusercontent.com/tkem/cachetools/master/LICENSE
caffeine;https://rawhubusercontent.com/ben-manes/caffeine/master/LICENSE
caffeine_api;https://rawhubusercontent.com/jenkinsci/caffeine-api-plugin/master/LICENSE
certifi;https://rawhubusercontent.com/certifi/python-certifi/master/LICENSE
cffi;https://rawhubusercontent.com/python-cffi/cffi/master/LICENSE
chardet;https://rawhubusercontent.com/chardet/chardet/master/LICENSE
charset_normalizer;https://rawhubusercontent.com/ousret/charset_normalizer/master/LICENSE
checks_api;https://rawhubusercontent.com/jenkinsci/checks-api-plugin/master/LICENSE
cli;https://github.com/jenkinsci/jenkins
click;https://rawhubusercontent.com/pallets/click/master/LICENSE.rst
cloud.google.com_go;https://rawhubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_bigtable;https://rawhubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_compute_metadata;https://rawhubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_iam;https://rawhubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_logging;https://rawhubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_longrunning;https://rawhubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_monitoring;https://rawhubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_osconfig;https://rawhubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_storage;https://rawhubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_trace;https://rawhubusercontent.com/googleapis/google-cloud-go/master/LICENSE
codecov_codecov_action;https://rawhubusercontent.com/codecov/codecov-action/main/LICENSE
colorlog;https://rawhubusercontent.com/borntyping/python-colorlog/master/LICENSE
command_launcher;https://github.com/jenkinsci/command-launcher-plugin
commonmark;https://github.com/rtfd/commonmark.py
commons_beanutils;http://svn.apache.org/viewvc/commons/proper/beanutils/tags/BEANUTILS_1_9_3_RC3
commons_cli;http://svn.apache.org/viewvc/commons/proper/cli/trunk/
commons_codec;https://github.com/apache/commons-codec
commons_collections;http://svn.apache.org/viewvc/commons/proper/collections/trunk
commons_compress;https://gitbox.apache.org/repos/asf?p=commons-compress
commons_discovery;http://svn.apache.org/viewvc/commons/proper/discovery/tags/DISCOVERY_0_5_RC2
commons_fileupload;https://gitbox.apache.org/repos/asf?p=commons-fileupload
commons_io;https://gitbox.apache.org/repos/asf?p=commons-io
commons_jelly;https://github.com/jenkinsci/jelly
commons_jelly_tags_define;https://github.com/jenkinsci/jelly
commons_jelly_tags_fmt;https://github.com/jenkinsci/jelly
commons_jelly_tags_xml;https://github.com/jenkinsci/jelly
commons_jexl;http://jakarta.apache.org/commons/jexl/
commons_lang;http://svn.apache.org/viewvc/commons/proper/lang/branches/LANG_2_X
commons_lang3;https://gitbox.apache.org/repos/asf?p=commons-lang
commons_lang3_api;https://github.com/jenkinsci/commons-lang3-api-plugin
commons_text;https://gitbox.apache.org/repos/asf?p=commons-text
commons_text_api;https://rawhubusercontent.com/jenkinsci/commons-text-api-plugin/master/LICENSE
constant_pool_scanner;https://github.com/jenkinsci/constant-pool-scanner/blob/master/pom.xml#L17
contrib.go.opencensus.io_exporter_prometheus;https://rawhubusercontent.com/census-ecosystem/opencensus-go-exporter-prometheus/master/LICENSE
cos.googlesource.com_cos_tools.git;https://cos.googlesource.com/cos/tools
coverage;https://bitbucket.org/ned/coveragepy
crcmod;https://rawhubusercontent.com/gsutil-mirrors/crcmod/master/LICENSE
crypto_util;https://github.com/jenkinsci/lib-crypto-util
cryptography;https://rawhubusercontent.com/pyca/cryptography/master/LICENSE
dario.cat_mergo;https://rawhubusercontent.com/imdario/mergo/master/LICENSE
dbus_python;https://gitlab.freedesktop.org/dbus/dbus-python/-/raw/master/CONTRIBUTING.md
dessant_lock_threads;https://rawhubusercontent.com/dessant/lock-threads/main/LICENSE
display_url_api;https://github.com/jenkinsci/display-url-api-plugin
distlib;https://rawhubusercontent.com/pypa/distlib/master/LICENSE.txt
distro_info;https://rawhubusercontent.com/python-distro/distro/master/LICENSE
docutils;https://docutils.sourceforge.io/COPYING.html
echarts_api;https://rawhubusercontent.com/jenkinsci/echarts-api-plugin/master/LICENSE
eddsa;https://github.com/str4d/ed25519-java
el_api;https://rawhubusercontent.com/jakartaee/expression-language/master/LICENSE.md
embedded_su4j;https://rawhubusercontent.com/kohsuke/embedded_su4j/master/pom.xml
error_prone_annotations;https://github.com/google/error-prone
ezmorph;http://ezmorph.cvs.sourceforge.net/ezmorph
failureaccess;https://rawhubusercontent.com/google/guava/master/LICENSE
filelock;https://rawhubusercontent.com/tox-dev/py-filelock/master/LICENSE
flake8;https://github.com/pycqa/flake8
flaky;https://rawhubusercontent.com/box/flaky/master/LICENSE
fluent_hc;http://hc.apache.org/httpcomponents-client-ga
font_awesome_api;https://rawhubusercontent.com/jenkinsci/font-awesome-api-plugin/master/LICENSE
future;https://rawhubusercontent.com/PythonCharmers/python-future/master/LICENSE.txt
gcp_devrel_py_tools;https://rawhubusercontent.com/GoogleCloudPlatform/python-repo-tools/master/LICENSE
gcp_docuploader;https://rawhubusercontent.com/googleapis/docuploader/main/LICENSE
gcp_releasetool;https://rawhubusercontent.com/googleapis/releasetool/master/LICENSE
github.com_99designs_keyring;https://github.com/99designs/keyring
github.com_Azure_azure_sdk_for_go;https://github.com/azure/azure-sdk-for-go
github.com_Azure_azure_sdk_for_go_sdk_azcore;https://github.com/azure/azure-sdk-for-go
github.com_Azure_azure_sdk_for_go_sdk_azidentity;https://github.com/azure/azure-sdk-for-go
github.com_Azure_azure_sdk_for_go_sdk_internal;https://github.com/azure/azure-sdk-for-go
github.com_Azure_azure_sdk_for_go_sdk_resourcemanager_compute_armcompute_v4;https://github.com/azure/azure-sdk-for-go
github.com_Azure_azure_sdk_for_go_sdk_resourcemanager_network_armnetwork_v2;https://github.com/azure/azure-sdk-for-go
github.com_Azure_azure_sdk_for_go_sdk_storage_azblob;https://github.com/azure/azure-sdk-for-go
github.com_Azure_go_autorest_autorest;https://rawhubusercontent.com/azure/go-autorest/master/LICENSE
github.com_Azure_go_autorest_autorest_adal;https://rawhubusercontent.com/azure/go-autorest/master/LICENSE
github.com_Azure_go_autorest_autorest_date;https://rawhubusercontent.com/azure/go-autorest/master/LICENSE
github.com_Azure_go_autorest_autorest_to;https://rawhubusercontent.com/azure/go-autorest/master/LICENSE
github.com_Azure_go_autorest_autorest_validation;https://rawhubusercontent.com/azure/go-autorest/master/LICENSE
github.com_Azure_go_autorest_logger;https://rawhubusercontent.com/azure/go-autorest/master/LICENSE
github.com_Azure_go_autorest_tracing;https://rawhubusercontent.com/azure/go-autorest/master/LICENSE
github.com_AzureAD_microsoft_authentication_library_for_go;https://rawhubusercontent.com/azuread/microsoft-authentication-library-for-go/master/LICENSE
github.com_CycloneDX_cyclonedx_go;https://rawhubusercontent.com/cyclonedx/cyclonedx-go/master/LICENSE
github.com_GoogleCloudPlatform_declarative_resource_client_library;https://rawhubusercontent.com/googlecloudplatform/declarative-resource-client-library/master/LICENSE
github.com_GoogleCloudPlatform_guest_agent;https://rawhubusercontent.com/GoogleCloudPlatform/guest-agent/main/LICENSE
github.com_GoogleCloudPlatform_guest_logging_go;https://rawhubusercontent.com/googlecloudplatform/guest-logging-go/master/LICENSE
github.com_GoogleCloudPlatform_opentelemetry_operations_collector;https://rawhubusercontent.com/GoogleCloudPlatform/opentelemetry-operations-collector/master/LICENSE
github.com_GoogleCloudPlatform_opentelemetry_operations_go_detectors_gcp;https://rawhubusercontent.com/googlecloudplatform/opentelemetry-operations-go/master/LICENSE
github.com_GoogleCloudPlatform_opentelemetry_operations_go_exporter_collector;https://rawhubusercontent.com/googlecloudplatform/opentelemetry-operations-go/master/LICENSE
github.com_GoogleCloudPlatform_opentelemetry_operations_go_exporter_collector_googlemanagedprometheus;https://rawhubusercontent.com/googlecloudplatform/opentelemetry-operations-go/master/LICENSE
github.com_GoogleCloudPlatform_opentelemetry_operations_go_exporter_metric;https://rawhubusercontent.com/googlecloudplatform/opentelemetry-operations-go/master/LICENSE
github.com_GoogleCloudPlatform_opentelemetry_operations_go_exporter_trace;https://rawhubusercontent.com/googlecloudplatform/opentelemetry-operations-go/master/LICENSE
github.com_GoogleCloudPlatform_opentelemetry_operations_go_internal_resourcemapping;https://rawhubusercontent.com/googlecloudplatform/opentelemetry-operations-go/master/LICENSE
github.com_GoogleCloudPlatform_ops_agent;https://rawhubusercontent.com/GoogleCloudPlatform/ops-agent/master/LICENSE
github.com_GoogleCloudPlatform_osconfig;https://rawhubusercontent.com/GoogleCloudPlatform/osconfig/master/LICENSE
github.com_GoogleContainerTools_kpt;https://rawhubusercontent.com/googlecontainertools/kpt/master/LICENSE
github.com_GoogleContainerTools_kpt_porch_api;https://rawhubusercontent.com/googlecontainertools/kpt/master/LICENSE
github.com_JohnCGriffin_overflow;https://rawhubusercontent.com/JohnCGriffin/overflow/master/README.md
github.com_MakeNowJust_heredoc;https://rawhubusercontent.com/makenowjust/heredoc/master/LICENSE
github.com_Masterminds_goutils;https://github.com/masterminds/goutils
github.com_Masterminds_semver;https://github.com/masterminds/semver
github.com_Masterminds_semver_v3;https://github.com/masterminds/semver
github.com_Masterminds_sprig_v3;https://github.com/masterminds/sprig
github.com_NVIDIA_go_dcgm;https://rawhubusercontent.com/nvidia/go-dcgm/master/LICENSE
github.com_NVIDIA_go_nvml;https://rawhubusercontent.com/nvidia/go-nvml/master/LICENSE
github.com_ProtonMail_go_crypto;https://rawhubusercontent.com/protonmail/go-crypto/master/LICENSE
github.com_SAP_go_hdb;https://rawhubusercontent.com/sap/go-hdb/master/LICENSE.md
github.com_Showmax_go_fqdn;https://rawhubusercontent.com/showmax/go-fqdn/master/LICENSE
github.com_acarl005_stripansi;https://github.com/acarl005/stripansi
github.com_acobaugh_osrelease;https://rawhubusercontent.com/acobaugh/osrelease/master/LICENSE
github.com_adrg_xdg;https://rawhubusercontent.com/adrg/xdg/master/LICENSE
github.com_aerospike_aerospike_client_go_v6;https://rawhubusercontent.com/aerospike/aerospike-client-go/master/LICENSE
github.com_agext_levenshtein;https://rawhubusercontent.com/agext/levenshtein/master/LICENSE
github.com_alecthomas_participle_v2;https://github.com/alecthomas/participle
github.com_alecthomas_units;https://github.com/alecthomas/units
github.com_anchore_bubbly;https://rawhubusercontent.com/anchore/bubbly/master/LICENSE
github.com_anchore_clio;https://rawhubusercontent.com/anchore/clio/master/LICENSE
github.com_anchore_fangs;https://rawhubusercontent.com/anchore/fangs/master/LICENSE
github.com_anchore_go_logger;https://rawhubusercontent.com/anchore/go-logger/main/LICENSE
github.com_anchore_go_macholibre;https://rawhubusercontent.com/anchore/go-macholibre/master/LICENSE
github.com_anchore_go_struct_converter;https://rawhubusercontent.com/anchore/go-struct-converter/master/LICENSE
github.com_anchore_go_version;https://rawhubusercontent.com/anchore/go-version/master/LICENSE
github.com_anchore_packageurl_go;https://rawhubusercontent.com/anchore/packageurl-go/master/LICENSE
github.com_anchore_stereoscope;https://rawhubusercontent.com/anchore/stereoscope/master/LICENSE
github.com_anchore_syft;https://rawhubusercontent.com/anchore/syft/master/LICENSE
github.com_andybalholm_brotli;https://rawhubusercontent.com/andybalholm/brotli/master/LICENSE
github.com_apache_arrow_go_v12;https://github.com/apache/arrow
github.com_apache_thrift;https://rawhubusercontent.com/apache/thrift/master/LICENSE
github.com_apparentlymart_go_cidr;https://rawhubusercontent.com/apparentlymart/go-cidr/master/LICENSE
github.com_apparentlymart_go_textseg_v13;https://rawhubusercontent.com/apparentlymart/go-textseg/master/LICENSE
github.com_aquasecurity_go_pep440_version;https://github.com/aquasecurity/go-pep440-version
github.com_aquasecurity_go_version;https://rawhubusercontent.com/aquasecurity/go-version/master/LICENSE
github.com_armon_go_metrics;https://rawhubusercontent.com/armon/go-metrics/master/LICENSE
github.com_asaskevich_govalidator;https://rawhubusercontent.com/asaskevich/govalidator/master/LICENSE
github.com_aws_aws_sdk_go;https://github.com/aws/aws-sdk-go
github.com_aws_aws_sdk_go_v2;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_aws_protocol_eventstream;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_credentials;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_feature_s3_manager;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_internal_configsources;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_internal_endpoints_v2;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_internal_v4a;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_service_internal_accept_encoding;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_service_internal_checksum;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_service_internal_presigned_url;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_service_internal_s3shared;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_service_s3;https://github.com/aws/aws-sdk-go-v2
github.com_aws_smithy_go;https://rawhubusercontent.com/aws/smithy-go/master/LICENSE
github.com_aymanbagabas_go_osc52_v2;https://github.com/aymanbagabas/go-osc52
github.com_becheran_wildmatch_go;https://rawhubusercontent.com/becheran/wildmatch-go/master/LICENSE
github.com_beorn7_perks;https://github.com/beorn7/perks
github.com_bits_and_blooms_bitset;https://rawhubusercontent.com/bits-and-blooms/bitset/master/LICENSE
github.com_bmatcuk_doublestar_v4;https://rawhubusercontent.com/bmatcuk/doublestar/master/LICENSE
github.com_cenkalti_backoff;https://rawhubusercontent.com/cenkalti/backoff/master/LICENSE
github.com_cenkalti_backoff_v4;https://rawhubusercontent.com/cenkalti/backoff/master/LICENSE
github.com_cespare_xxhash_v2;https://github.com/cespare/xxhash
github.com_chai2010_gettext_go;https://github.com/chai2010/gettext-go
github.com_charmbracelet_bubbles;https://rawhubusercontent.com/charmbracelet/bubbles/master/LICENSE
github.com_charmbracelet_bubbletea;https://rawhubusercontent.com/charmbracelet/bubbletea/master/LICENSE
github.com_charmbracelet_harmonica;https://rawhubusercontent.com/charmbracelet/harmonica/master/LICENSE
github.com_charmbracelet_lipgloss;https://rawhubusercontent.com/charmbracelet/lipgloss/master/LICENSE
github.com_cloudflare_circl;https://rawhubusercontent.com/cloudflare/circl/master/LICENSE
github.com_cncf_xds_go;https://rawhubusercontent.com/cncf/xds/master/LICENSE
github.com_containerd_console;https://rawhubusercontent.com/containerd/console/master/LICENSE
github.com_containerd_containerd;https://rawhubusercontent.com/containerd/containerd/master/LICENSE
github.com_containerd_continuity;https://rawhubusercontent.com/containerd/continuity/master/LICENSE
github.com_containerd_fifo;https://rawhubusercontent.com/containerd/fifo/master/LICENSE
github.com_containerd_log;https://rawhubusercontent.com/containerd/log/master/LICENSE
github.com_containerd_stargz_snapshotter_estargz;https://rawhubusercontent.com/containerd/stargz-snapshotter/master/LICENSE
github.com_containerd_ttrpc;https://rawhubusercontent.com/containerd/ttrpc/master/LICENSE
github.com_containerd_typeurl_v2;https://rawhubusercontent.com/containerd/typeurl/master/LICENSE
github.com_cyphar_filepath_securejoin;https://rawhubusercontent.com/cyphar/filepath-securejoin/master/LICENSE
github.com_davecgh_go_spew;https://rawhubusercontent.com/davecgh/go-spew/master/LICENSE
github.com_deitch_magic;https://rawhubusercontent.com/deitch/magic/master/LICENSE
github.com_denisenkom_go_mssqldb;https://github.com/denisenkom/go-mssqldb
github.com_dennwc_varint;https://rawhubusercontent.com/dennwc/varint/master/LICENSE
github.com_dgryski_go_rendezvous;https://rawhubusercontent.com/dgryski/go-rendezvous/master/LICENSE
github.com_digitalocean_godo;https://github.com/digitalocean/godo
github.com_distribution_reference;https://rawhubusercontent.com/distribution/reference/main/LICENSE
github.com_docker_cli;https://rawhubusercontent.com/docker/cli/master/LICENSE
github.com_docker_distribution;https://rawhubusercontent.com/docker/distribution/master/LICENSE
github.com_docker_docker;https://rawhubusercontent.com/docker/docker/master/LICENSE
github.com_docker_docker_credential_helpers;https://rawhubusercontent.com/docker/docker-credential-helpers/master/LICENSE
github.com_docker_go_connections;https://rawhubusercontent.com/docker/go-connections/master/LICENSE
github.com_docker_go_events;https://rawhubusercontent.com/docker/go-events/master/LICENSE
github.com_docker_go_units;https://rawhubusercontent.com/docker/go-units/master/LICENSE
github.com_dsnet_compress;https://rawhubusercontent.com/dsnet/compress/master/LICENSE.md
github.com_dustin_go_humanize;https://rawhubusercontent.com/dustin/go-humanize/master/LICENSE
github.com_dvsekhvalnov_jose2go;https://github.com/dvsekhvalnov/jose2go
github.com_edsrzf_mmap_go;https://rawhubusercontent.com/edsrzf/mmap-go/master/LICENSE
github.com_emicklei_go_restful;https://rawhubusercontent.com/emicklei/go-restful/master/LICENSE
github.com_emicklei_go_restful_v3;https://rawhubusercontent.com/emicklei/go-restful/master/LICENSE
github.com_emirpasic_gods;https://rawhubusercontent.com/emirpasic/gods/master/LICENSE
github.com_envoyproxy_go_control_plane;https://rawhubusercontent.com/envoyproxy/go-control-plane/master/LICENSE
github.com_envoyproxy_protoc_gen_validate;https://rawhubusercontent.com/envoyproxy/protoc-gen-validate/master/LICENSE
github.com_evanphx_json_patch;https://rawhubusercontent.com/evanphx/json-patch/master/LICENSE
github.com_exponent_io_jsonpath;https://rawhubusercontent.com/exponent-io/jsonpath/master/LICENSE
github.com_expr_lang_expr;https://rawhubusercontent.com/expr-lang/expr/master/LICENSE
github.com_facebookincubator_nvdtools;https://rawhubusercontent.com/facebookincubator/nvdtools/master/LICENSE
github.com_fatih_color;https://rawhubusercontent.com/fatih/color/master/LICENSE.md
github.com_felixge_fgprof;https://github.com/felixge/fgprof
github.com_felixge_httpsnoop;https://github.com/felixge/httpsnoop
github.com_form3tech_oss_jwt_go;https://github.com/form3tech-oss/jwt-go
github.com_fsnotify_fsnotify;https://rawhubusercontent.com/fsnotify/fsnotify/master/LICENSE
github.com_gabriel_vasile_mimetype;https://rawhubusercontent.com/gabriel-vasile/mimetype/master/LICENSE
github.com_gammazero_deque;https://rawhubusercontent.com/gammazero/deque/master/LICENSE
github.com_gammazero_workerpool;https://rawhubusercontent.com/gammazero/workerpool/master/LICENSE
github.com_ghodss_yaml;https://rawhubusercontent.com/ghodss/yaml/master/LICENSE
github.com_github_go_spdx_v2;https://rawhubusercontent.com/github/go-spdx/master/LICENSE
github.com_go_errors_errors;https://github.com/go-errors/errors
github.com_go_git_gcfg;https://rawhubusercontent.com/go-git/gcfg/master/LICENSE
github.com_go_git_go_billy_v5;https://rawhubusercontent.com/go-git/go-billy/master/LICENSE
github.com_go_git_go_git_v5;https://rawhubusercontent.com/go-git/go-git/master/LICENSE
github.com_go_ini_ini;https://rawhubusercontent.com/go-ini/ini/master/LICENSE
github.com_go_kit_log;https://rawhubusercontent.com/go-kit/log/master/LICENSE
github.com_go_logfmt_logfmt;https://rawhubusercontent.com/go-logfmt/logfmt/master/LICENSE
github.com_go_logr_logr;https://rawhubusercontent.com/go-logr/logr/master/LICENSE
github.com_go_logr_stdr;https://rawhubusercontent.com/go-logr/stdr/master/LICENSE
github.com_go_openapi_jsonpointer;https://rawhubusercontent.com/go-openapi/jsonpointer/master/LICENSE
github.com_go_openapi_jsonreference;https://rawhubusercontent.com/go-openapi/jsonreference/master/LICENSE
github.com_go_openapi_swag;https://rawhubusercontent.com/go-openapi/swag/master/LICENSE
github.com_go_playground_locales;https://rawhubusercontent.com/go-playground/locales/master/LICENSE
github.com_go_playground_universal_translator;https://rawhubusercontent.com/go-playground/universal-translator/master/LICENSE
github.com_go_playground_validator_v10;https://rawhubusercontent.com/go-playground/validator/master/LICENSE
github.com_go_restruct_restruct;https://rawhubusercontent.com/go-restruct/restruct/master/LICENSE.md
github.com_go_resty_resty_v2;https://rawhubusercontent.com/go-resty/resty/master/LICENSE
github.com_go_sql_driver_mysql;https://rawhubusercontent.com/go-sql-driver/mysql/master/LICENSE
github.com_go_zookeeper_zk;https://rawhubusercontent.com/go-zookeeper/zk/master/LICENSE
github.com_gobwas_glob;https://rawhubusercontent.com/gobwas/glob/master/LICENSE
github.com_goccy_go_json;https://rawhubusercontent.com/goccy/go-json/master/LICENSE
github.com_goccy_go_yaml;https://rawhubusercontent.com/goccy/go-yaml/master/LICENSE
github.com_godbus_dbus;https://rawhubusercontent.com/godbus/dbus/master/LICENSE
github.com_gogo_protobuf;https://rawhubusercontent.com/gogo/protobuf/master/LICENSE
github.com_golang_jwt_jwt_v4;https://rawhubusercontent.com/golang-jwt/jwt/master/LICENSE
github.com_golang_jwt_jwt_v5;https://rawhubusercontent.com/golang-jwt/jwt/master/LICENSE
github.com_golang_sql_civil;https://rawhubusercontent.com/golang-sql/civil/master/LICENSE
github.com_golang_sql_sqlexp;https://rawhubusercontent.com/golang-sql/sqlexp/master/LICENSE
github.com_golang_glog;https://rawhubusercontent.com/golang/glog/master/LICENSE
github.com_golang_groupcache;https://rawhubusercontent.com/golang/groupcache/master/LICENSE
github.com_golang_mock;https://rawhubusercontent.com/golang/mock/master/LICENSE
github.com_golang_protobuf;https://rawhubusercontent.com/golang/protobuf/master/LICENSE
github.com_golang_snappy;https://rawhubusercontent.com/golang/snappy/master/LICENSE
github.com_google_btree;https://rawhubusercontent.com/google/btree/master/LICENSE
github.com_google_flatbuffers;https://rawhubusercontent.com/google/flatbuffers/master/LICENSE
github.com_google_gnostic;https://rawhubusercontent.com/google/gnostic/master/LICENSE
github.com_google_gnostic_models;https://rawhubusercontent.com/google/gnostic-models/master/LICENSE
github.com_google_go_cmp;https://rawhubusercontent.com/google/go-cmp/master/LICENSE
github.com_google_go_containerregistry;https://rawhubusercontent.com/google/go-containerregistry/master/LICENSE
github.com_google_go_cpy;https://rawhubusercontent.com/google/go-cpy/master/LICENSE
github.com_google_go_querystring;https://rawhubusercontent.com/google/go-querystring/master/LICENSE
github.com_google_go_sev_guest;https://rawhubusercontent.com/google/go-sev-guest/master/LICENSE
github.com_google_go_tpm;https://rawhubusercontent.com/google/go-tpm/master/LICENSE
github.com_google_go_tpm_tools;https://rawhubusercontent.com/google/go-tpm-tools/master/LICENSE
github.com_google_gofuzz;https://rawhubusercontent.com/google/gofuzz/master/LICENSE
github.com_google_licensecheck;https://rawhubusercontent.com/google/licensecheck/master/LICENSE
github.com_google_logger;https://rawhubusercontent.com/google/logger/master/LICENSE
github.com_google_pprof;https://rawhubusercontent.com/google/pprof/master/LICENSE
github.com_google_s2a_go;https://github.com/google/s2a-go
github.com_google_shlex;https://github.com/google/shlex
github.com_google_tink_go;https://rawhubusercontent.com/google/tink/master/LICENSE
github.com_google_uuid;https://rawhubusercontent.com/google/uuid/master/LICENSE
github.com_googleapis_enterprise_certificate_proxy;https://rawhubusercontent.com/googleapis/enterprise-certificate-proxy/master/LICENSE
github.com_googleapis_gax_go_v2;https://rawhubusercontent.com/googleapis/gax-go/master/LICENSE
github.com_gookit_color;https://rawhubusercontent.com/gookit/color/master/LICENSE
github.com_gophercloud_gophercloud;https://rawhubusercontent.com/gophercloud/gophercloud/master/LICENSE
github.com_gorilla_websocket;https://rawhubusercontent.com/gorilla/websocket/master/LICENSE
github.com_grafana_regexp;https://rawhubusercontent.com/grafana/regexp/master/LICENSE
github.com_gregjones_httpcache;https://github.com/gregjones/httpcache
github.com_grobie_gomemcache;https://rawhubusercontent.com/grobie/gomemcache/master/LICENSE
github.com_grpc_ecosystem_go_grpc_middleware;https://rawhubusercontent.com/grpc-ecosystem/go-grpc-middleware/master/LICENSE
github.com_grpc_ecosystem_grpc_gateway_v2;https://rawhubusercontent.com/grpc-ecosystem/grpc-gateway/master/LICENSE
github.com_gsterjov_go_libsecret;https://rawhubusercontent.com/gsterjov/go-libsecret/master/LICENSE
github.com_hashicorp_consul_api;https://rawhubusercontent.com/hashicorp/consul/master/LICENSE
github.com_hashicorp_cronexpr;https://rawhubusercontent.com/hashicorp/cronexpr/master/LICENSE
github.com_hashicorp_errwrap;https://rawhubusercontent.com/hashicorp/errwrap/master/LICENSE
github.com_hashicorp_go_checkpoint;https://rawhubusercontent.com/hashicorp/go-checkpoint/master/LICENSE
github.com_hashicorp_go_cleanhttp;https://rawhubusercontent.com/hashicorp/go-cleanhttp/master/LICENSE
github.com_hashicorp_go_cty;https://rawhubusercontent.com/hashicorp/go-cty/master/LICENSE
github.com_hashicorp_go_hclog;https://rawhubusercontent.com/hashicorp/go-hclog/master/LICENSE
github.com_hashicorp_go_immutable_radix;https://rawhubusercontent.com/hashicorp/go-immutable-radix/master/LICENSE
github.com_hashicorp_go_multierror;https://rawhubusercontent.com/hashicorp/go-multierror/master/LICENSE
github.com_hashicorp_go_plugin;https://rawhubusercontent.com/hashicorp/go-plugin/master/LICENSE
github.com_hashicorp_go_retryablehttp;https://rawhubusercontent.com/hashicorp/go-retryablehttp/master/LICENSE
github.com_hashicorp_go_rootcerts;https://rawhubusercontent.com/hashicorp/go-rootcerts/master/LICENSE
github.com_hashicorp_go_uuid;https://rawhubusercontent.com/hashicorp/go-uuid/master/LICENSE
github.com_hashicorp_go_version;https://rawhubusercontent.com/hashicorp/go-version/master/LICENSE
github.com_hashicorp_golang_lru;https://rawhubusercontent.com/hashicorp/golang-lru/master/LICENSE
github.com_hashicorp_hc_install;https://rawhubusercontent.com/hashicorp/hc-install/master/LICENSE
github.com_hashicorp_hcl;https://rawhubusercontent.com/hashicorp/hcl/master/LICENSE
github.com_hashicorp_hcl_v2;https://rawhubusercontent.com/hashicorp/hcl/master/LICENSE
github.com_hashicorp_logutils;https://rawhubusercontent.com/hashicorp/logutils/master/LICENSE
github.com_hashicorp_nomad_api;https://rawhubusercontent.com/hashicorp/nomad/master/LICENSE
github.com_hashicorp_serf;https://rawhubusercontent.com/hashicorp/serf/master/LICENSE
github.com_hashicorp_terraform_exec;https://rawhubusercontent.com/hashicorp/terraform-exec/master/LICENSE
github.com_hashicorp_terraform_json;https://rawhubusercontent.com/hashicorp/terraform-json/master/LICENSE
github.com_hashicorp_terraform_plugin_go;https://rawhubusercontent.com/hashicorp/terraform-plugin-go/master/LICENSE
github.com_hashicorp_terraform_plugin_log;https://rawhubusercontent.com/hashicorp/terraform-plugin-log/master/LICENSE
github.com_hashicorp_terraform_plugin_sdk_v2;https://rawhubusercontent.com/hashicorp/terraform-plugin-sdk/master/LICENSE
github.com_hashicorp_terraform_registry_address;https://rawhubusercontent.com/hashicorp/terraform-registry-address/master/LICENSE
github.com_hashicorp_terraform_svchost;https://rawhubusercontent.com/hashicorp/terraform-svchost/master/LICENSE
github.com_hashicorp_yamux;https://rawhubusercontent.com/hashicorp/yamux/master/LICENSE
github.com_hetznercloud_hcloud_go;https://rawhubusercontent.com/hetznercloud/hcloud-go/master/LICENSE
github.com_hetznercloud_hcloud_go_v2;https://rawhubusercontent.com/hetznercloud/hcloud-go/master/LICENSE
github.com_huandu_xstrings;https://rawhubusercontent.com/huandu/xstrings/master/LICENSE
github.com_iancoleman_strcase;https://rawhubusercontent.com/iancoleman/strcase/master/LICENSE
github.com_imdario_mergo;https://rawhubusercontent.com/imdario/mergo/master/LICENSE
github.com_influxdata_go_syslog_v3;https://rawhubusercontent.com/influxdata/go-syslog/master/LICENSE
github.com_ionos_cloud_sdk_go_v6;https://rawhubusercontent.com/ionos-cloud/sdk-go/master/LICENSE
github.com_jbenet_go_context;https://rawhubusercontent.com/jbenet/go-context/master/LICENSE
github.com_jinzhu_copier;https://github.com/jinzhu/copier
github.com_jmespath_go_jmespath;https://rawhubusercontent.com/jmespath/go-jmespath/master/LICENSE
github.com_josharian_intern;https://rawhubusercontent.com/josharian/intern/master/LICENSE.md
github.com_jpillora_backoff;https://rawhubusercontent.com/jpillora/backoff/master/LICENSE
github.com_json_iterator_go;https://rawhubusercontent.com/json-iterator/go/master/LICENSE
github.com_julienschmidt_httprouter;https://rawhubusercontent.com/julienschmidt/httprouter/master/LICENSE
github.com_kardianos_osext;https://rawhubusercontent.com/kardianos/osext/master/LICENSE
github.com_kardianos_service;https://rawhubusercontent.com/kardianos/service/master/LICENSE
github.com_kastenhq_goversion;https://rawhubusercontent.com/kastenhq/goversion/master/LICENSE
github.com_kevinburke_ssh_config;https://rawhubusercontent.com/kevinburke/ssh_config/master/LICENSE
github.com_klauspost_compress;https://rawhubusercontent.com/klauspost/compress/master/LICENSE
github.com_klauspost_cpuid_v2;https://rawhubusercontent.com/klauspost/cpuid/master/LICENSE
github.com_klauspost_pgzip;https://rawhubusercontent.com/klauspost/pgzip/master/LICENSE
github.com_knadh_koanf;https://rawhubusercontent.com/knadh/koanf/master/LICENSE
github.com_knadh_koanf_v2;https://rawhubusercontent.com/knadh/koanf/master/LICENSE
github.com_knqyf263_go_rpmdb;https://github.com/knqyf263/go-rpmdb
github.com_kolo_xmlrpc;https://rawhubusercontent.com/kolo/xmlrpc/master/LICENSE
github.com_kylelemons_godebug;https://rawhubusercontent.com/kylelemons/godebug/master/LICENSE
github.com_leodido_go_urn;https://rawhubusercontent.com/leodido/go-urn/master/LICENSE
github.com_leodido_ragel_machinery;https://rawhubusercontent.com/leodido/ragel-machinery/master/LICENSE
github.com_lib_pq;https://rawhubusercontent.com/lib/pq/master/LICENSE.md
github.com_liggitt_tabwriter;https://rawhubusercontent.com/liggitt/tabwriter/master/LICENSE
github.com_linode_linodego;https://rawhubusercontent.com/linode/linodego/master/LICENSE
github.com_lucasb_eyer_go_colorful;https://rawhubusercontent.com/lucasb-eyer/go-colorful/master/LICENSE
github.com_magiconair_properties;https://rawhubusercontent.com/magiconair/properties/master/LICENSE.md
github.com_mailru_easyjson;https://rawhubusercontent.com/mailru/easyjson/master/LICENSE
github.com_mattn_go_colorable;https://rawhubusercontent.com/mattn/go-colorable/master/LICENSE
github.com_mattn_go_isatty;https://rawhubusercontent.com/mattn/go-isatty/master/LICENSE
github.com_mattn_go_localereader;https://rawhubusercontent.com/mattn/go-localereader/master/LICENSE
github.com_mattn_go_runewidth;https://rawhubusercontent.com/mattn/go-runewidth/master/LICENSE
github.com_matttproud_golang_protobuf_extensions;https://rawhubusercontent.com/matttproud/golang_protobuf_extensions/master/LICENSE
github.com_matttproud_golang_protobuf_extensions_v2;https://rawhubusercontent.com/matttproud/golang_protobuf_extensions/master/LICENSE
github.com_mgutz_ansi;https://rawhubusercontent.com/mgutz/ansi/master/LICENSE
github.com_mholt_archiver_v3;https://rawhubusercontent.com/mholt/archiver/master/LICENSE
github.com_microsoft_go_rustaudit;https://rawhubusercontent.com/microsoft/go-rustaudit/master/LICENSE
github.com_miekg_dns;https://rawhubusercontent.com/miekg/dns/master/LICENSE
github.com_mitchellh_copystructure;https://rawhubusercontent.com/mitchellh/copystructure/master/LICENSE
github.com_mitchellh_go_homedir;https://rawhubusercontent.com/mitchellh/go-homedir/master/LICENSE
github.com_mitchellh_go_testing_interface;https://rawhubusercontent.com/mitchellh/go-testing-interface/master/LICENSE
github.com_mitchellh_go_wordwrap;https://rawhubusercontent.com/mitchellh/go-wordwrap/master/LICENSE.md
github.com_mitchellh_hashstructure;https://rawhubusercontent.com/mitchellh/hashstructure/master/LICENSE
github.com_mitchellh_hashstructure_v2;https://rawhubusercontent.com/mitchellh/hashstructure/master/LICENSE
github.com_mitchellh_mapstructure;https://rawhubusercontent.com/mitchellh/mapstructure/master/LICENSE
github.com_mitchellh_reflectwalk;https://rawhubusercontent.com/mitchellh/reflectwalk/master/LICENSE
github.com_moby_locker;https://rawhubusercontent.com/moby/locker/master/LICENSE
github.com_moby_spdystream;https://rawhubusercontent.com/moby/spdystream/master/LICENSE
github.com_moby_sys_mountinfo;https://rawhubusercontent.com/moby/sys/master/LICENSE
github.com_moby_sys_signal;https://rawhubusercontent.com/moby/sys/master/LICENSE
github.com_moby_term;https://rawhubusercontent.com/moby/term/master/LICENSE
github.com_modern_go_concurrent;https://rawhubusercontent.com/modern-go/concurrent/master/LICENSE
github.com_modern_go_reflect2;https://github.com/modern-go/reflect2
github.com_monochromegane_go_gitignore;https://rawhubusercontent.com/monochromegane/go-gitignore/master/LICENSE
github.com_montanaflynn_stats;https://rawhubusercontent.com/montanaflynn/stats/master/LICENSE
github.com_mostynb_go_grpc_compression;https://rawhubusercontent.com/mostynb/go-grpc-compression/master/LICENSE
github.com_mtibben_percent;https://rawhubusercontent.com/mtibben/percent/master/LICENSE
github.com_muesli_ansi;https://rawhubusercontent.com/muesli/ansi/master/LICENSE
github.com_muesli_cancelreader;https://rawhubusercontent.com/muesli/cancelreader/master/LICENSE
github.com_muesli_reflow;https://rawhubusercontent.com/muesli/reflow/master/LICENSE
github.com_muesli_termenv;https://rawhubusercontent.com/muesli/termenv/master/LICENSE
github.com_munnerz_goautoneg;https://rawhubusercontent.com/munnerz/goautoneg/master/LICENSE
github.com_mwitkow_go_conntrack;https://rawhubusercontent.com/mwitkow/go-conntrack/master/LICENSE
github.com_nasa9084_go_openapi;https://github.com/nasa9084/go-openapi
github.com_nginxinc_nginx_prometheus_exporter;https://rawhubusercontent.com/nginxinc/nginx-prometheus-exporter/master/LICENSE
github.com_nwaples_rardecode;https://rawhubusercontent.com/nwaples/rardecode/master/LICENSE
github.com_oklog_run;https://rawhubusercontent.com/oklog/run/master/LICENSE
github.com_olekukonko_tablewriter;https://rawhubusercontent.com/olekukonko/tablewriter/master/LICENSE.md
github.com_open_telemetry_opentelemetry_collector_contrib_exporter_fileexporter;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_exporter_googlecloudexporter;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_internal_aws_ecsutil;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_internal_common;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_internal_coreinternal;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_internal_filter;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_internal_k8sconfig;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_internal_metadataproviders;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_internal_sharedcomponent;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_pkg_ottl;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_pkg_pdatautil;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_pkg_stanza;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_pkg_translator_prometheus;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_processor_filterprocessor;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_processor_groupbyattrsprocessor;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_processor_metricstransformprocessor;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_processor_resourcedetectionprocessor;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_processor_resourceprocessor;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_processor_transformprocessor;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_activedirectorydsreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_aerospikereceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_apachereceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_couchdbreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_elasticsearchreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_filelogreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_flinkmetricsreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_hostmetricsreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_iisreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_jmxreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_memcachedreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_mysqlreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_nginxreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_postgresqlreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_rabbitmqreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_redisreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_saphanareceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_sqlqueryreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_sqlserverreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_windowsperfcountersreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_zookeeperreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_opencontainers_go_digest;https://rawhubusercontent.com/opencontainers/go-digest/master/LICENSE
github.com_opencontainers_image_spec;https://rawhubusercontent.com/opencontainers/image-spec/master/LICENSE
github.com_opencontainers_runc;https://rawhubusercontent.com/opencontainers/runc/master/LICENSE
github.com_opencontainers_runtime_spec;https://rawhubusercontent.com/opencontainers/runtime-spec/master/LICENSE
github.com_opencontainers_selinux;https://rawhubusercontent.com/opencontainers/selinux/master/LICENSE
github.com_openshift_api;https://rawhubusercontent.com/openshift/api/master/LICENSE
github.com_openshift_client_go;https://rawhubusercontent.com/openshift/client-go/master/LICENSE
github.com_otiai10_copy;https://github.com/otiai10/copy
github.com_ovh_go_ovh;https://rawhubusercontent.com/ovh/go-ovh/master/LICENSE
github.com_pborman_indent;https://rawhubusercontent.com/pborman/indent/master/LICENSE
github.com_pborman_uuid;https://rawhubusercontent.com/pborman/uuid/master/LICENSE
github.com_pelletier_go_toml;https://rawhubusercontent.com/pelletier/go-toml/master/LICENSE
github.com_pelletier_go_toml_v2;https://rawhubusercontent.com/pelletier/go-toml/master/LICENSE
github.com_peterbourgon_diskv;https://rawhubusercontent.com/peterbourgon/diskv/master/LICENSE
github.com_pierrec_lz4_v4;https://github.com/pierrec/lz4
github.com_pjbgf_sha1cd;https://github.com/pjbgf/sha1cd
github.com_pkg_browser;https://rawhubusercontent.com/pkg/browser/master/LICENSE
github.com_pkg_errors;https://rawhubusercontent.com/pkg/errors/master/LICENSE
github.com_pkg_profile;https://rawhubusercontent.com/pkg/profile/master/LICENSE
github.com_pmezard_go_difflib;https://rawhubusercontent.com/pmezard/go-difflib/master/LICENSE
github.com_prometheus_client_golang;https://rawhubusercontent.com/prometheus/client_golang/master/LICENSE
github.com_prometheus_client_model;https://rawhubusercontent.com/prometheus/client_model/master/LICENSE
github.com_prometheus_common;https://rawhubusercontent.com/prometheus/common/master/LICENSE
github.com_prometheus_common_sigv4;https://rawhubusercontent.com/prometheus/common/master/LICENSE
github.com_prometheus_procfs;https://rawhubusercontent.com/prometheus/procfs/master/LICENSE
github.com_prometheus_prometheus;https://rawhubusercontent.com/prometheus/prometheus/master/LICENSE
github.com_prometheus_statsd_exporter;https://rawhubusercontent.com/prometheus/statsd_exporter/master/LICENSE
github.com_redis_go_redis_v9;https://rawhubusercontent.com/redis/go-redis/master/LICENSE
github.com_remyoudompheng_bigfft;https://rawhubusercontent.com/remyoudompheng/bigfft/master/LICENSE
github.com_rivo_uniseg;https://github.com/rivo/uniseg
github.com_robfig_cron_v3;https://rawhubusercontent.com/robfig/cron/master/LICENSE
github.com_rs_cors;https://rawhubusercontent.com/rs/cors/master/LICENSE
github.com_russross_blackfriday;https://github.com/russross/blackfriday
github.com_saferwall_pe;https://rawhubusercontent.com/saferwall/pe/master/LICENSE
github.com_saintfish_chardet;https://rawhubusercontent.com/saintfish/chardet/master/LICENSE
github.com_sassoftware_go_rpmutils;https://rawhubusercontent.com/sassoftware/go-rpmutils/master/LICENSE
github.com_scaleway_scaleway_sdk_go;https://rawhubusercontent.com/scaleway/scaleway-sdk-go/master/LICENSE
github.com_scylladb_go_set;https://rawhubusercontent.com/scylladb/go-set/master/LICENSE
github.com_sergi_go_diff;https://rawhubusercontent.com/sergi/go-diff/master/LICENSE
github.com_shirou_gopsutil;https://rawhubusercontent.com/shirou/gopsutil/master/LICENSE
github.com_shirou_gopsutil_v3;https://rawhubusercontent.com/shirou/gopsutil/master/LICENSE
github.com_shopspring_decimal;https://rawhubusercontent.com/shopspring/decimal/master/LICENSE
github.com_sijms_go_ora_v2;https://rawhubusercontent.com/sijms/go-ora/master/LICENSE
github.com_sirupsen_logrus;https://rawhubusercontent.com/sirupsen/logrus/master/LICENSE
github.com_skeema_knownhosts;https://rawhubusercontent.com/skeema/knownhosts/master/LICENSE
github.com_snowflakedb_gosnowflake;https://rawhubusercontent.com/snowflakedb/gosnowflake/master/LICENSE
github.com_spdx_tools_golang;https://github.com/spdx/tools-golang
github.com_spf13_afero;https://github.com/spf13/afero
github.com_spf13_cast;https://github.com/spf13/cast
github.com_spf13_cobra;https://github.com/spf13/cobra
github.com_spf13_jwalterweatherman;https://github.com/spf13/jwalterweatherman
github.com_spf13_pflag;https://github.com/spf13/pflag
github.com_spf13_viper;https://github.com/spf13/viper
github.com_stretchr_objx;https://rawhubusercontent.com/stretchr/objx/master/LICENSE
github.com_stretchr_testify;https://rawhubusercontent.com/stretchr/testify/master/LICENSE
github.com_subosito_gotenv;https://rawhubusercontent.com/subosito/gotenv/master/LICENSE
github.com_sylabs_sif_v2;https://rawhubusercontent.com/sylabs/sif/master/LICENSE.md
github.com_sylabs_squashfs;https://rawhubusercontent.com/sylabs/squashfs/master/LICENSE
github.com_tarm_serial;https://rawhubusercontent.com/tarm/serial/master/LICENSE
github.com_therootcompany_xz;https://rawhubusercontent.com/therootcompany/xz/master/LICENSE
github.com_tidwall_gjson;https://rawhubusercontent.com/tidwall/gjson/master/LICENSE
github.com_tidwall_match;https://rawhubusercontent.com/tidwall/match/master/LICENSE
github.com_tidwall_pretty;https://rawhubusercontent.com/tidwall/pretty/master/LICENSE
github.com_tidwall_tinylru;https://rawhubusercontent.com/tidwall/tinylru/master/LICENSE
github.com_tidwall_wal;https://rawhubusercontent.com/tidwall/wal/master/LICENSE
github.com_tklauser_go_sysconf;https://rawhubusercontent.com/tklauser/go-sysconf/master/LICENSE
github.com_tklauser_numcpus;https://rawhubusercontent.com/tklauser/numcpus/master/LICENSE
github.com_ulikunitz_xz;https://rawhubusercontent.com/ulikunitz/xz/master/LICENSE
github.com_vbatts_go_mtree;https://rawhubusercontent.com/vbatts/go-mtree/master/LICENSE
github.com_vbatts_tar_split;https://rawhubusercontent.com/vbatts/tar-split/master/LICENSE
github.com_vifraa_gopom;https://rawhubusercontent.com/vifraa/gopom/master/LICENSE
github.com_vmihailenco_msgpack;https://rawhubusercontent.com/vmihailenco/msgpack/master/LICENSE
github.com_vmihailenco_msgpack_v4;https://rawhubusercontent.com/vmihailenco/msgpack/master/LICENSE
github.com_vmihailenco_tagparser;https://rawhubusercontent.com/vmihailenco/tagparser/master/LICENSE
github.com_vultr_govultr_v2;https://rawhubusercontent.com/vultr/govultr/master/LICENSE
github.com_wagoodman_go_partybus;https://rawhubusercontent.com/wagoodman/go-partybus/master/LICENSE
github.com_wagoodman_go_progress;https://rawhubusercontent.com/wagoodman/go-progress/master/LICENSE
github.com_xanzy_ssh_agent;https://rawhubusercontent.com/xanzy/ssh-agent/master/LICENSE
github.com_xdg_go_pbkdf2;https://github.com/xdg-go/pbkdf2
github.com_xdg_go_scram;https://rawhubusercontent.com/xdg-go/scram/master/LICENSE
github.com_xdg_go_stringprep;https://rawhubusercontent.com/xdg-go/stringprep/master/LICENSE
github.com_xi2_xz;https://rawhubusercontent.com/xi2/xz/master/LICENSE
github.com_xlab_treeprint;https://rawhubusercontent.com/xlab/treeprint/master/LICENSE
github.com_xo_terminfo;https://rawhubusercontent.com/xo/terminfo/master/LICENSE
github.com_youmark_pkcs8;https://rawhubusercontent.com/youmark/pkcs8/master/LICENSE
github.com_yuin_gopher_lua;https://rawhubusercontent.com/yuin/gopher-lua/master/LICENSE
github.com_zclconf_go_cty;https://rawhubusercontent.com/zclconf/go-cty/master/LICENSE
github.com_zeebo_xxh3;https://github.com/zeebo/xxh3
github.com_zyedidia_generic;https://rawhubusercontent.com/zyedidia/generic/master/LICENSE
github_codeql_action_analyze;https://rawhubusercontent.com/github/codeql-action/main/LICENSE
github_codeql_action_autobuild;https://rawhubusercontent.com/github/codeql-action/main/LICENSE
github_codeql_action_init;https://rawhubusercontent.com/github/codeql-action/main/LICENSE
go.chromium.org_luci;https://chromium.googlesource.com/infra/luci/luci-go
go.mongodb.org_mongo_driver;https://rawhubusercontent.com/mongodb/mongo-go-driver/master/LICENSE
go.mozilla.org_pkcs7;https://github.com/mozilla-services/pkcs7
go.opencensus.io;https://rawhubusercontent.com/census-instrumentation/opencensus-go/master/LICENSE
go.opentelemetry.io_collector;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_component;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_config_configauth;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_config_configcompression;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_config_configgrpc;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_config_confighttp;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_config_confignet;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_config_configopaque;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_config_configtelemetry;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_config_configtls;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_config_internal;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_confmap;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_connector;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_consumer;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_exporter;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_exporter_loggingexporter;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_exporter_otlpexporter;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_exporter_otlphttpexporter;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_extension;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_extension_auth;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_extension_ballastextension;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_extension_zpagesextension;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_featuregate;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_otelcol;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_pdata;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_processor;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_processor_batchprocessor;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_processor_memorylimiterprocessor;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_receiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_receiver_otlpreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_semconv;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_service;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_contrib_config;https://rawhubusercontent.com/open-telemetry/opentelemetry-go-contrib/master/LICENSE
go.opentelemetry.io_contrib_detectors_gcp;https://rawhubusercontent.com/open-telemetry/opentelemetry-go-contrib/master/LICENSE
go.opentelemetry.io_contrib_instrumentation_google.golang.org_grpc_otelgrpc;https://rawhubusercontent.com/open-telemetry/opentelemetry-go-contrib/master/LICENSE
go.opentelemetry.io_contrib_instrumentation_net_http_otelhttp;https://rawhubusercontent.com/open-telemetry/opentelemetry-go-contrib/master/LICENSE
go.opentelemetry.io_contrib_propagators_b3;https://rawhubusercontent.com/open-telemetry/opentelemetry-go-contrib/master/LICENSE
go.opentelemetry.io_contrib_zpages;https://rawhubusercontent.com/open-telemetry/opentelemetry-go-contrib/master/LICENSE
go.opentelemetry.io_otel;https://rawhubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_bridge_opencensus;https://rawhubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_exporters_otlp_otlpmetric_otlpmetricgrpc;https://rawhubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_exporters_otlp_otlpmetric_otlpmetrichttp;https://rawhubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_exporters_otlp_otlptrace;https://rawhubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_exporters_otlp_otlptrace_otlptracegrpc;https://rawhubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_exporters_otlp_otlptrace_otlptracehttp;https://rawhubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_exporters_prometheus;https://rawhubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_exporters_stdout_stdoutmetric;https://rawhubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_exporters_stdout_stdouttrace;https://rawhubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_metric;https://rawhubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_sdk;https://rawhubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_sdk_metric;https://rawhubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_trace;https://rawhubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_proto_otlp;https://rawhubusercontent.com/open-telemetry/opentelemetry-proto-go/master/LICENSE
go.starlark.net;https://rawhubusercontent.com/google/starlark-go/master/LICENSE
go.uber.org_atomic;https://github.com/uber-go/atomic
go.uber.org_multierr;https://github.com/uber-go/multierr
go.uber.org_zap;https://rawhubusercontent.com/uber-go/zap/master/LICENSE
golang.org_x_crypto;https://go.googlesource.com/crypto
golang.org_x_exp;https://go.googlesource.com/exp
golang.org_x_mod;https://go.googlesource.com/mod
golang.org_x_net;https://go.googlesource.com/net
golang.org_x_oauth2;https://go.googlesource.com/oauth2
golang.org_x_sync;https://go.googlesource.com/sync
golang.org_x_sys;https://go.googlesource.com/sys
golang.org_x_term;https://go.googlesource.com/term
golang.org_x_text;https://go.googlesource.com/text
golang.org_x_time;https://go.googlesource.com/time
golang.org_x_xerrors;https://go.googlesource.com/xerrors
gonum.org_v1_gonum;https://rawhubusercontent.com/gonum/gonum/master/LICENSE
google_api_core;https://rawhubusercontent.com/googleapis/python-api-core/master/LICENSE
google_auth;https://rawhubusercontent.com/googleapis/google-auth-library-python/master/LICENSE
google_cloud_compute;https://rawhubusercontent.com/googleapis/python-compute/master/LICENSE
google_cloud_core;https://rawhubusercontent.com/googleapis/python-cloud-core/master/LICENSE
google_cloud_storage;https://rawhubusercontent.com/googleapis/python-storage/master/LICENSE
google_crc32c;https://github.com/googleapis/python-crc32c
google_resumable_media;https://rawhubusercontent.com/googleapis/google-resumable-media-python/master/LICENSE
google.golang.org_api;https://rawhubusercontent.com/googleapis/google-api-go-client/master/LICENSE
google.golang.org_appengine;https://rawhubusercontent.com/golang/appengine/master/LICENSE
google.golang.org_genproto;https://rawhubusercontent.com/googleapis/go-genproto/master/LICENSE
google.golang.org_genproto_googleapis_api;https://rawhubusercontent.com/googleapis/go-genproto/master/LICENSE
google.golang.org_genproto_googleapis_rpc;https://rawhubusercontent.com/googleapis/go-genproto/master/LICENSE
google.golang.org_grpc;https://rawhubusercontent.com/grpc/grpc-go/master/LICENSE
google.golang.org_protobuf;https://go.googlesource.com/protobuf
googleapis_common_protos;https://rawhubusercontent.com/googleapis/python-api-common-protos/master/LICENSE
gopkg.in_inf.v0;https://gopkg.in/inf.v0
gopkg.in_ini.v1;https://gopkg.in/ini.v1
gopkg.in_natefinch_lumberjack.v2;https://gopkg.in/natefinch/lumberjack.v2
gopkg.in_warnings.v0;https://gopkg.in/warnings.v0
gopkg.in_yaml.v2;https://gopkg.in/yaml.v2
gopkg.in_yaml.v3;https://gopkg.in/yaml.v3
groovy;https://rawhubusercontent.com/apache/groovy/master/LICENSE
groovy_all;https://rawhubusercontent.com/apache/groovy/master/LICENSE
groovy_ant;https://rawhubusercontent.com/apache/groovy/master/LICENSE
groovy_bsf;https://rawhubusercontent.com/apache/groovy/master/LICENSE
groovy_console;https://rawhubusercontent.com/apache/groovy/master/LICENSE
groovy_docgenerator;https://rawhubusercontent.com/apache/groovy/master/LICENSE
groovy_groovydoc;https://rawhubusercontent.com/apache/groovy/master/LICENSE
groovy_groovysh;https://rawhubusercontent.com/apache/groovy/master/LICENSE
groovy_jmx;https://rawhubusercontent.com/apache/groovy/master/LICENSE
groovy_json;https://rawhubusercontent.com/apache/groovy/master/LICENSE
groovy_jsr223;https://rawhubusercontent.com/apache/groovy/master/LICENSE
groovy_nio;https://rawhubusercontent.com/apache/groovy/master/LICENSE
groovy_sandbox;https://rawhubusercontent.com/jenkinsci/groovy-sandbox/master/LICENSE.md
groovy_servlet;https://rawhubusercontent.com/apache/groovy/master/LICENSE
groovy_sql;https://rawhubusercontent.com/apache/groovy/master/LICENSE
groovy_swing;https://rawhubusercontent.com/apache/groovy/master/LICENSE
groovy_templates;https://rawhubusercontent.com/apache/groovy/master/LICENSE
groovy_test;https://rawhubusercontent.com/apache/groovy/master/LICENSE
groovy_testng;https://rawhubusercontent.com/apache/groovy/master/LICENSE
groovy_xml;https://rawhubusercontent.com/apache/groovy/master/LICENSE
grpcio;https://rawhubusercontent.com/grpc/grpc/master/LICENSE
gson;https://rawhubusercontent.com/google/gson/master/LICENSE
guava;https://rawhubusercontent.com/google/guava/master/LICENSE
guice;https://github.com/google/guice
hamcrest_all;https://rawhubusercontent.com/hamcrest/JavaHamcrest/master/LICENSE.txt
hamcrest_core;https://rawhubusercontent.com/hamcrest/JavaHamcrest/master/LICENSE.txt
hamcrest_generator;https://rawhubusercontent.com/hamcrest/JavaHamcrest/master/LICENSE.txt
hamcrest_integration;https://rawhubusercontent.com/hamcrest/JavaHamcrest/master/LICENSE.txt
hamcrest_library;https://rawhubusercontent.com/hamcrest/JavaHamcrest/master/LICENSE.txt
hamcrest_unit_test;https://rawhubusercontent.com/hamcrest/JavaHamcrest/master/LICENSE.txt
hawtjni_runtime;https://rawhubusercontent.com/fusesource/hawtjni/master/license.txt
http2_common;https://github.com/eclipse/jetty.project
http2_hpack;https://github.com/eclipse/jetty.project
http2_server;https://github.com/eclipse/jetty.project
httpasyncclient;https://svn.apache.org/repos/asf/httpcomponents/httpasyncclient/branches/4.1.x
httpasyncclient_cache;https://svn.apache.org/repos/asf/httpcomponents/httpasyncclient/branches/4.1.x
httpbin;https://rawhubusercontent.com/requests/httpbin/master/LICENSE
httpclient;http://hc.apache.org/httpcomponents-client-ga
httpclient_cache;http://hc.apache.org/httpcomponents-client-ga
httpcore;http://hc.apache.org/httpcomponents-core-ga
httpcore_nio;http://hc.apache.org/httpcomponents-core-ga
httplib2;https://github.com/httplib2/httplib2
httpmime;http://hc.apache.org/httpcomponents-client-ga
idna;https://rawhubusercontent.com/kjd/idna/master/LICENSE.md
importlib_metadata;https://rawhubusercontent.com/python/importlib_metadata/master/LICENSE
instance_identity;https://github.com/jenkinsci/instance-identity-plugin
ionicons_api;https://rawhubusercontent.com/jenkinsci/ionicons-api-plugin/master/LICENSE
isorelax;https://rawhubusercontent.com/sonatype/oss-parents/master/jvnet-parent/pom.xml
istack_commons_runtime;https://rawhubusercontent.com/eclipse-ee4j/jaxb-istack-commons/master/LICENSE.md
ivy;https://svn.apache.org/repos/asf/ant/ivy/core/trunk
j_interop;http://kohsuke.org/
j_interopdeps;http://kohsuke.org/
jackson_annotations;https://rawhubusercontent.com/FasterXML/jackson-annotations/master/LICENSE
jackson_core;https://rawhubusercontent.com/FasterXML/jackson-core/master/LICENSE
jackson_databind;https://rawhubusercontent.com/FasterXML/jackson-databind/master/LICENSE
jackson_dataformat_cbor;https://rawhubusercontent.com/FasterXML/jackson-dataformats-binary/master/LICENSE
jackson_dataformat_xml;http://github.com/FasterXML/jackson-dataformat-xml
jackson_dataformat_yaml;https://rawhubusercontent.com/FasterXML/jackson-dataformats-text/master/LICENSE
jackson_datatype_jdk8;http://github.com/FasterXML/jackson-modules-java8
jackson_datatype_json_org;https://rawhubusercontent.com/FasterXML/jackson-datatypes-misc/master/LICENSE
jackson_datatype_jsr310;http://github.com/FasterXML/jackson-modules-java8
jackson_module_jaxb_annotations;https://rawhubusercontent.com/FasterXML/jackson-modules-base/master/LICENSE
jackson_module_parameter_names;http://github.com/FasterXML/jackson-modules-java8
jackson2_api;https://github.com/jenkinsci/jackson2-api-plugin
jakarta_activation_api;https://rawhubusercontent.com/jenkinsci/jakarta-activation-api-plugin/master/LICENSE
jakarta_mail_api;https://rawhubusercontent.com/jenkinsci/jakarta-mail-api-plugin/master/LICENSE
jakarta.activation;https://rawhubusercontent.com/jakartaee/jaf-api/master/LICENSE.md
jakarta.annotation_api;https://github.com/eclipse-ee4j/common-annotations-api
jakarta.inject_api;https://github.com/eclipse-ee4j/injection-api
jakarta.mail;https://github.com/eclipse-ee4j/mail
jakarta.servlet.jsp.jstl_api;https://github.com/eclipse-ee4j/jstl-api
jakarta.websocket_api;https://github.com/eclipse-ee4j/websocket-api
jakarta.websocket_client_api;https://github.com/eclipse-ee4j/websocket-api
jansi;https://rawhubusercontent.com/fusesource/jansi/master/license.txt
jansi_native;https://rawhubusercontent.com/fusesource/jansi/master/license.txt
jaraco_classes;https://rawhubusercontent.com/jaraco/jaraco.classes/main/LICENSE
javax_activation_api;https://rawhubusercontent.com/jenkinsci/javax-activation-api-plugin/master/LICENSE
javax_mail_api;https://rawhubusercontent.com/jenkinsci/javax-mail-api-plugin/master/LICENSE
javax.activation;https://rawhubusercontent.com/javaee/activation/master/LICENSE.txt
javax.annotation_api;https://rawhubusercontent.com/javaee/javax.annotation/master/LICENSE
javax.el_api;https://rawhubusercontent.com/javaee/el-spec/master/LICENSE
javax.mail;https://rawhubusercontent.com/javaee/javamail/master/LICENSE.txt
javax.servlet_api;https://rawhubusercontent.com/javaee/servlet-spec/master/LICENSE
javax.servlet.jsp_api;https://rawhubusercontent.com/javaee/javaee-jsp-api/master/LICENSE
javax.websocket_api;https://rawhubusercontent.com/jakartaee/websocket/master/LICENSE.md
javax.websocket_client_api;https://rawhubusercontent.com/jakartaee/websocket/master/LICENSE.md
jaxb;https://github.com/jenkinsci/jaxb-plugin
jaxb_api;https://github.com/javaee/jaxb-spec
jaxb_impl;https://rawhubusercontent.com/eclipse-ee4j/jaxb-ri/master/LICENSE.md
jaxb_runtime;https://rawhubusercontent.com/eclipse-ee4j/jaxb-ri/master/LICENSE.md
jaxen;https://rawhubusercontent.com/jaxen-xpath/jaxen/master/LICENSE.txt
jbcrypt;https://rawhubusercontent.com/jeremyh/jBCrypt/master/LICENSE
jboss_marshalling;http://github.com/jboss/jboss-parent-pom
jboss_marshalling_river;http://github.com/jboss/jboss-parent-pom
jcifs;http://github.com/kohsuke/jcifs
jcip_annotations;https://rawhubusercontent.com/stephenc/jcip-annotations/master/LICENSE.txt
jcl_over_slf4j;https://github.com/qos-ch/slf4j
jcommon;https://rawhubusercontent.com/jfree/jcommon/master/LICENSE
jctools_core;https://rawhubusercontent.com/JCTools/JCTools/master/LICENSE
jdk_tool;https://github.com/jenkinsci/jdk-tool-plugin
jeepney;https://gitlab.com/takluyver/jeepney/-/raw/master/LICENSE
jenkins_core;https://github.com/jenkinsci/jenkins
jenkins_stapler_support;https://github.com/jenkinsci/pom
jenkins_war;https://github.com/jenkinsci/jenkins
jetty_alpn_java_server;https://rawhubusercontent.com/jetty/jetty.project/jetty-12.0.x/LICENSE
jetty_alpn_server;https://rawhubusercontent.com/jetty/jetty.project/jetty-12.0.x/LICENSE
jetty_http;https://rawhubusercontent.com/jetty/jetty.project/jetty-12.0.x/LICENSE
jetty_io;https://rawhubusercontent.com/jetty/jetty.project/jetty-12.0.x/LICENSE
jetty_jmx;https://rawhubusercontent.com/jetty/jetty.project/jetty-12.0.x/LICENSE
jetty_security;https://rawhubusercontent.com/jetty/jetty.project/jetty-12.0.x/LICENSE
jetty_server;https://rawhubusercontent.com/jetty/jetty.project/jetty-12.0.x/LICENSE
jetty_servlet;https://rawhubusercontent.com/jetty/jetty.project/jetty-12.0.x/LICENSE
jetty_unixdomain_server;https://rawhubusercontent.com/jetty/jetty.project/jetty-12.0.x/LICENSE
jetty_util;https://rawhubusercontent.com/jetty/jetty.project/jetty-12.0.x/LICENSE
jetty_webapp;https://rawhubusercontent.com/jetty/jetty.project/jetty-12.0.x/LICENSE
jetty_xml;https://rawhubusercontent.com/jetty/jetty.project/jetty-12.0.x/LICENSE
jfreechart;https://rawhubusercontent.com/jfree/jfreechart/master/licence-LGPL.txt
jinja2;https://rawhubusercontent.com/pallets/jinja/master/LICENSE.rst
jline;http://github.com/jline/jline2
jna;https://rawhubusercontent.com/java-native-access/jna/master/LICENSE
jquery3_api;https://github.com/jenkinsci/jquery3-api-plugin
jrt_fs;https://rawhubusercontent.com/AdoptOpenJDK/openjdk-jdk11/master/LICENSE
json;https://rawhubusercontent.com/douglascrockford/JSON-java/master/LICENSE
json_lib;https://github.com/jenkinsci/json-lib
jsp_api;https://rawhubusercontent.com/jakartaee/pages/master/LICENSE.md
jsr305;https://code.google.com/p/jsr-305/
junit;https://rawhubusercontent.com/jenkinsci/junit-plugin/master/LICENSE
junit4;https://rawhubusercontent.com/junit-team/junit4/main/LICENSE-junit.txt
jzlib;https://rawhubusercontent.com/kohsuke/jzlib/master/LICENSE.txt
k8s.io_api;https://rawhubusercontent.com/kubernetes/api/master/LICENSE
k8s.io_apiextensions_apiserver;https://rawhubusercontent.com/kubernetes/apiextensions-apiserver/master/LICENSE
k8s.io_apimachinery;https://rawhubusercontent.com/kubernetes/apimachinery/master/LICENSE
k8s.io_cli_runtime;https://rawhubusercontent.com/kubernetes/cli-runtime/master/LICENSE
k8s.io_client_go;https://rawhubusercontent.com/kubernetes/client-go/master/LICENSE
k8s.io_component_base;https://rawhubusercontent.com/kubernetes/component-base/master/LICENSE
k8s.io_klog_v2;https://rawhubusercontent.com/kubernetes/klog/master/LICENSE
k8s.io_kube_openapi;https://rawhubusercontent.com/kubernetes/kube-openapi/master/LICENSE
k8s.io_kubectl;https://rawhubusercontent.com/kubernetes/kubectl/master/LICENSE
k8s.io_utils;https://rawhubusercontent.com/kubernetes/utils/master/LICENSE
keyring;https://rawhubusercontent.com/jaraco/keyring/master/LICENSE
libintl;https://rawhubusercontent.com/lattera/glibc/master/intl/libintl.h
listenablefuture;https://rawhubusercontent.com/google/guava/master/LICENSE
localizer;https://rawhubusercontent.com/kohsuke/localizer/master/pom.xml
log4j_over_slf4j;https://rawhubusercontent.com/qos-ch/slf4j/master/LICENSE.txt
logging;https://rawhubusercontent.com/apache/commons-logging/master/LICENSE.txt
mailer;https://github.com/jenkinsci/mailer-plugin
markupsafe;https://rawhubusercontent.com/pallets/markupsafe/master/LICENSE.rst
matrix_auth;https://github.com/jenkinsci/matrix-auth-plugin
matrix_project;https://github.com/jenkinsci/matrix-project-plugin
memory_monitor;https://github.com/jenkinsci/extras-memory-monitor
mina_sshd_api_common;https://rawhubusercontent.com/jenkinsci/mina-sshd-api-plugin/master/LICENSE
mina_sshd_api_core;https://rawhubusercontent.com/jenkinsci/mina-sshd-api-plugin/master/LICENSE
mock;https://rawhubusercontent.com/testing-cabal/mock/master/LICENSE.txt
modernc.org_libc;https://gitlab.com/cznic/libc
modernc.org_mathutil;https://gitlab.com/cznic/mathutil
modernc.org_memory;https://gitlab.com/cznic/memory
modernc.org_sqlite;https://gitlab.com/cznic/sqlite
more_itertools;https://rawhubusercontent.com/more-itertools/more-itertools/master/LICENSE
mypy;https://rawhubusercontent.com/python/mypy/master/LICENSE
nox;https://rawhubusercontent.com/wntrblm/nox/master/LICENSE
opentelemetry_java_contrib_jmx_metrics;https://rawhubusercontent.com/open-telemetry/opentelemetry-java-contrib/main/LICENSE
owasp_java_html_sanitizer;https://github.com/OWASP/java-html-sanitizer
packaging;https://rawhubusercontent.com/pypa/packaging/master/LICENSE
peter_evans_create_pull_request;https://rawhubusercontent.com/peter-evans/create-pull-request/main/LICENSE
pip;https://github.com/pypa/pip
platformdirs;https://rawhubusercontent.com/platformdirs/platformdirs/master/LICENSE
plugin_util_api;https://rawhubusercontent.com/jenkinsci/plugin-util-api-plugin/master/LICENSE
pre_commit_action;https://rawhubusercontent.com/pre-commit/action/main/LICENSE
protobuf;https://rawhubusercontent.com/protocolbuffers/protobuf/main/LICENSE
pyOpenSSL;https://rawhubusercontent.com/pyca/pyopenssl/master/LICENSE
pyasn1;https://rawhubusercontent.com/etingof/pyasn1/master/LICENSE.rst
pyasn1_modules;https://github.com/etingof/pyasn1-modules
pycparser;https://rawhubusercontent.com/eliben/pycparser/master/LICENSE
pycurl;https://rawhubusercontent.com/pycurl/pycurl/master/COPYING-LGPL
pygments;https://rawhubusercontent.com/pygments/pygments/master/LICENSE
pyjwt;https://rawhubusercontent.com/jpadilla/pyjwt/master/LICENSE
pyopenssl;https://rawhubusercontent.com/pyca/pyopenssl/main/LICENSE
pypa_gh_action_pypi_publish;https://rawhubusercontent.com/pypa/gh-action-pypi-publish/unstable/v1/LICENSE.md
pyparsing;https://rawhubusercontent.com/pyparsing/pyparsing/master/LICENSE
pyperclip;https://rawhubusercontent.com/asweigart/pyperclip/master/LICENSE.txt
pytest;https://rawhubusercontent.com/pytest-dev/pytest/master/LICENSE
pytest_cov;https://rawhubusercontent.com/pytest-dev/pytest-cov/master/LICENSE
pytest_forked;https://rawhubusercontent.com/pytest-dev/pytest-forked/master/LICENSE
pytest_freezegun;https://rawhubusercontent.com/ktosiek/pytest-freezegun/master/LICENSE
pytest_httpbin;https://github.com/kevin1024/pytest-httpbin
pytest_mock;https://rawhubusercontent.com/pytest-dev/pytest-mock/master/LICENSE
pytest_randomly;https://rawhubusercontent.com/pytest-dev/pytest-randomly/main/LICENSE
pytest_timeout;http://github.com/pytest-dev/pytest-timeout
pytest_xdist;https://rawhubusercontent.com/pytest-dev/pytest-xdist/master/LICENSE
python;https://rawhubusercontent.com/python/cpython/main/LICENSE
python_dateutil;https://rawhubusercontent.com/dateutil/dateutil/master/LICENSE
python_debian;https://rawhubusercontent.com/romlok/python-debian/master/setup.py.in
python_debianbts;https://rawhubusercontent.com/venthur/python-debianbts/master/LICENSE
qdox;http://svn.qdox.codehaus.org/browse/qdox/tags/qdox-1.12.1
readme_renderer;https://rawhubusercontent.com/pypa/readme_renderer/master/LICENSE
relaxngDatatype;https://rawhubusercontent.com/java-schema-utilities/relaxng-datatype-java/master/pom.xml
remoting;https://rawhubusercontent.com/jenkinsci/remoting/master/LICENSE.md
reportbug;https://rawhubusercontent.com/venthur/python-debianbts/master/LICENSE
requests;https://rawhubusercontent.com/psf/requests/master/LICENSE
requests_toolbelt;https://rawhubusercontent.com/requests/toolbelt/master/LICENSE
rfc3986;https://rawhubusercontent.com/python-hyper/rfc3986/main/LICENSE
rich;https://rawhubusercontent.com/willmcgugan/rich/master/LICENSE
robust_http_client;https://rawhubusercontent.com/kohsuke/robust-http-client/master/pom.xml
scm_api;https://github.com/jenkinsci/scm-api-plugin
script_security;https://github.com/jenkinsci/script-security-plugin
secretstorage;https://github.com/mitya57/secretstorage
servlet_api;https://rawhubusercontent.com/jakartaee/servlet/master/LICENSE.md
setuptools;https://rawhubusercontent.com/pypa/setuptools/master/LICENSE
sezpoz;https://rawhubusercontent.com/jglick/sezpoz/master/pom.xml
sigs.k8s.io_cli_utils;https://rawhubusercontent.com/kubernetes-sigs/cli-utils/master/LICENSE
sigs.k8s.io_controller_runtime;https://rawhubusercontent.com/kubernetes-sigs/controller-runtime/master/LICENSE
sigs.k8s.io_json;https://rawhubusercontent.com/kubernetes-sigs/json/master/LICENSE
sigs.k8s.io_kustomize_api;https://rawhubusercontent.com/kubernetes-sigs/kustomize/master/LICENSE
sigs.k8s.io_kustomize_kyaml;https://rawhubusercontent.com/kubernetes-sigs/kustomize/master/LICENSE
sigs.k8s.io_structured_merge_diff_v4;https://rawhubusercontent.com/kubernetes-sigs/structured-merge-diff/master/LICENSE
sigs.k8s.io_yaml;https://rawhubusercontent.com/kubernetes-sigs/yaml/master/LICENSE
simpleclient;https://github.com/prometheus/client_java
simpleclient_common;https://github.com/prometheus/client_java
simpleclient_httpserver;https://github.com/prometheus/client_java
simpleclient_tracer_common;https://github.com/prometheus/client_java
simpleclient_tracer_otel;https://github.com/prometheus/client_java
simpleclient_tracer_otel_agent;https://github.com/prometheus/client_java
simplejson;http://github.com/simplejson/simplejson
six;https://rawhubusercontent.com/benjaminp/six/master/LICENSE
slf4j_api;https://github.com/qos-ch/slf4j
slf4j_jdk14;https://github.com/qos-ch/slf4j
slf4j_simple;https://github.com/qos-ch/slf4j
snakeyaml;https://bitbucket.org/snakeyaml/snakeyaml/src
snakeyaml_api;https://github.com/jenkinsci/snakeyaml-api-plugin
spotbugs_annotations;https://rawhubusercontent.com/spotbugs/spotbugs/master/LICENSE
spring_aop;https://rawhubusercontent.com/spring-projects/spring-framework/main/LICENSE.txt
spring_beans;https://rawhubusercontent.com/spring-projects/spring-framework/main/LICENSE.txt
spring_context;https://rawhubusercontent.com/spring-projects/spring-framework/main/LICENSE.txt
spring_core;https://rawhubusercontent.com/spring-projects/spring-framework/main/LICENSE.txt
spring_expression;https://rawhubusercontent.com/spring-projects/spring-framework/main/LICENSE.txt
spring_security_core;https://rawhubusercontent.com/spring-projects/spring-framework/main/LICENSE.txt
spring_security_crypto;https://rawhubusercontent.com/spring-projects/spring-framework/main/LICENSE.txt
spring_security_web;https://rawhubusercontent.com/spring-projects/spring-framework/main/LICENSE.txt
spring_web;https://rawhubusercontent.com/spring-projects/spring-framework/main/LICENSE.txt
sshd;https://rawhubusercontent.com/jenkinsci/sshd-plugin/master/LICENSE
sshd_common;https://www.apache.org/
sshd_core;https://www.apache.org/
stapler;https://github.com/jenkinsci/stapler
stapler_adjunct_codemirror;https://github.com/stapler/stapler-adjunct-codemirror
stapler_groovy;https://github.com/jenkinsci/stapler
stapler_jelly;https://github.com/jenkinsci/stapler
stax2_api;https://rawhubusercontent.com/FasterXML/stax2-api/master/pom.xml
structs;https://github.com/jenkinsci/structs-plugin
support_log_formatter;https://github.com/jenkinsci/lib-support-log-formatter
symbol_annotation;https://github.com/jenkinsci/lib-symbol-annotation
task_reactor;https://github.com/jenkinsci/lib-task-reactor
tiger_types;https://rawhubusercontent.com/kohsuke/tiger-types/master/pom.xml
tink;https://rawhubusercontent.com/google/tink/master/LICENSE
tornado;https://rawhubusercontent.com/tornadoweb/tornado/master/LICENSE
tox;https://rawhubusercontent.com/tox-dev/tox/main/LICENSE
trilead_api;https://github.com/jenkinsci/trilead-api-plugin
trilead_putty_extension;https://rawhubusercontent.com/kohsuke/trilead-putty-extension/master/src/main/java/org/kohsuke/putty/PuTTYKey.java
trilead_ssh2;https://github.com/jenkinsci/trilead-ssh2
trilead_ssh2_build;https://github.com/jenkinsci/trilead-ssh2
trustme;https://rawhubusercontent.com/python-trio/trustme/master/LICENSE
twine;https://rawhubusercontent.com/pypa/twine/master/LICENSE
txw2;https://rawhubusercontent.com/eclipse-ee4j/jaxb-ri/master/LICENSE.md
typing_extensions;https://rawhubusercontent.com/python/typing_extensions/master/LICENSE
tyrus_client;https://github.com/eclipse-ee4j/tyrus
tyrus_container_jdk_client;https://github.com/eclipse-ee4j/tyrus
tyrus_core;https://github.com/eclipse-ee4j/tyrus
tyrus_spi;https://github.com/eclipse-ee4j/tyrus
tyrus_standalone_client_jdk;https://github.com/eclipse-ee4j/tyrus
unattended_upgrades;https://rawhubusercontent.com/mvo5/unattended-upgrades/master/COPYING
urllib3;https://github.com/urllib3/urllib3
version_number;https://github.com/jenkinsci/lib-version-number
virtualenv;https://rawhubusercontent.com/pypa/virtualenv/master/LICENSE
webencodings;https://rawhubusercontent.com/SimonSapin/python-webencodings/master/LICENSE
websocket_api;https://github.com/eclipse/jetty.project
websocket_client_api;https://github.com/eclipse/jetty.project
websocket_core_common;https://github.com/eclipse/jetty.project
websocket_core_server;https://github.com/eclipse/jetty.project
websocket_jetty_api;https://github.com/eclipse/jetty.project
websocket_jetty_common;https://github.com/eclipse/jetty.project
websocket_jetty_server;https://github.com/eclipse/jetty.project
websocket_jetty10;https://github.com/jenkinsci/jenkins
websocket_servlet;https://github.com/eclipse/jetty.project
websocket_spi;https://github.com/jenkinsci/jenkins
wheel;https://github.com/pypa/wheel
win_inet_pton;https://rawhubusercontent.com/hickeroar/win_inet_pton/master/LICENSE
windows_package_checker;http://kohsuke.org/
winp;https://github.com/jenkinsci/winp
winstone;https://github.com/jenkinsci/winstone
woodstox_core;https://rawhubusercontent.com/FasterXML/woodstox/master/LICENSE
workflow_api;https://rawhubusercontent.com/jenkinsci/workflow-api-plugin/master/LICENSE
workflow_step_api;https://github.com/jenkinsci/workflow-step-api-plugin
workflow_support;https://github.com/jenkinsci/workflow-support-plugin
wrapt;https://rawhubusercontent.com/GrahamDumpleton/wrapt/master/LICENSE
xstream;http://github.com/x-stream/xstream
zipp;https://rawhubusercontent.com/jaraco/zipp/master/LICENSE
EOF
end
