# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ospo_download 'Licenses and Source-code' do
  ref_repos <<-EOF
https://github.com/pysimplesoap/pysimplesoap
https://github.com/certifi/python-certifi
https://github.com/chardet/chardet
https://github.com/jenkinsci/constant-pool-scanner
https://docutils.sourceforge.io
https://github.com/jakartaee/expression-language
https://github.com/anchore/go-version
https://github.com/go-sql-driver/mysql
https://github.com/hashicorp/consul
https://github.com/hashicorp/errwrap
https://github.com/hashicorp/go-checkpoint
https://github.com/hashicorp/go-cleanhttp
https://github.com/hashicorp/go-immutable-radix
https://github.com/hashicorp/go-multierror
https://github.com/hashicorp/go-plugin
https://github.com/hashicorp/go-retryablehttp
https://github.com/hashicorp/go-rootcerts
https://github.com/hashicorp/go-uuid
https://github.com/hashicorp/go-version
https://github.com/hashicorp/golang-lru
https://github.com/hashicorp/hc-install
https://github.com/hashicorp/hcl
https://github.com/hashicorp/logutils
https://github.com/hashicorp/nomad
https://github.com/hashicorp/serf
https://github.com/hashicorp/terraform-exec
https://github.com/hashicorp/terraform-json
https://github.com/hashicorp/terraform-plugin-go
https://github.com/hashicorp/terraform-plugin-log
https://github.com/hashicorp/terraform-plugin-sdk
https://github.com/hashicorp/terraform-registry-address
https://github.com/hashicorp/terraform-svchost
https://github.com/hashicorp/yamux
https://github.com/eclipse/jetty.project
https://github.com/jenkinsci/jakarta-mail-api-plugin
https://github.com/eclipse-ee4j/common-annotations-api
https://github.com/eclipse-ee4j/mail
https://github.com/eclipse-ee4j/jstl-api
https://github.com/eclipse-ee4j/websocket-api
https://github.com/jenkinsci/javax-activation-api-plugin
https://github.com/jenkinsci/javax-mail-api-plugin
https://github.com/javaee/activation
https://github.com/javaee/javax.annotation
https://github.com/javaee/el-spec
https://github.com/javaee/javamail
https://github.com/javaee/servlet-spec
https://github.com/javaee/javaee-jsp-api
https://github.com/jakartaee/websocket
https://github.com/javaee/jaxb-spec.git
http://github.com/kohsuke/jcifs
https://github.com/jfree/jcommon
https://github.com/jetty/jetty.project
https://github.com/jfree/jfreechart
https://github.com/java-native-access/jna
https://github.com/AdoptOpenJDK/openjdk-jdk11
https://github.com/jakartaee/pages
https://github.com/lattera/glibc
https://github.com/pycurl/pycurl
https://github.com/romlok/python-debian
https://github.com/jakartaee/servlet
https://github.com/jglick/sezpoz
https://github.com/spotbugs/spotbugs
https://github.com/kohsuke/tiger-types
https://github.com/eclipse-ee4j/tyrus
https://github.com/mvo5/unattended-upgrades
https://github.com/jenkinsci/winstone
EOF
  licenses <<-EOF
private_repos_cnrm.googlesource.com_cnrm_;https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/main/LICENSE
private_repos_cnrm.googlesource.com_cnrm_third_party_github.com_hashicorp_terraform_provider_google_beta;https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/main/LICENSE
HdrHistogram;scm:git:https://github.com/HdrHistogram/HdrHistogram
PySimpleSOAP;https://github.com/pysimplesoap/pysimplesoap
PySocks;https://rawhubusercontent.com/Anorov/PySocks/master/LICENSE
ST4;https://github.com/antlr/stringtemplate4
SimpleLauncherExecutable;https://github.com/googleapis/google-api-python-client/blob/main/LICENSE
Sphinx;https://rawhubusercontent.com/sphinx-doc/sphinx/master/LICENSE.rst
actions_cache;https://github.com/actions/gh-actions-cache/blob/main/LICENSE
actions_checkout;https://github.com/actions/checkout/blob/main/LICENSE
actions_download_artifact;https://github.com/actions/download-artifact/blob/main/LICENSE
actions_setup_python;https://github.com/actions/setup-python/blob/main/LICENSE
actions_upload_artifact;https://github.com/actions/upload-artifact/blob/main/LICENSE
airline;http://github.com/airlift/airline/tree/master
animal_sniffer_annotations;https://rawhubusercontent.com/mojohaus/animal-sniffer/master/LICENSE
annotations;https://github.com/JetBrains/intellij-community
annotations;https://android.kernel.org/
anthoscli;https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/main/LICENSE
antlr_runtime;https://github.com/antlr/antlr3/tree/master
apache_cassandra;https://github.com/apache/cassandra/blob/trunk/LICENSE.txt
argcomplete;https://rawhubusercontent.com/kislyuk/argcomplete/master/LICENSE.rst
argparse;https://github.com/python/cpython/blob/main/LICENSE
asm;https://github.com/stephengold/asm/blob/master/LICENSE
attrs;https://rawhubusercontent.com/python-attrs/attrs/master/LICENSE
bitbucket.org_creachadair_stringset;https://bitbucket.org/creachadair/stringset
black;https://rawhubusercontent.com/psf/black/master/LICENSE
bleach;https://rawhubusercontent.com/mozilla/bleach/master/LICENSE
ca_certificates_java;https://github.com/swisscom/update-java-ca-certificates/blob/master/LICENSE
cachetools;https://rawhubusercontent.com/tkem/cachetools/master/LICENSE
caffeine;https://rawhubusercontent.com/ben-manes/caffeine/master/LICENSE
cassandra_driver_core;https://rawhubusercontent.com/datastax/java-driver/master/LICENSE
cassandra_pylib;https://github.com/apache/cassandra/blob/trunk/LICENSE.txt
certifi;https://rawhubusercontent.com/certifi/python-certifi/master/LICENSE
cffi;https://rawhubusercontent.com/python-cffi/cffi/master/LICENSE
chardet;https://rawhubusercontent.com/chardet/chardet/master/LICENSE
charset_normalizer;https://rawhubusercontent.com/ousret/charset_normalizer/master/LICENSE
checker_qual;https://github.com/typetools/checker-framework/blob/master/LICENSE.txt
chronicle_bytes;scm:git:git@github.com:OpenHFT/Chronicle-Bytes
chronicle_core;scm:git:git@github.com:OpenHFT/Chronicle-Core
chronicle_queue;scm:git:git@github.com:OpenHFT/Chronicle-Queue
chronicle_threads;scm:git:git@github.com:OpenHFT/Chronicle-Threads
chronicle_wire;scm:git:git@github.com:OpenHFT/Chronicle-Wire
click;https://rawhubusercontent.com/pallets/click/master/LICENSE.rst
cloud.google.com_go;https://rawhubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_bigtable;https://rawhubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_compute_metadata;https://rawhubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_iam;https://rawhubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_logging;https://rawhubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_longrunning;https://rawhubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_monitoring;https://rawhubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_osconfig;https://rawhubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_storage;https://rawhubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_trace;https://rawhubusercontent.com/googleapis/google-cloud-go/master/LICENSE
codecov_codecov_action;https://github.com/codecov/codecov-action/blob/main/LICENSE
colorlog;https://rawhubusercontent.com/borntyping/python-colorlog/master/LICENSE
command_line_arguments;https://rawhubusercontent.com/googleapis/google-cloud-go/master/LICENSE
commonmark;https://github.com/rtfd/commonmark.py
commons_cli;http://svn.apache.org/repos/asf/jakarta/commons/proper/cli/trunk
commons_codec;http://svn.apache.org/viewvc/commons/proper/codec/trunk
commons_lang3;https://gitbox.apache.org/repos/asf?p=commons-lang
commons_math3;http://svn.apache.org/viewvc/commons/proper/math/trunk
concurrent_trees;http://concurrent-trees.googlecode.com/svn/concurrent-trees/tags/2.4.0
contrib.go.opencensus.io_exporter_prometheus;https://rawhubusercontent.com/census-ecosystem/opencensus-go-exporter-prometheus/master/LICENSE
cos.googlesource.com_cos_tools.git;https://cos.googlesource.com/cos/tools
coverage;https://bitbucket.org/ned/coveragepy
crcmod;https://github.com/gsutil-mirrors/crcmod/blob/master/LICENSE
cryptography;https://rawhubusercontent.com/pyca/cryptography/master/LICENSE
dario.cat_mergo;https://rawhubusercontent.com/imdario/mergo/master/LICENSE
dbus_python;https://github.com/posborne/dbus-python/blob/master/COPYING
dessant_lock_threads;https://github.com/dessant/lock-threads/blob/main/LICENSE
distlib;https://github.com/pypa/distlib
distro_info;https://github.com/python-distro/distro/blob/master/LICENSE
docutils;https://github.com/docutils/docutils/blob/master/docutils/licenses/BSD-2-Clause.txt
ecj;https://github.com/GMUEClab/ecj/blob/master/ecj/LICENSE
error_prone_annotations;https://github.com/google/error-prone
failureaccess;https://rawhubusercontent.com/google/guava/master/LICENSE
filelock;https://rawhubusercontent.com/tox-dev/py-filelock/master/LICENSE
flake8;https://gitlab.com/pycqa/flake8
flake8;https://github.com/pycqa/flake8
flaky;https://rawhubusercontent.com/box/flaky/master/LICENSE
fqltool;https://github.com/apache/cassandra-dtest/blob/trunk/license.txt
future;https://github.com/GoogleCloudPlatform/python-repo-tools/blob/master/LICENSE
gcp_devrel_py_tools;https://rawhubusercontent.com/GoogleCloudPlatform/python-repo-tools/master/LICENSE
gcp_docuploader;https://github.com/googleapis/docuploader/blob/main/LICENSE
gcp_releasetool;https://github.com/googleapis/releasetool/blob/master/LICENSE
github.com_99designs_keyring;https://github.com/99designs/keyring
github.com_Azure_azure_sdk_for_go;https://github.com/azure/azure-sdk-for-go
github.com_Azure_azure_sdk_for_go_sdk_azcore;https://github.com/azure/azure-sdk-for-go
github.com_Azure_azure_sdk_for_go_sdk_azidentity;https://github.com/azure/azure-sdk-for-go
github.com_Azure_azure_sdk_for_go_sdk_internal;https://github.com/azure/azure-sdk-for-go
github.com_Azure_azure_sdk_for_go_sdk_resourcemanager_compute_armcompute_v4;https://github.com/azure/azure-sdk-for-go
github.com_Azure_azure_sdk_for_go_sdk_resourcemanager_network_armnetwork_v2;https://github.com/azure/azure-sdk-for-go
github.com_Azure_azure_sdk_for_go_sdk_storage_azblob;https://github.com/azure/azure-sdk-for-go
github.com_Azure_go_autorest_autorest;https://rawhubusercontent.com/azure/go-autorest/master/LICENSE
github.com_Azure_go_autorest_autorest_adal;https://rawhubusercontent.com/azure/go-autorest/master/LICENSE
github.com_Azure_go_autorest_autorest_date;https://rawhubusercontent.com/azure/go-autorest/master/LICENSE
github.com_Azure_go_autorest_autorest_to;https://rawhubusercontent.com/azure/go-autorest/master/LICENSE
github.com_Azure_go_autorest_autorest_validation;https://rawhubusercontent.com/azure/go-autorest/master/LICENSE
github.com_Azure_go_autorest_logger;https://rawhubusercontent.com/azure/go-autorest/master/LICENSE
github.com_Azure_go_autorest_tracing;https://rawhubusercontent.com/azure/go-autorest/master/LICENSE
github.com_AzureAD_microsoft_authentication_library_for_go;https://rawhubusercontent.com/azuread/microsoft-authentication-library-for-go/master/LICENSE
github.com_CycloneDX_cyclonedx_go;https://rawhubusercontent.com/cyclonedx/cyclonedx-go/master/LICENSE
github.com_GoogleCloudPlatform_declarative_resource_client_library;https://rawhubusercontent.com/googlecloudplatform/declarative-resource-client-library/master/LICENSE
github.com_GoogleCloudPlatform_guest_agent;https://github.com/GoogleCloudPlatform/guest-agent/blob/main/LICENSE
github.com_GoogleCloudPlatform_guest_logging_go;https://rawhubusercontent.com/googlecloudplatform/guest-logging-go/master/LICENSE
github.com_GoogleCloudPlatform_opentelemetry_operations_collector;https://github.com/GoogleCloudPlatform/opentelemetry-operations-collector/blob/master/LICENSE
github.com_GoogleCloudPlatform_opentelemetry_operations_go_detectors_gcp;https://rawhubusercontent.com/googlecloudplatform/opentelemetry-operations-go/master/LICENSE
github.com_GoogleCloudPlatform_opentelemetry_operations_go_exporter_collector;https://rawhubusercontent.com/googlecloudplatform/opentelemetry-operations-go/master/LICENSE
github.com_GoogleCloudPlatform_opentelemetry_operations_go_exporter_collector_googlemanagedprometheus;https://rawhubusercontent.com/googlecloudplatform/opentelemetry-operations-go/master/LICENSE
github.com_GoogleCloudPlatform_opentelemetry_operations_go_exporter_metric;https://rawhubusercontent.com/googlecloudplatform/opentelemetry-operations-go/master/LICENSE
github.com_GoogleCloudPlatform_opentelemetry_operations_go_exporter_trace;https://rawhubusercontent.com/googlecloudplatform/opentelemetry-operations-go/master/LICENSE
github.com_GoogleCloudPlatform_opentelemetry_operations_go_internal_resourcemapping;https://rawhubusercontent.com/googlecloudplatform/opentelemetry-operations-go/master/LICENSE
github.com_GoogleCloudPlatform_ops_agent;https://github.com/GoogleCloudPlatform/ops-agent/blob/master/LICENSE
github.com_GoogleCloudPlatform_osconfig;https://github.com/GoogleCloudPlatform/osconfig/blob/master/LICENSE
github.com_GoogleContainerTools_kpt;https://github.com/kptdev/kpt/blob/main/LICENSE
github.com_GoogleContainerTools_kpt_porch_api;https://rawhubusercontent.com/googlecontainertools/kpt/master/LICENSE
github.com_JohnCGriffin_overflow;https://github.com/johncgriffin/overflow
github.com_MakeNowJust_heredoc;https://rawhubusercontent.com/makenowjust/heredoc/master/LICENSE
github.com_Masterminds_goutils;https://github.com/masterminds/goutils
github.com_Masterminds_semver;https://github.com/masterminds/semver
github.com_Masterminds_semver_v3;https://github.com/masterminds/semver
github.com_Masterminds_sprig_v3;https://github.com/masterminds/sprig
github.com_NVIDIA_go_dcgm;https://rawhubusercontent.com/nvidia/go-dcgm/master/LICENSE
github.com_NVIDIA_go_nvml;https://github.com/NVIDIA/go-nvml/blob/main/LICENSE
github.com_ProtonMail_go_crypto;https://rawhubusercontent.com/protonmail/go-crypto/master/LICENSE
github.com_SAP_go_hdb;https://rawhubusercontent.com/sap/go-hdb/master/LICENSE.md
github.com_Showmax_go_fqdn;https://rawhubusercontent.com/showmax/go-fqdn/master/LICENSE
github.com_acarl005_stripansi;https://github.com/acarl005/stripansi
github.com_acobaugh_osrelease;https://rawhubusercontent.com/acobaugh/osrelease/master/LICENSE
github.com_adrg_xdg;https://rawhubusercontent.com/adrg/xdg/master/LICENSE
github.com_aerospike_aerospike_client_go_v6;https://rawhubusercontent.com/aerospike/aerospike-client-go/master/LICENSE
github.com_agext_levenshtein;https://rawhubusercontent.com/agext/levenshtein/master/LICENSE
github.com_alecthomas_participle_v2;https://github.com/alecthomas/participle
github.com_alecthomas_units;https://github.com/alecthomas/units
github.com_anchore_bubbly;https://rawhubusercontent.com/anchore/bubbly/master/LICENSE
github.com_anchore_clio;https://rawhubusercontent.com/anchore/clio/master/LICENSE
github.com_anchore_fangs;https://rawhubusercontent.com/anchore/fangs/master/LICENSE
github.com_anchore_go_logger;https://rawhubusercontent.com/anchore/go-logger/master/LICENSE
github.com_anchore_go_macholibre;https://rawhubusercontent.com/anchore/go-macholibre/master/LICENSE
github.com_anchore_go_struct_converter;https://rawhubusercontent.com/anchore/go-struct-converter/master/LICENSE
github.com_anchore_go_version;https://rawhubusercontent.com/anchore/go-version/master/LICENSE
github.com_anchore_packageurl_go;https://rawhubusercontent.com/anchore/packageurl-go/master/LICENSE
github.com_anchore_stereoscope;https://rawhubusercontent.com/anchore/stereoscope/master/LICENSE
github.com_anchore_syft;https://rawhubusercontent.com/anchore/syft/master/LICENSE
github.com_andybalholm_brotli;https://rawhubusercontent.com/andybalholm/brotli/master/LICENSE
github.com_apache_arrow_go_v12;https://github.com/apache/arrow
github.com_apache_thrift;https://rawhubusercontent.com/apache/thrift/master/LICENSE
github.com_apparentlymart_go_cidr;https://rawhubusercontent.com/apparentlymart/go-cidr/master/LICENSE
github.com_apparentlymart_go_textseg_v13;https://rawhubusercontent.com/apparentlymart/go-textseg/master/LICENSE
github.com_aquasecurity_go_pep440_version;https://github.com/aquasecurity/go-pep440-version
github.com_aquasecurity_go_version;https://rawhubusercontent.com/aquasecurity/go-version/master/LICENSE
github.com_armon_go_metrics;https://rawhubusercontent.com/armon/go-metrics/master/LICENSE
github.com_asaskevich_govalidator;https://github.com/asaskevich/govalidator/blob/master/LICENSE
github.com_aws_aws_sdk_go;https://github.com/aws/aws-sdk-go
github.com_aws_aws_sdk_go_v2;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_aws_protocol_eventstream;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_credentials;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_feature_s3_manager;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_internal_configsources;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_internal_endpoints_v2;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_internal_v4a;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_service_internal_accept_encoding;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_service_internal_checksum;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_service_internal_presigned_url;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_service_internal_s3shared;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_service_s3;https://github.com/aws/aws-sdk-go-v2
github.com_aws_smithy_go;https://rawhubusercontent.com/aws/smithy-go/master/LICENSE
github.com_aymanbagabas_go_osc52_v2;https://github.com/aymanbagabas/go-osc52
github.com_becheran_wildmatch_go;https://rawhubusercontent.com/becheran/wildmatch-go/master/LICENSE
github.com_beorn7_perks;https://github.com/beorn7/perks
github.com_bits_and_blooms_bitset;https://rawhubusercontent.com/bits-and-blooms/bitset/master/LICENSE
github.com_bmatcuk_doublestar_v4;https://rawhubusercontent.com/bmatcuk/doublestar/master/LICENSE
github.com_cenkalti_backoff;https://rawhubusercontent.com/cenkalti/backoff/master/LICENSE
github.com_cenkalti_backoff_v4;https://rawhubusercontent.com/cenkalti/backoff/master/LICENSE
github.com_cespare_xxhash_v2;https://github.com/cespare/xxhash
github.com_chai2010_gettext_go;https://github.com/chai2010/gettext-go
github.com_charmbracelet_bubbles;https://rawhubusercontent.com/charmbracelet/bubbles/master/LICENSE
github.com_charmbracelet_bubbletea;https://rawhubusercontent.com/charmbracelet/bubbletea/master/LICENSE
github.com_charmbracelet_harmonica;https://rawhubusercontent.com/charmbracelet/harmonica/master/LICENSE
github.com_charmbracelet_lipgloss;https://rawhubusercontent.com/charmbracelet/lipgloss/master/LICENSE
github.com_cloudflare_circl;https://rawhubusercontent.com/cloudflare/circl/master/LICENSE
github.com_cncf_xds_go;https://rawhubusercontent.com/cncf/xds/master/LICENSE
github.com_containerd_console;https://rawhubusercontent.com/containerd/console/master/LICENSE
github.com_containerd_containerd;https://rawhubusercontent.com/containerd/containerd/master/LICENSE
github.com_containerd_continuity;https://rawhubusercontent.com/containerd/continuity/master/LICENSE
github.com_containerd_fifo;https://rawhubusercontent.com/containerd/fifo/master/LICENSE
github.com_containerd_log;https://rawhubusercontent.com/containerd/log/master/LICENSE
github.com_containerd_stargz_snapshotter_estargz;https://rawhubusercontent.com/containerd/stargz-snapshotter/master/LICENSE
github.com_containerd_ttrpc;https://rawhubusercontent.com/containerd/ttrpc/master/LICENSE
github.com_containerd_typeurl_v2;https://rawhubusercontent.com/containerd/typeurl/master/LICENSE
github.com_cyphar_filepath_securejoin;https://rawhubusercontent.com/cyphar/filepath-securejoin/master/LICENSE
github.com_davecgh_go_spew;https://rawhubusercontent.com/davecgh/go-spew/master/LICENSE
github.com_deitch_magic;https://github.com/deitch/magic/blob/main/LICENSE
github.com_denisenkom_go_mssqldb;https://github.com/denisenkom/go-mssqldb
github.com_dennwc_varint;https://rawhubusercontent.com/dennwc/varint/master/LICENSE
github.com_dgryski_go_rendezvous;https://rawhubusercontent.com/dgryski/go-rendezvous/master/LICENSE
github.com_digitalocean_godo;https://github.com/digitalocean/godo
github.com_distribution_reference;https://github.com/distribution/reference/blob/main/LICENSE
github.com_docker_cli;https://github.com/docker/cli/blob/master/LICENSE
github.com_docker_distribution;https://rawhubusercontent.com/docker/distribution/master/LICENSE
github.com_docker_docker;https://rawhubusercontent.com/docker/docker/master/LICENSE
github.com_docker_docker_credential_helpers;https://rawhubusercontent.com/docker/docker-credential-helpers/master/LICENSE
github.com_docker_go_connections;https://rawhubusercontent.com/docker/go-connections/master/LICENSE
github.com_docker_go_events;https://rawhubusercontent.com/docker/go-events/master/LICENSE
github.com_docker_go_units;https://rawhubusercontent.com/docker/go-units/master/LICENSE
github.com_dsnet_compress;https://rawhubusercontent.com/dsnet/compress/master/LICENSE.md
github.com_dustin_go_humanize;https://rawhubusercontent.com/dustin/go-humanize/master/LICENSE
github.com_dvsekhvalnov_jose2go;https://github.com/dvsekhvalnov/jose2go
github.com_edsrzf_mmap_go;https://rawhubusercontent.com/edsrzf/mmap-go/master/LICENSE
github.com_emicklei_go_restful;https://rawhubusercontent.com/emicklei/go-restful/master/LICENSE
github.com_emicklei_go_restful_v3;https://rawhubusercontent.com/emicklei/go-restful/master/LICENSE
github.com_emirpasic_gods;https://rawhubusercontent.com/emirpasic/gods/master/LICENSE
github.com_envoyproxy_go_control_plane;https://rawhubusercontent.com/envoyproxy/go-control-plane/master/LICENSE
github.com_envoyproxy_protoc_gen_validate;https://rawhubusercontent.com/envoyproxy/protoc-gen-validate/master/LICENSE
github.com_evanphx_json_patch;https://rawhubusercontent.com/evanphx/json-patch/master/LICENSE
github.com_exponent_io_jsonpath;https://rawhubusercontent.com/exponent-io/jsonpath/master/LICENSE
github.com_expr_lang_expr;https://rawhubusercontent.com/expr-lang/expr/master/LICENSE
github.com_facebookincubator_nvdtools;https://rawhubusercontent.com/facebookincubator/nvdtools/master/LICENSE
github.com_fatih_color;https://rawhubusercontent.com/fatih/color/master/LICENSE.md
github.com_felixge_fgprof;https://github.com/felixge/fgprof
github.com_felixge_httpsnoop;https://github.com/felixge/httpsnoop
github.com_form3tech_oss_jwt_go;https://github.com/form3tech-oss/jwt-go
github.com_fsnotify_fsnotify;https://rawhubusercontent.com/fsnotify/fsnotify/master/LICENSE
github.com_gabriel_vasile_mimetype;https://rawhubusercontent.com/gabriel-vasile/mimetype/master/LICENSE
github.com_gammazero_deque;https://rawhubusercontent.com/gammazero/deque/master/LICENSE
github.com_gammazero_workerpool;https://rawhubusercontent.com/gammazero/workerpool/master/LICENSE
github.com_ghodss_yaml;https://rawhubusercontent.com/ghodss/yaml/master/LICENSE
github.com_github_go_spdx_v2;https://rawhubusercontent.com/github/go-spdx/master/LICENSE
github.com_go_errors_errors;https://github.com/go-errors/errors
github.com_go_git_gcfg;https://rawhubusercontent.com/go-git/gcfg/master/LICENSE
github.com_go_git_go_billy_v5;https://rawhubusercontent.com/go-git/go-billy/master/LICENSE
github.com_go_git_go_git_v5;https://rawhubusercontent.com/go-git/go-git/master/LICENSE
github.com_go_ini_ini;https://rawhubusercontent.com/go-ini/ini/master/LICENSE
github.com_go_kit_log;https://rawhubusercontent.com/go-kit/log/master/LICENSE
github.com_go_logfmt_logfmt;https://rawhubusercontent.com/go-logfmt/logfmt/master/LICENSE
github.com_go_logr_logr;https://rawhubusercontent.com/go-logr/logr/master/LICENSE
github.com_go_logr_stdr;https://rawhubusercontent.com/go-logr/stdr/master/LICENSE
github.com_go_openapi_jsonpointer;https://rawhubusercontent.com/go-openapi/jsonpointer/master/LICENSE
github.com_go_openapi_jsonreference;https://rawhubusercontent.com/go-openapi/jsonreference/master/LICENSE
github.com_go_openapi_swag;https://rawhubusercontent.com/go-openapi/swag/master/LICENSE
github.com_go_playground_locales;https://rawhubusercontent.com/go-playground/locales/master/LICENSE
github.com_go_playground_universal_translator;https://rawhubusercontent.com/go-playground/universal-translator/master/LICENSE
github.com_go_playground_validator_v10;https://rawhubusercontent.com/go-playground/validator/master/LICENSE
github.com_go_restruct_restruct;https://github.com/go-restruct/restruct/blob/master/LICENSE.md
github.com_go_resty_resty_v2;https://rawhubusercontent.com/go-resty/resty/master/LICENSE
github.com_go_sql_driver_mysql;https://rawhubusercontent.com/go-sql-driver/mysql/master/LICENSE
github.com_go_zookeeper_zk;https://rawhubusercontent.com/go-zookeeper/zk/master/LICENSE
github.com_gobwas_glob;https://rawhubusercontent.com/gobwas/glob/master/LICENSE
github.com_goccy_go_json;https://rawhubusercontent.com/goccy/go-json/master/LICENSE
github.com_goccy_go_yaml;https://rawhubusercontent.com/goccy/go-yaml/master/LICENSE
github.com_godbus_dbus;https://github.com/godbus/dbus/blob/master/LICENSE
github.com_gogo_protobuf;https://rawhubusercontent.com/gogo/protobuf/master/LICENSE
github.com_golang_jwt_jwt_v4;https://rawhubusercontent.com/golang-jwt/jwt/master/LICENSE
github.com_golang_jwt_jwt_v5;https://rawhubusercontent.com/golang-jwt/jwt/master/LICENSE
github.com_golang_sql_civil;https://rawhubusercontent.com/golang-sql/civil/master/LICENSE
github.com_golang_sql_sqlexp;https://rawhubusercontent.com/golang-sql/sqlexp/master/LICENSE
github.com_golang_glog;https://rawhubusercontent.com/golang/glog/master/LICENSE
github.com_golang_groupcache;https://rawhubusercontent.com/golang/groupcache/master/LICENSE
github.com_golang_mock;https://rawhubusercontent.com/golang/mock/master/LICENSE
github.com_golang_protobuf;https://rawhubusercontent.com/golang/protobuf/master/LICENSE
github.com_golang_snappy;https://rawhubusercontent.com/golang/snappy/master/LICENSE
github.com_google_btree;https://rawhubusercontent.com/google/btree/master/LICENSE
github.com_google_flatbuffers;https://rawhubusercontent.com/google/flatbuffers/master/LICENSE
github.com_google_gnostic;https://rawhubusercontent.com/google/gnostic/master/LICENSE
github.com_google_gnostic_models;https://rawhubusercontent.com/google/gnostic-models/master/LICENSE
github.com_google_go_cmp;https://rawhubusercontent.com/google/go-cmp/master/LICENSE
github.com_google_go_containerregistry;https://rawhubusercontent.com/google/go-containerregistry/master/LICENSE
github.com_google_go_cpy;https://rawhubusercontent.com/google/go-cpy/master/LICENSE
github.com_google_go_querystring;https://rawhubusercontent.com/google/go-querystring/master/LICENSE
github.com_google_go_sev_guest;https://rawhubusercontent.com/google/go-sev-guest/master/LICENSE
github.com_google_go_tpm;https://rawhubusercontent.com/google/go-tpm/master/LICENSE
github.com_google_go_tpm_tools;https://rawhubusercontent.com/google/go-tpm-tools/master/LICENSE
github.com_google_gofuzz;https://rawhubusercontent.com/google/gofuzz/master/LICENSE
github.com_google_licensecheck;https://rawhubusercontent.com/google/licensecheck/master/LICENSE
github.com_google_logger;https://rawhubusercontent.com/google/logger/master/LICENSE
github.com_google_pprof;https://rawhubusercontent.com/google/pprof/master/LICENSE
github.com_google_s2a_go;https://github.com/google/s2a-go
github.com_google_shlex;https://github.com/google/shlex
github.com_google_tink_go;https://rawhubusercontent.com/google/tink/master/LICENSE
github.com_google_uuid;https://rawhubusercontent.com/google/uuid/master/LICENSE
github.com_googleapis_enterprise_certificate_proxy;https://rawhubusercontent.com/googleapis/enterprise-certificate-proxy/master/LICENSE
github.com_googleapis_gax_go_v2;https://rawhubusercontent.com/googleapis/gax-go/master/LICENSE
github.com_gookit_color;https://rawhubusercontent.com/gookit/color/master/LICENSE
github.com_gophercloud_gophercloud;https://rawhubusercontent.com/gophercloud/gophercloud/master/LICENSE
github.com_gorilla_websocket;https://rawhubusercontent.com/gorilla/websocket/master/LICENSE
github.com_grafana_regexp;https://rawhubusercontent.com/grafana/regexp/master/LICENSE
github.com_gregjones_httpcache;https://github.com/gregjones/httpcache
github.com_grobie_gomemcache;https://rawhubusercontent.com/grobie/gomemcache/master/LICENSE
github.com_grpc_ecosystem_go_grpc_middleware;https://rawhubusercontent.com/grpc-ecosystem/go-grpc-middleware/master/LICENSE
github.com_grpc_ecosystem_grpc_gateway_v2;https://rawhubusercontent.com/grpc-ecosystem/grpc-gateway/master/LICENSE
github.com_gsterjov_go_libsecret;https://rawhubusercontent.com/gsterjov/go-libsecret/master/LICENSE
github.com_hashicorp_consul_api;https://rawhubusercontent.com/hashicorp/consul/master/LICENSE
github.com_hashicorp_cronexpr;https://rawhubusercontent.com/hashicorp/cronexpr/master/LICENSE
github.com_hashicorp_errwrap;https://rawhubusercontent.com/hashicorp/errwrap/master/LICENSE
github.com_hashicorp_go_checkpoint;https://rawhubusercontent.com/hashicorp/go-checkpoint/master/LICENSE
github.com_hashicorp_go_cleanhttp;https://rawhubusercontent.com/hashicorp/go-cleanhttp/master/LICENSE
github.com_hashicorp_go_cty;https://rawhubusercontent.com/hashicorp/go-cty/master/LICENSE
github.com_hashicorp_go_hclog;https://rawhubusercontent.com/hashicorp/go-hclog/master/LICENSE
github.com_hashicorp_go_immutable_radix;https://rawhubusercontent.com/hashicorp/go-immutable-radix/master/LICENSE
github.com_hashicorp_go_multierror;https://rawhubusercontent.com/hashicorp/go-multierror/master/LICENSE
github.com_hashicorp_go_plugin;https://rawhubusercontent.com/hashicorp/go-plugin/master/LICENSE
github.com_hashicorp_go_retryablehttp;https://rawhubusercontent.com/hashicorp/go-retryablehttp/master/LICENSE
github.com_hashicorp_go_rootcerts;https://rawhubusercontent.com/hashicorp/go-rootcerts/master/LICENSE
github.com_hashicorp_go_uuid;https://rawhubusercontent.com/hashicorp/go-uuid/master/LICENSE
github.com_hashicorp_go_version;https://rawhubusercontent.com/hashicorp/go-version/master/LICENSE
github.com_hashicorp_golang_lru;https://rawhubusercontent.com/hashicorp/golang-lru/master/LICENSE
github.com_hashicorp_hc_install;https://rawhubusercontent.com/hashicorp/hc-install/master/LICENSE
github.com_hashicorp_hcl;https://rawhubusercontent.com/hashicorp/hcl/master/LICENSE
github.com_hashicorp_hcl_v2;https://rawhubusercontent.com/hashicorp/hcl/master/LICENSE
github.com_hashicorp_logutils;https://rawhubusercontent.com/hashicorp/logutils/master/LICENSE
github.com_hashicorp_nomad_api;https://rawhubusercontent.com/hashicorp/nomad/master/LICENSE
github.com_hashicorp_serf;https://rawhubusercontent.com/hashicorp/serf/master/LICENSE
github.com_hashicorp_terraform_exec;https://rawhubusercontent.com/hashicorp/terraform-exec/master/LICENSE
github.com_hashicorp_terraform_json;https://rawhubusercontent.com/hashicorp/terraform-json/master/LICENSE
github.com_hashicorp_terraform_plugin_go;https://rawhubusercontent.com/hashicorp/terraform-plugin-go/master/LICENSE
github.com_hashicorp_terraform_plugin_log;https://rawhubusercontent.com/hashicorp/terraform-plugin-log/master/LICENSE
github.com_hashicorp_terraform_plugin_sdk_v2;https://rawhubusercontent.com/hashicorp/terraform-plugin-sdk/master/LICENSE
github.com_hashicorp_terraform_registry_address;https://rawhubusercontent.com/hashicorp/terraform-registry-address/master/LICENSE
github.com_hashicorp_terraform_svchost;https://rawhubusercontent.com/hashicorp/terraform-svchost/master/LICENSE
github.com_hashicorp_yamux;https://rawhubusercontent.com/hashicorp/yamux/master/LICENSE
github.com_hetznercloud_hcloud_go;https://rawhubusercontent.com/hetznercloud/hcloud-go/master/LICENSE
github.com_hetznercloud_hcloud_go_v2;https://rawhubusercontent.com/hetznercloud/hcloud-go/master/LICENSE
github.com_huandu_xstrings;https://rawhubusercontent.com/huandu/xstrings/master/LICENSE
github.com_iancoleman_strcase;https://rawhubusercontent.com/iancoleman/strcase/master/LICENSE
github.com_imdario_mergo;https://rawhubusercontent.com/imdario/mergo/master/LICENSE
github.com_influxdata_go_syslog_v3;https://rawhubusercontent.com/influxdata/go-syslog/master/LICENSE
github.com_ionos_cloud_sdk_go_v6;https://rawhubusercontent.com/ionos-cloud/sdk-go/master/LICENSE
github.com_jbenet_go_context;https://rawhubusercontent.com/jbenet/go-context/master/LICENSE
github.com_jinzhu_copier;https://github.com/jinzhu/copier
github.com_jmespath_go_jmespath;https://rawhubusercontent.com/jmespath/go-jmespath/master/LICENSE
github.com_josharian_intern;https://rawhubusercontent.com/josharian/intern/master/LICENSE.md
github.com_jpillora_backoff;https://rawhubusercontent.com/jpillora/backoff/master/LICENSE
github.com_json_iterator_go;https://rawhubusercontent.com/json-iterator/go/master/LICENSE
github.com_julienschmidt_httprouter;https://rawhubusercontent.com/julienschmidt/httprouter/master/LICENSE
github.com_kardianos_osext;https://rawhubusercontent.com/kardianos/osext/master/LICENSE
github.com_kardianos_service;https://rawhubusercontent.com/kardianos/service/master/LICENSE
github.com_kastenhq_goversion;https://github.com/kastenhq/goversion/blob/master/LICENSE
github.com_kevinburke_ssh_config;https://rawhubusercontent.com/kevinburke/ssh_config/master/LICENSE
github.com_klauspost_compress;https://rawhubusercontent.com/klauspost/compress/master/LICENSE
github.com_klauspost_cpuid_v2;https://rawhubusercontent.com/klauspost/cpuid/master/LICENSE
github.com_klauspost_pgzip;https://rawhubusercontent.com/klauspost/pgzip/master/LICENSE
github.com_knadh_koanf;https://rawhubusercontent.com/knadh/koanf/master/LICENSE
github.com_knadh_koanf_v2;https://rawhubusercontent.com/knadh/koanf/master/LICENSE
github.com_knqyf263_go_rpmdb;https://github.com/knqyf263/go-rpmdb
github.com_kolo_xmlrpc;https://rawhubusercontent.com/kolo/xmlrpc/master/LICENSE
github.com_kylelemons_godebug;https://rawhubusercontent.com/kylelemons/godebug/master/LICENSE
github.com_leodido_go_urn;https://rawhubusercontent.com/leodido/go-urn/master/LICENSE
github.com_leodido_ragel_machinery;https://rawhubusercontent.com/leodido/ragel-machinery/master/LICENSE
github.com_lib_pq;https://rawhubusercontent.com/lib/pq/master/LICENSE.md
github.com_liggitt_tabwriter;https://rawhubusercontent.com/liggitt/tabwriter/master/LICENSE
github.com_linode_linodego;https://rawhubusercontent.com/linode/linodego/master/LICENSE
github.com_lucasb_eyer_go_colorful;https://rawhubusercontent.com/lucasb-eyer/go-colorful/master/LICENSE
github.com_magiconair_properties;https://rawhubusercontent.com/magiconair/properties/master/LICENSE.md
github.com_mailru_easyjson;https://rawhubusercontent.com/mailru/easyjson/master/LICENSE
github.com_mattn_go_colorable;https://rawhubusercontent.com/mattn/go-colorable/master/LICENSE
github.com_mattn_go_isatty;https://rawhubusercontent.com/mattn/go-isatty/master/LICENSE
github.com_mattn_go_localereader;https://rawhubusercontent.com/mattn/go-localereader/master/LICENSE
github.com_mattn_go_runewidth;https://rawhubusercontent.com/mattn/go-runewidth/master/LICENSE
github.com_matttproud_golang_protobuf_extensions;https://rawhubusercontent.com/matttproud/golang_protobuf_extensions/master/LICENSE
github.com_matttproud_golang_protobuf_extensions_v2;https://rawhubusercontent.com/matttproud/golang_protobuf_extensions/master/LICENSE
github.com_mgutz_ansi;https://rawhubusercontent.com/mgutz/ansi/master/LICENSE
github.com_mholt_archiver_v3;https://rawhubusercontent.com/mholt/archiver/master/LICENSE
github.com_microsoft_go_rustaudit;https://rawhubusercontent.com/microsoft/go-rustaudit/master/LICENSE
github.com_miekg_dns;https://rawhubusercontent.com/miekg/dns/master/LICENSE
github.com_mitchellh_copystructure;https://rawhubusercontent.com/mitchellh/copystructure/master/LICENSE
github.com_mitchellh_go_homedir;https://rawhubusercontent.com/mitchellh/go-homedir/master/LICENSE
github.com_mitchellh_go_testing_interface;https://rawhubusercontent.com/mitchellh/go-testing-interface/master/LICENSE
github.com_mitchellh_go_wordwrap;https://rawhubusercontent.com/mitchellh/go-wordwrap/master/LICENSE.md
github.com_mitchellh_hashstructure;https://rawhubusercontent.com/mitchellh/hashstructure/master/LICENSE
github.com_mitchellh_hashstructure_v2;https://rawhubusercontent.com/mitchellh/hashstructure/master/LICENSE
github.com_mitchellh_mapstructure;https://rawhubusercontent.com/mitchellh/mapstructure/master/LICENSE
github.com_mitchellh_reflectwalk;https://rawhubusercontent.com/mitchellh/reflectwalk/master/LICENSE
github.com_moby_locker;https://rawhubusercontent.com/moby/locker/master/LICENSE
github.com_moby_spdystream;https://rawhubusercontent.com/moby/spdystream/master/LICENSE
github.com_moby_sys_mountinfo;https://rawhubusercontent.com/moby/sys/master/LICENSE
github.com_moby_sys_signal;https://rawhubusercontent.com/moby/sys/master/LICENSE
github.com_moby_term;https://rawhubusercontent.com/moby/term/master/LICENSE
github.com_modern_go_concurrent;https://rawhubusercontent.com/modern-go/concurrent/master/LICENSE
github.com_modern_go_reflect2;https://github.com/modern-go/reflect2
github.com_monochromegane_go_gitignore;https://rawhubusercontent.com/monochromegane/go-gitignore/master/LICENSE
github.com_montanaflynn_stats;https://rawhubusercontent.com/montanaflynn/stats/master/LICENSE
github.com_mostynb_go_grpc_compression;https://rawhubusercontent.com/mostynb/go-grpc-compression/master/LICENSE
github.com_mtibben_percent;https://rawhubusercontent.com/mtibben/percent/master/LICENSE
github.com_muesli_ansi;https://rawhubusercontent.com/muesli/ansi/master/LICENSE
github.com_muesli_cancelreader;https://rawhubusercontent.com/muesli/cancelreader/master/LICENSE
github.com_muesli_reflow;https://rawhubusercontent.com/muesli/reflow/master/LICENSE
github.com_muesli_termenv;https://rawhubusercontent.com/muesli/termenv/master/LICENSE
github.com_munnerz_goautoneg;https://rawhubusercontent.com/munnerz/goautoneg/master/LICENSE
github.com_mwitkow_go_conntrack;https://rawhubusercontent.com/mwitkow/go-conntrack/master/LICENSE
github.com_nasa9084_go_openapi;https://github.com/nasa9084/go-openapi
github.com_nginxinc_nginx_prometheus_exporter;https://rawhubusercontent.com/nginxinc/nginx-prometheus-exporter/master/LICENSE
github.com_nwaples_rardecode;https://rawhubusercontent.com/nwaples/rardecode/master/LICENSE
github.com_oklog_run;https://rawhubusercontent.com/oklog/run/master/LICENSE
github.com_olekukonko_tablewriter;https://rawhubusercontent.com/olekukonko/tablewriter/master/LICENSE.md
github.com_open_telemetry_opentelemetry_collector_contrib_exporter_fileexporter;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_exporter_googlecloudexporter;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_internal_aws_ecsutil;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_internal_common;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_internal_coreinternal;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_internal_filter;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_internal_k8sconfig;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_internal_metadataproviders;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_internal_sharedcomponent;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_pkg_ottl;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_pkg_pdatautil;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_pkg_stanza;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_pkg_translator_prometheus;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_processor_filterprocessor;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_processor_groupbyattrsprocessor;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_processor_metricstransformprocessor;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_processor_resourcedetectionprocessor;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_processor_resourceprocessor;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_processor_transformprocessor;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_activedirectorydsreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_aerospikereceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_apachereceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_couchdbreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_elasticsearchreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_filelogreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_flinkmetricsreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_hostmetricsreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_iisreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_jmxreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_memcachedreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_mysqlreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_nginxreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_postgresqlreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_rabbitmqreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_redisreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_saphanareceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_sqlqueryreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_sqlserverreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_windowsperfcountersreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_zookeeperreceiver;https://rawhubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_opencontainers_go_digest;https://rawhubusercontent.com/opencontainers/go-digest/master/LICENSE
github.com_opencontainers_image_spec;https://rawhubusercontent.com/opencontainers/image-spec/master/LICENSE
github.com_opencontainers_image_spec;https://github.com/opencontainers/image-spec/blob/main/LICENSE
github.com_opencontainers_runc;https://rawhubusercontent.com/opencontainers/runc/master/LICENSE
github.com_opencontainers_runtime_spec;https://github.com/opencontainers/runtime-spec/blob/main/LICENSE
github.com_opencontainers_selinux;https://rawhubusercontent.com/opencontainers/selinux/master/LICENSE
github.com_openshift_api;https://github.com/openshift/api/blob/master/LICENSE
github.com_openshift_client_go;https://rawhubusercontent.com/openshift/client-go/master/LICENSE
github.com_otiai10_copy;https://github.com/otiai10/copy
github.com_ovh_go_ovh;https://rawhubusercontent.com/ovh/go-ovh/master/LICENSE
github.com_pborman_indent;https://rawhubusercontent.com/pborman/indent/master/LICENSE
github.com_pborman_uuid;https://rawhubusercontent.com/pborman/uuid/master/LICENSE
github.com_pelletier_go_toml;https://rawhubusercontent.com/pelletier/go-toml/master/LICENSE
github.com_pelletier_go_toml_v2;https://rawhubusercontent.com/pelletier/go-toml/master/LICENSE
github.com_peterbourgon_diskv;https://rawhubusercontent.com/peterbourgon/diskv/master/LICENSE
github.com_pierrec_lz4_v4;https://github.com/pierrec/lz4
github.com_pjbgf_sha1cd;https://github.com/pjbgf/sha1cd
github.com_pkg_browser;https://rawhubusercontent.com/pkg/browser/master/LICENSE
github.com_pkg_errors;https://rawhubusercontent.com/pkg/errors/master/LICENSE
github.com_pkg_profile;https://rawhubusercontent.com/pkg/profile/master/LICENSE
github.com_pmezard_go_difflib;https://rawhubusercontent.com/pmezard/go-difflib/master/LICENSE
github.com_prometheus_client_golang;https://rawhubusercontent.com/prometheus/client_golang/master/LICENSE
github.com_prometheus_client_model;https://rawhubusercontent.com/prometheus/client_model/master/LICENSE
github.com_prometheus_common;https://rawhubusercontent.com/prometheus/common/master/LICENSE
github.com_prometheus_common_sigv4;https://rawhubusercontent.com/prometheus/common/master/LICENSE
github.com_prometheus_procfs;https://rawhubusercontent.com/prometheus/procfs/master/LICENSE
github.com_prometheus_prometheus;https://rawhubusercontent.com/prometheus/prometheus/master/LICENSE
github.com_prometheus_statsd_exporter;https://rawhubusercontent.com/prometheus/statsd_exporter/master/LICENSE
github.com_redis_go_redis_v9;https://rawhubusercontent.com/redis/go-redis/master/LICENSE
github.com_remyoudompheng_bigfft;https://rawhubusercontent.com/remyoudompheng/bigfft/master/LICENSE
github.com_rivo_uniseg;https://github.com/rivo/uniseg
github.com_robfig_cron_v3;https://rawhubusercontent.com/robfig/cron/master/LICENSE
github.com_rs_cors;https://rawhubusercontent.com/rs/cors/master/LICENSE
github.com_russross_blackfriday;https://github.com/russross/blackfriday
github.com_saferwall_pe;https://rawhubusercontent.com/saferwall/pe/master/LICENSE
github.com_saintfish_chardet;https://rawhubusercontent.com/saintfish/chardet/master/LICENSE
github.com_sassoftware_go_rpmutils;https://rawhubusercontent.com/sassoftware/go-rpmutils/master/LICENSE
github.com_scaleway_scaleway_sdk_go;https://github.com/scaleway/scaleway-sdk-go/blob/master/LICENSE
github.com_scylladb_go_set;https://rawhubusercontent.com/scylladb/go-set/master/LICENSE
github.com_sergi_go_diff;https://rawhubusercontent.com/sergi/go-diff/master/LICENSE
github.com_shirou_gopsutil;https://rawhubusercontent.com/shirou/gopsutil/master/LICENSE
github.com_shirou_gopsutil_v3;https://rawhubusercontent.com/shirou/gopsutil/master/LICENSE
github.com_shopspring_decimal;https://rawhubusercontent.com/shopspring/decimal/master/LICENSE
github.com_sijms_go_ora_v2;https://rawhubusercontent.com/sijms/go-ora/master/LICENSE
github.com_sirupsen_logrus;https://rawhubusercontent.com/sirupsen/logrus/master/LICENSE
github.com_skeema_knownhosts;https://rawhubusercontent.com/skeema/knownhosts/master/LICENSE
github.com_snowflakedb_gosnowflake;https://rawhubusercontent.com/snowflakedb/gosnowflake/master/LICENSE
github.com_spdx_tools_golang;https://github.com/spdx/tools-golang
github.com_spf13_afero;https://github.com/spf13/afero
github.com_spf13_cast;https://github.com/spf13/cast
github.com_spf13_cobra;https://github.com/spf13/cobra
github.com_spf13_jwalterweatherman;https://github.com/spf13/jwalterweatherman
github.com_spf13_pflag;https://github.com/spf13/pflag
github.com_spf13_viper;https://github.com/spf13/viper
github.com_stretchr_objx;https://rawhubusercontent.com/stretchr/objx/master/LICENSE
github.com_stretchr_testify;https://rawhubusercontent.com/stretchr/testify/master/LICENSE
github.com_subosito_gotenv;https://rawhubusercontent.com/subosito/gotenv/master/LICENSE
github.com_sylabs_sif_v2;https://rawhubusercontent.com/sylabs/sif/master/LICENSE.md
github.com_sylabs_squashfs;https://rawhubusercontent.com/sylabs/squashfs/master/LICENSE
github.com_tarm_serial;https://rawhubusercontent.com/tarm/serial/master/LICENSE
github.com_therootcompany_xz;https://rawhubusercontent.com/therootcompany/xz/master/LICENSE
github.com_tidwall_gjson;https://rawhubusercontent.com/tidwall/gjson/master/LICENSE
github.com_tidwall_match;https://rawhubusercontent.com/tidwall/match/master/LICENSE
github.com_tidwall_pretty;https://rawhubusercontent.com/tidwall/pretty/master/LICENSE
github.com_tidwall_tinylru;https://rawhubusercontent.com/tidwall/tinylru/master/LICENSE
github.com_tidwall_wal;https://rawhubusercontent.com/tidwall/wal/master/LICENSE
github.com_tklauser_go_sysconf;https://rawhubusercontent.com/tklauser/go-sysconf/master/LICENSE
github.com_tklauser_numcpus;https://rawhubusercontent.com/tklauser/numcpus/master/LICENSE
github.com_ulikunitz_xz;https://rawhubusercontent.com/ulikunitz/xz/master/LICENSE
github.com_vbatts_go_mtree;https://rawhubusercontent.com/vbatts/go-mtree/master/LICENSE
github.com_vbatts_tar_split;https://rawhubusercontent.com/vbatts/tar-split/master/LICENSE
github.com_vifraa_gopom;https://rawhubusercontent.com/vifraa/gopom/master/LICENSE
github.com_vmihailenco_msgpack;https://rawhubusercontent.com/vmihailenco/msgpack/master/LICENSE
EOF
end
