#!/bin/bash -eu
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/c2d-utils || exit 1

prestashop_password="$(get_attribute_value "prestashop-db-password")"
declare -r prestashop_password

mysql -u root -e "CREATE USER 'prestashop'@'localhost'IDENTIFIED WITH mysql_native_password BY'${prestashop_password}';"
mysql -u root -e "GRANT ALL PRIVILEGES ON prestashop.* TO 'prestashop'@'localhost';"
mysql -u root -e "FLUSH PRIVILEGES"