#!/bin/bash -eu
#
# Copyright 2024 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/c2d-utils || exit 1

declare prestashop_db_password="$(get_attribute_value "prestashop-db-password")"
declare prestashop_admin_password="$(get_attribute_value "prestashop-admin-password")"
declare prestashop_admin_email="$(get_attribute_value "prestashop-admin-email")"
declare use_external_ip="$(get_attribute_value "prestashop-use-external-ip")"

declare prestashop_domain="$(get_internal_ip)"
if [[ has_external_ip && "${use_external_ip}" == "1" ]]; then
  prestashop_domain="$(get_external_ip)"
fi

# Run the CLI installer for PrestaShop
cd /var/www/html

php install/index_cli.php \
  --timezone="UTC" \
  --language="en" \
  --domain="${prestashop_domain}" \
  --db_server="localhost" \
  --db_user="prestashop" \
  --db_password="${prestashop_db_password}" \
  --db_name="prestashop" \
  --db_create=1 \
  --name="PrestaShop" \
  --country="us" \
  --firstname="John" \
  --lastname="Doe" \
  --password="${prestashop_admin_password}" \
  --email="${prestashop_admin_email}" \
  --newsletter=0 \
  --send_email=0 \
  --theme=classic

# Change ownership for dirs that PrestaShop needs access to
chown -R www-data:www-data /var/www/html/

# Delete the install directory for security reasons
rm -rf /var/www/html/install

# Rename the admin directory
mv /var/www/html/admin*/ /var/www/html/adminpanel

# Restart apache2
systemctl restart apache2
