#!/bin/bash -eu
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/c2d-utils || exit 1

# Run the CLI installer for PrestaShop
php /var/www/html/install/index_cli.php \
  --timezone="UTC" \
  --language="en" \
  --domain="$(get_external_ip)" \
  --db_server="localhost" \
  --db_user="prestashop" \
  --db_password="$(get_metadata_value "instance/attributes/prestashop-db-password")" \
  --db_name="prestashop" \
  --db_create=1 \
  --name="PrestaShop" \
  --country="us" \
  --firstname="John" \
  --lastname="Doe" \
  --password="$(get_metadata_value "instance/attributes/prestashop-admin-password")" \
  --email="$(get_metadata_value "instance/attributes/prestashop-admin-email")" \
  --newsletter=0 \
  --send_email=0

# Change ownership for dirs that PrestaShop needs access to
chown -R www-data:www-data /var/www/html/

# Delete the install directory for security reasons
rm -rf /var/www/html/install

# Rename the admin directory
mv /var/www/html/admin*/ /var/www/html/adminpanel
