#!/bin/bash -eu
#
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -x 
source /opt/c2d/c2d-utils || exit 1

readonly admin_username="$(get_attribute_value "dolibarr-admin-username")"
readonly admin_password="$(get_attribute_value "dolibarr-admin-password")"

readonly db_username="dolibarr"
readonly db_password="$(get_attribute_value "dolibarr-db-password")"
readonly main_url_root="http://$(get_external_ip)"

cat << 'EOF' > /var/www/html/htdocs/install/install.forced.php

<?php
/* Copyright (C) 2016       Raphaël Doursenaud      <rdoursenaud@gpcsolutions.fr>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/** @var bool Hide PHP informations */
$force_install_nophpinfo = true;

/** @var int 1 = Lock and hide environment variables, 2 = Lock all set variables */
$force_install_noedit = 2;

/** @var string Information message */
$force_install_message = 'Welcome to your Dolibarr install';

/** @var string Data root absolute path (documents folder) */
$force_install_main_data_root = '/var/lib/dolibarr/documents';

/** @var bool Force HTTPS */
$force_install_mainforcehttps = false;

/** @var string Database name */
$force_install_database = 'dolibarr';

/** @var string Database driver (mysql|mysqli|pgsql|mssql|sqlite|sqlite3) */
$force_install_type = 'mysqli';

/** @var string Database tables prefix */
$force_install_prefix = 'llx_';

/** @var bool Force database creation */
$force_install_createdatabase = false;

/** @var string Database username */
$force_install_databaselogin = '';

/** @var string Database password */
$force_install_databasepass = '';

/** @var bool Force database user creation */
$force_install_createuser = false;

/** @var string Database root username */
$force_install_databaserootlogin = 'root';

/** @var string Database root password */
$force_install_databaserootpass = '';

/** @var bool Force install locking */
$force_install_lockinstall = true;

/** @var string Database server host */
$force_install_dbserver = 'localhost';

/** @var int Database server port */
$force_install_port = 3306;

$dolibarr_main_url_root = '';

EOF

# echo '$dolibarr_main_url_root = '"'${dolibarr_main_url_root}';" >> /var/www/html/htdocs/install/install.forced.php
sed -i -e  "s|dolibarr_main_url_root =.*|dolibarr_main_url_root = '${main_url_root}';|g" /var/www/html/htdocs/install/install.forced.php

sed -i -e "s|force_install_databaselogin =.*|force_install_databaselogin = '${db_username}';|g" /var/www/html/htdocs/install/install.forced.php

sed -i -e "s|force_install_databasepass =.*|force_install_databasepass = '${db_password}';|g" /var/www/html/htdocs/install/install.forced.php

curl -s -L http://localhost/install/check.php?testget=ok 

curl -s -L -d 'selectlang=en_US' -d 'action=set' http://localhost/install/fileconf.php 

curl -s -L -d 'selectlang=en_US' -d "main_url=http://$(get_external_ip)" -d 'action=set' \
http://localhost/install/step1.php 

curl -s -L -d 'selectlang=en_US' -d 'action=set' http://localhost/install/step2.php  

curl -s -L -d 'selectlang=en_US' -d 'action=set' http://localhost/install/step4.php  

curl -s -L -d "login=${admin_username}" -d "pass=${admin_password}" \
-d "pass_verif=${admin_password}" -d 'selectlang=en_US' -d 'action=set' \
http://localhost/install/step5.php

touch /var/lib/dolibarr/documents/install.lock 
chown www-data:www-data /var/lib/dolibarr/documents/install.lock 
chmod 444 /var/lib/dolibarr/documents/install.lock 

sed -i "s/dolibarr_main_url_root =.*/dolibarr_main_url_root = 'http:\/\/$(get_external_ip)'/" \
/var/www/html/htdocs/conf/conf.php

# Delete install.forced.php file 
rm /var/www/html/htdocs/install/install.forced.php