#!/bin/bash -eu
#
# Copyright 2024 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/c2d-utils || exit 1

declare -r mysql_root_password="$(get_attribute_value "mysql-root-password")"

declare -r ghost_user="ghost_app"
declare -r ghost_db_name="ghost_production"
declare -r ghost_db_user="ghost"
declare -r ghost_db_password="$(get_attribute_value "ghost-db-password")"

function wait_for_port() {
  local -r host="$1"
  local -r port="$2"
  local -r timeout="${3:-300}"

  timeout --preserve-status "${timeout}" bash -c "until echo > /dev/tcp/${host}/${port}; do sleep 2; done"
  if [[ "$?" -ne 0 ]]; then
    exit 1
  fi
}

# Wait for MySQL to be ready
wait_for_port "localhost" "3306"
mysql -u root -p"${mysql_root_password}" -e "CREATE USER '${ghost_db_user}'@'localhost' IDENTIFIED WITH mysql_native_password BY '${ghost_db_password}';"
mysql -u root -p"${mysql_root_password}" -e "GRANT ALL PRIVILEGES ON ${ghost_db_name}.* TO '${ghost_db_user}'@'localhost';";
mysql -u root -p"${mysql_root_password}" -e "FLUSH PRIVILEGES;"
systemctl restart mysql

cd /var/www/ghost

# Temporarily ghost user as sudoer
echo "${ghost_user} ALL = (ALL) NOPASSWD:ALL" > /etc/sudoers.d/ghost_app

# Install dependencies
runuser ${ghost_user} -c "ghost install \
  --no-stack \
  --no-prompt \
  --no-setup \
  --no-setup-ssl \
  --ip "0.0.0.0" \
  --url="http://$(get_external_ip)" \
  --db=mysql \
  --dbhost="127.0.0.1" \
  --dbuser="${ghost_db_user}" \
  --dbname="${ghost_db_name}" \
  --dbpass="${ghost_db_password}""

# Configure NGINX
runuser ${ghost_user} -c "ghost setup \
  --ip "0.0.0.0" \
  --url="http://$(get_external_ip)" \
  --db=mysql \
  --dbhost="127.0.0.1" \
  --dbuser="${ghost_db_user}" \
  --dbname="${ghost_db_name}" \
  --dbpass="${ghost_db_password}" \
  --no-prommpt"

# Remove default nginx config
rm -f /etc/nginx/conf.d/default.conf
systemctl restart nginx

# Remove sudoer for ghost suer
rm /etc/sudoers.d/ghost_app

# Pre-warm request
curl http://localhost

echo "Setup finished."
