#!/bin/bash -eu
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/c2d-utils || exit 1

ghost_db_password="$(get_attribute_value "ghost-db-password")"
declare -r ghost_db_password

mysql -u root -e "CREATE USER 'ghost'@'localhost' IDENTIFIED BY '${ghost_db_password}';"
mysql -u root -e "GRANT ALL PRIVILEGES ON ghost_production.* TO 'ghost'@'localhost' IDENTIFIED BY '${ghost_db_password}';";
mysql -u root -e "FLUSH PRIVILEGES;"

cd /var/www/ghost

ghost config --no-prompt --url="http://$(get_external_ip)" --dbpass="${ghost_db_password}"
ghost setup --no-prompt --no-setup-mysql --no-setup-ssl
