#!/bin/bash -eu
#
# Copyright 2022 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/concretecms-utils || exit 1

export COMPOSER_HOME="/root/.config/composer"
export COMPOSER_MEMORY_LIMIT=-1
export CONCRETE_PROJECT="$(get_attribute_value "concrete-project")"

# Required fields for ConcreteCMS istallation
declare -r MYSQL_PASSWORD="$(get_attribute_value "mysql-root-password")"
declare -r CONCRETE_DB_PASSWORD="$(get_attribute_value "concrete-db-password")"
declare -r CONCRETE_ADMIN_PASSWORD="$(get_attribute_value "concrete-admin-password")"
declare -r CONCRETE_DB_USER="concrete"
declare -r CONCRETE_DB_NAME="concretedb"
declare -r CONCRETE_ADMIN_USER="admin"
declare -r CONCRETE_FOLDER="/opt/concretecms"
declare -r CONCRETE_DB_SERVER="localhost"

echo "Creating database user..."
create_db_user

echo "Restarting MySQL..."
service mysql restart

mkdir "${CONCRETE_FOLDER}"
cd "${CONCRETE_FOLDER}/"

echo "Configuring and updating composer..."
composer create-project concretecms/composer "${CONCRETE_PROJECT}" -d "${CONCRETE_FOLDER}" -n
cd "${CONCRETE_FOLDER}"/"${CONCRETE_PROJECT}"
composer install -n

echo "Installing Concrete..."
cd "${CONCRETE_FOLDER}/${CONCRETE_PROJECT}"

# Concrete 9.1.3 has a mispelled class name, fix is available in develop branch
# which is not stable
# https://github.com/concretecms/concretecms/blob/9.1.3/concrete/src/Entity/Search/SavedSearch.php#L7
# https://github.com/concretecms/concretecms/blob/develop/concrete/src/Entity/Search/SavedSearch.php#L7
sed 's/MappedSuperClass/MappedSuperclass/g' public/concrete/src/Entity/Search/SavedSearch.php

# Setup script requires orm 2.13
composer require doctrine/orm=2.13 -n

vendor/bin/concrete5 c5:install -vv \
  --db-server="${CONCRETE_DB_SERVER}" \
  --db-username="${CONCRETE_DB_USER}" \
  --db-password="${CONCRETE_DB_PASSWORD}" \
  --db-database="${CONCRETE_DB_NAME}" \
  --admin-password="${CONCRETE_ADMIN_PASSWORD}" \
  --allow-as-root \
  --no-interaction

echo "Configure Apache..."
rm -f /etc/apache2/sites-enabled/000-default.conf
envsubst '\$CONCRETE_PROJECT' < /opt/c2d/apache-concretecms.conf \
  > /etc/apache2/sites-enabled/concretecms.conf

echo "Assign permission to Apache user..."
chown -R www-data:www-data "${CONCRETE_FOLDER}/"

echo "Restarting Apache..."
systemctl restart apache2

echo "Waiting application to be ready..."
wait_for_app

echo "Installation complete!"
