#!/bin/bash -eu
#
# Copyright 2021 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

readonly supervisor_config="/etc/supervisor/conf.d/supervisor-mean.conf"
readonly webapp_homepage="/sites/web/src/index.html"
export NVM_DIR=/usr/local/nvm
export API_PORT=8080
export WEB_PORT=4200
export HTTP_PORT=80

function check_web_ready() {
  echo "$(curl -s -I http://localhost/web/ | grep "200 OK" | wc -l)"
}
# Configure Web app
if [[ -f "${webapp_homepage}" ]]; then
  echo "Setting up Web app..."
  sed -i 's/<base href="\/">/<base href="\/web\/">/g' \
    "${webapp_homepage}"
  echo "Web app set up."
fi

# Configure front end web-server
echo "Setting up NGINX..."
systemctl stop nginx
rm -f /etc/nginx/sites-enabled/default && \
  cat /etc/nginx/sites-available/nginx-mean.conf \
    | envsubst '\$API_PORT,\$WEB_PORT,\$HTTP_PORT' \
    > /etc/nginx/sites-enabled/nginx-mean.conf
echo "NGINX set up."

echo "Starting supervisord..."
supervisord --configuration "${supervisor_config}"

# Await for web project be up before releasing the script
echo "Awaiting for webapp be compiled and served..."
while [[ "$(check_web_ready)" -eq 0 ]]; do
  echo "Not ready."
  sleep 5
done
echo "Angular webapp is ready."

echo "MEAN Stack ready."
