#!/bin/bash -eu
#
# Copyright 2021 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/meanstack-utils || exit 1

readonly enable_metrics="$(get_attribute_value "mean-enable-metrics" \
  | tr '[:upper:]' '[:lower:]')"

# Export variables for templating ready.html page.
export API_PORT=8080
export WEB_PORT=4200
export HTTP_PORT=80
export VERSION_MONGO="$(get_mongo_version)"
export VERSION_EXPRESS="$(get_express_version)"
export VERSION_ANGULAR="$(get_angular_version)"
export VERSION_NODEJS="$(get_nodejs_version)"

# Define SITE_URL
declare SITE_URL="http://$(get_internal_ip)"
if [[ has_external_ip ]]; then
  SITE_URL="http://$(get_external_ip)"
fi
export SITE_URL

# Configure Web app
setup_webapp_homepage

echo "Setting up NGINX..."
systemctl stop nginx

echo "-> Configure Stack on NGINX..."
setup_nginx_stack

# Enable metrics or not
if [[ "${enable_metrics}" == "true" ]]; then
  echo "-> Enable NGINX metrics..."
  enable_metrics_exporter
else
  echo "-> NGINX metrics are disabled."
fi

echo "NGINX set up."
echo "Starting NGINX..."
systemctl start nginx

wait_for_port localhost 27017

echo "Starting supervisord..."
systemctl start supervisor

# Await for web project be up before releasing the script
echo "Awaiting for webapp be compiled and served..."
while [[ "$(check_web_ready)" -eq 0 ]]; do
  echo "Not ready."
  sleep 3
done
echo "Angular webapp is ready."

echo "Setup ready homepage..."
setup_ready_homepage

# Define permissions
chown -R www-data:www-data /sites/

echo "MEAN Stack ready."
