#!/bin/bash -eu
#
# Copyright 2020 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/logstash-utils || exit 1

# Export variables to be used in configuration files
export es_host="$(get_attribute_value "es_host")"
export es_port="$(get_attribute_value "es_port")"
export es_username="$(get_attribute_value "es_username")"
export es_password="$(get_attribute_value "es_password")"

readonly logstash_template="/etc/logstash/conf.d/syslog.conf.template"

echo "Awaiting for Elasticsearch server to be up..."
await_for_host_and_port "${es_host}" "${es_port}"

echo "Setting up Logstash..."

if [[ -z "${es_username}" ]]; then
  echo "Disable authentication"
  readonly line_number="$(cat -n "${logstash_template}" | grep "user =>" | awk '{ print $1 }')"
  readonly template_contents="$(cat "${logstash_template}" | sed "${line_number}d" | sed "${line_number}d")"
  echo "${template_contents}" > "${logstash_template}"
fi

echo "Configuring syslog pipeline..."
fill_in_config_template \
  /etc/logstash/conf.d/ \
  syslog.conf.template \
  syslog.conf

# Enable and start Logstash service
systemctl enable logstash
systemctl start logstash
