#!/bin/bash -eu
#
# Copyright 2021 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/c2d-utils || exit 1

readonly svn_repository_name="$(get_attribute_value "svn-repository-name")"
readonly svn_admin_username="$(get_attribute_value "svn-admin-username")"
readonly svn_admin_password="$(get_attribute_value "svn-admin-password")"

echo "Creating repository..."
mkdir -p /var/lib/svn/ \
  && svnadmin create "/var/lib/svn/${svn_repository_name}" \
  && chown -R www-data:www-data /var/lib/svn \
  && chmod -R 775 /var/lib/svn

echo "Adding ${svn_admin_username} user..."
htpasswd -b -c /etc/apache2/dav_svn.passwd \
  "${svn_admin_username}" "${svn_admin_password}"

echo "Restarting Apache2..."
systemctl restart apache2

echo "Installation complete."
