#!/bin/bash -eu
#
# Copyright 2021 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/resourcespace-utils || exit 1

readonly mysql_db="resourcespace"
readonly mysql_username="$(get_attribute_value "mysql_username")"
readonly mysql_password="$(get_attribute_value "mysql_password")"
readonly mysql_ro_username="$(get_attribute_value "mysql_ro_username")"
readonly mysql_ro_password="$(get_attribute_value "mysql_ro_password")"

echo "Awaiting for MySQL be up..."
wait_for_port "localhost" "3306"

echo "Setting up MySQL users..."
setup_mysql_user "${mysql_db}" "${mysql_username}" "${mysql_password}"
setup_mysql_user "${mysql_db}" "${mysql_ro_username}" "${mysql_ro_password}"

echo "Installation complete!"
