# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ospo_download 'Licenses and Source-code' do
  ref_repos <<-EOF
https://github.com/AndrewSpangler/py_simple_launcher
https://github.com/llinder/deb-ca-certificates-java
https://github.com/certifi/python-certifi
https://github.com/chardet/chardet
https://github.com/anchore/go-version
https://github.com/go-sql-driver/mysql
https://github.com/hashicorp/consul
https://github.com/hashicorp/errwrap
https://github.com/hashicorp/go-checkpoint
https://github.com/hashicorp/go-cleanhttp
https://github.com/hashicorp/go-immutable-radix
https://github.com/hashicorp/go-multierror
https://github.com/hashicorp/go-plugin
https://github.com/hashicorp/go-retryablehttp
https://github.com/hashicorp/go-rootcerts
https://github.com/hashicorp/go-uuid
https://github.com/hashicorp/go-version
https://github.com/hashicorp/golang-lru
https://github.com/hashicorp/hc-install
https://github.com/hashicorp/hcl
https://github.com/hashicorp/logutils
https://github.com/hashicorp/nomad
https://github.com/hashicorp/serf
https://github.com/hashicorp/terraform-exec
https://github.com/hashicorp/terraform-json
https://github.com/hashicorp/terraform-plugin-go
https://github.com/hashicorp/terraform-plugin-log
https://github.com/hashicorp/terraform-plugin-sdk
https://github.com/hashicorp/terraform-registry-address
https://github.com/hashicorp/terraform-svchost
https://github.com/hashicorp/yamux
https://github.com/AdoptOpenJDK/openjdk-jdk11
https://github.com/mvo5/unattended-upgrades

EOF
  licenses <<-EOF
PySimpleSOAP;https://github.com/pysimplesoap/pysimplesoap
PySocks;https://raw.githubusercontent.com/Anorov/PySocks/master/LICENSE
SimpleLauncherExecutable;https://github.com/AndrewSpangler/py_simple_launcher/blob/main/LICENSE
Sphinx;https://raw.githubusercontent.com/sphinx-doc/sphinx/master/LICENSE.rst
actions_cache;https://github.com/actions/cache/blob/main/LICENSE
actions_checkout;https://github.com/actions/checkout/blob/main/LICENSE
actions_download_artifact;https://github.com/actions/download-artifact/blob/main/LICENSE
actions_setup_python;https://github.com/actions/setup-python/blob/main/LICENSE
actions_upload_artifact;https://github.com/actions/upload-artifact/blob/main/LICENSE
activation;https://raw.githubusercontent.com/jenkinsci/jakarta-activation-api-plugin/master/LICENSE
animal_sniffer-annotations;https://raw.githubusercontent.com/mojohaus/animal-sniffer/master/LICENSE
annotations;https://github.com/JetBrains/intellij-community
annotations;https://android.git.kernel.org/
anthoscli;https://github.com/GoogleCloudPlatform/cloud-sdk-docker/blob/master/LICENSE
aopalliance_repackaged;https://github.com/eclipse-ee4j/glassfish-hk2
argcomplete;https://raw.githubusercontent.com/kislyuk/argcomplete/master/LICENSE.rst
argparse;https://github.com/nodeca/argparse
argparse4j;https://github.com/tatsuhiro-t/argparse4j
attrs;https://raw.githubusercontent.com/python-attrs/attrs/master/LICENSE
audience_annotations;https://raw.githubusercontent.com/apache/yetus/master/LICENSE
bash;git+https://github.com/streetsidesoftware/cspell-dicts.git
bitbucket.org_creachadair/stringset;https://bitbucket.org/creachadair/stringset
black;https://raw.githubusercontent.com/psf/black/master/LICENSE
bleach;https://raw.githubusercontent.com/mozilla/bleach/master/LICENSE
ca_certificates-java;https://raw.githubusercontent.com/llinder/deb-ca-certificates-java/master/UpdateCertificates.java
cachetools;https://raw.githubusercontent.com/tkem/cachetools/master/LICENSE
caffeine;https://raw.githubusercontent.com/ben-manes/caffeine/master/LICENSE
certifi;https://raw.githubusercontent.com/certifi/python-certifi/master/LICENSE
cffi;https://raw.githubusercontent.com/python-cffi/cffi/master/LICENSE
chardet;https://raw.githubusercontent.com/chardet/chardet/master/LICENSE
charset_normalizer;https://raw.githubusercontent.com/ousret/charset_normalizer/master/LICENSE
checker_qual;https://raw.githubusercontent.com/typetools/checker-framework/master/LICENSE.txt
click;https://raw.githubusercontent.com/pallets/click/master/LICENSE.rst
cloud.google.com_go;https://raw.githubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go/bigtable;https://raw.githubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go/compute/metadata;https://raw.githubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go/iam;https://raw.githubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go/logging;https://raw.githubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go/longrunning;https://raw.githubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go/monitoring;https://raw.githubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go/osconfig;https://raw.githubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go/storage;https://raw.githubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go/trace;https://raw.githubusercontent.com/googleapis/google-cloud-go/master/LICENSE
codecov_codecov_action;https://github.com/codecov/codecov-action/blob/main/LICENSE
colorlog;https://raw.githubusercontent.com/borntyping/python-colorlog/master/LICENSE
commonmark;https://github.com/rtfd/commonmark.py
commons_beanutils;http://svn.apache.org/viewvc/commons/proper/beanutils/tags/BEANUTILS_1_9_3_RC3
commons_cli;http://svn.apache.org/viewvc/commons/proper/cli/trunk/
commons_collections;http://svn.apache.org/viewvc/commons/proper/collections/trunk
commons_digester;http://svn.apache.org/viewvc/commons/proper/digester/tags/DIGESTER_2_1_RC2
commons_io;https://gitbox.apache.org/repos/asf?p=commons-io.git
commons_lang3;https://git-wip-us.apache.org/repos/asf?p=commons-lang.git
commons_logging;http://svn.apache.org/repos/asf/commons/proper/logging/trunk
commons_validator;https://gitbox.apache.org/repos/asf/commons-validator
connect_api;https://raw.githubusercontent.com/apache/kafka/trunk/LICENSE
connect_basic-auth-extension;https://raw.githubusercontent.com/apache/kafka/trunk/LICENSE
connect_file;https://raw.githubusercontent.com/apache/kafka/trunk/LICENSE
connect_json;https://raw.githubusercontent.com/apache/kafka/trunk/LICENSE
connect_mirror;https://raw.githubusercontent.com/apache/kafka/trunk/LICENSE
connect_mirror-client;https://raw.githubusercontent.com/apache/kafka/trunk/LICENSE
connect_runtime;https://raw.githubusercontent.com/apache/kafka/trunk/LICENSE
connect_transforms;https://raw.githubusercontent.com/apache/kafka/trunk/LICENSE
contrib.go.opencensus.io_exporter/prometheus;https://raw.githubusercontent.com/census-ecosystem/opencensus-go-exporter-prometheus/master/LICENSE
cos.googlesource.com_cos/tools.git;https://cos.googlesource.com/cos/tools
coverage;https://bitbucket.org/ned/coveragepy
crcmod;https://github.com/gsutil-mirrors/crcmod/blob/master/LICENSE
cryptography;https://raw.githubusercontent.com/pyca/cryptography/master/LICENSE
dario.cat_mergo;https://raw.githubusercontent.com/imdario/mergo/master/LICENSE
dbus_python;https://github.com/posborne/dbus-python/blob/master/COPYING
dessant_lock_threads;https://github.com/dessant/lock-threads/blob/main/LICENSE
distlib;https://github.com/pypa/distlib
distro_info;https://github.com/softwarefactory-project/distroinfo/blob/master/LICENSE
docutils;https://raw.githubusercontent.com/docutils/docutils/master/docutils/licenses/BSD-2-Clause.txt
error_prone_annotations;https://github.com/google/error-prone
failureaccess;https://raw.githubusercontent.com/google/guava/master/LICENSE
filelock;https://raw.githubusercontent.com/tox-dev/py-filelock/master/LICENSE
flake8;https://gitlab.com/pycqa/flake8
flake8;https://github.com/pycqa/flake8
flaky;https://raw.githubusercontent.com/box/flaky/master/LICENSE
future;https://raw.githubusercontent.com/google/guava/master/LICENSE
gcp_devrel-py-tools;https://raw.githubusercontent.com/GoogleCloudPlatform/python-repo-tools/master/LICENSE
gcp_docuploader;https://github.com/googleapis/docuploader/blob/main/LICENSE
gcp_releasetool;https://github.com/googleapis/releasetool/blob/master/LICENSE
github.com_99designs/keyring;https://github.com/99designs/keyring
github.com_Azure/azure_sdk-for-go;https://github.com/azure/azure-sdk-for-go
github.com_Azure/azure_sdk-for-go/sdk/azcore;https://github.com/azure/azure-sdk-for-go
github.com_Azure/azure_sdk-for-go/sdk/azidentity;https://github.com/azure/azure-sdk-for-go
github.com_Azure/azure_sdk-for-go/sdk/internal;https://github.com/azure/azure-sdk-for-go
github.com_Azure/azure_sdk-for-go/sdk/resourcemanager/compute/armcompute/v4;https://github.com/azure/azure-sdk-for-go
github.com_Azure/azure_sdk-for-go/sdk/resourcemanager/network/armnetwork/v2;https://github.com/azure/azure-sdk-for-go
github.com_Azure/azure_sdk-for-go/sdk/storage/azblob;https://github.com/azure/azure-sdk-for-go
github.com_Azure/go_autorest/autorest;https://raw.githubusercontent.com/azure/go-autorest/master/LICENSE
github.com_Azure/go_autorest/autorest/adal;https://raw.githubusercontent.com/azure/go-autorest/master/LICENSE
github.com_Azure/go_autorest/autorest/date;https://raw.githubusercontent.com/azure/go-autorest/master/LICENSE
github.com_Azure/go_autorest/autorest/to;https://raw.githubusercontent.com/azure/go-autorest/master/LICENSE
github.com_Azure/go_autorest/autorest/validation;https://raw.githubusercontent.com/azure/go-autorest/master/LICENSE
github.com_Azure/go_autorest/logger;https://raw.githubusercontent.com/azure/go-autorest/master/LICENSE
github.com_Azure/go_autorest/tracing;https://raw.githubusercontent.com/azure/go-autorest/master/LICENSE
github.com_AzureAD/microsoft_authentication-library-for-go;https://raw.githubusercontent.com/azuread/microsoft-authentication-library-for-go/master/LICENSE
github.com_CycloneDX/cyclonedx_go;https://raw.githubusercontent.com/cyclonedx/cyclonedx-go/master/LICENSE
github.com_GoogleCloudPlatform/declarative_resource-client-library;https://raw.githubusercontent.com/googlecloudplatform/declarative-resource-client-library/master/LICENSE
github.com_GoogleCloudPlatform/guest_agent;https://github.com/GoogleCloudPlatform/guest-agent/blob/main/LICENSE
github.com_GoogleCloudPlatform/guest_logging-go;https://raw.githubusercontent.com/googlecloudplatform/guest-logging-go/master/LICENSE
github.com_GoogleCloudPlatform/opentelemetry_operations-collector;https://github.com/GoogleCloudPlatform/opentelemetry-operations-collector/blob/master/LICENSE
github.com_GoogleCloudPlatform/opentelemetry_operations-go/detectors/gcp;https://raw.githubusercontent.com/googlecloudplatform/opentelemetry-operations-go/master/LICENSE
github.com_GoogleCloudPlatform/opentelemetry_operations-go/exporter/collector;https://raw.githubusercontent.com/googlecloudplatform/opentelemetry-operations-go/master/LICENSE
github.com_GoogleCloudPlatform/opentelemetry_operations-go/exporter/collector/googlemanagedprometheus;https://raw.githubusercontent.com/googlecloudplatform/opentelemetry-operations-go/master/LICENSE
github.com_GoogleCloudPlatform/opentelemetry_operations-go/exporter/metric;https://raw.githubusercontent.com/googlecloudplatform/opentelemetry-operations-go/master/LICENSE
github.com_GoogleCloudPlatform/opentelemetry_operations-go/exporter/trace;https://raw.githubusercontent.com/googlecloudplatform/opentelemetry-operations-go/master/LICENSE
github.com_GoogleCloudPlatform/opentelemetry_operations-go/internal/resourcemapping;https://raw.githubusercontent.com/googlecloudplatform/opentelemetry-operations-go/master/LICENSE
github.com_GoogleCloudPlatform/ops_agent;https://github.com/GoogleCloudPlatform/ops-agent/blob/master/LICENSE
github.com_GoogleCloudPlatform/osconfig;https://github.com/GoogleCloudPlatform/osconfig/blob/master/LICENSE
github.com_GoogleContainerTools/kpt;https://raw.githubusercontent.com/googlecontainertools/kpt/master/LICENSE
github.com_GoogleContainerTools/kpt/porch/api;https://raw.githubusercontent.com/googlecontainertools/kpt/master/LICENSE
github.com_JohnCGriffin/overflow;https://github.com/johncgriffin/overflow
github.com_MakeNowJust/heredoc;https://raw.githubusercontent.com/makenowjust/heredoc/master/LICENSE
github.com_Masterminds/goutils;https://github.com/masterminds/goutils
github.com_Masterminds/semver;https://github.com/masterminds/semver
github.com_Masterminds/semver/v3;https://github.com/masterminds/semver
github.com_Masterminds/sprig/v3;https://github.com/masterminds/sprig
github.com_NVIDIA/go_dcgm;https://raw.githubusercontent.com/nvidia/go-dcgm/master/LICENSE
github.com_NVIDIA/go_nvml;https://github.com/NVIDIA/go-nvml/blob/main/LICENSE
github.com_ProtonMail/go_crypto;https://raw.githubusercontent.com/protonmail/go-crypto/master/LICENSE
github.com_SAP/go_hdb;https://raw.githubusercontent.com/sap/go-hdb/master/LICENSE.md
github.com_Showmax/go_fqdn;https://raw.githubusercontent.com/showmax/go-fqdn/master/LICENSE
github.com_acarl005/stripansi;https://github.com/acarl005/stripansi
github.com_acobaugh/osrelease;https://raw.githubusercontent.com/acobaugh/osrelease/master/LICENSE
github.com_adrg/xdg;https://raw.githubusercontent.com/adrg/xdg/master/LICENSE
github.com_aerospike/aerospike_client-go/v6;https://raw.githubusercontent.com/aerospike/aerospike-client-go/master/LICENSE
github.com_agext/levenshtein;https://raw.githubusercontent.com/agext/levenshtein/master/LICENSE
github.com_alecthomas/participle/v2;https://github.com/alecthomas/participle
github.com_alecthomas/units;https://github.com/alecthomas/units
github.com_anchore/bubbly;https://raw.githubusercontent.com/anchore/bubbly/master/LICENSE
github.com_anchore/clio;https://raw.githubusercontent.com/anchore/clio/master/LICENSE
github.com_anchore/fangs;https://raw.githubusercontent.com/anchore/fangs/master/LICENSE
github.com_anchore/go_logger;https://raw.githubusercontent.com/anchore/go-logger/master/LICENSE
github.com_anchore/go_macholibre;https://raw.githubusercontent.com/anchore/go-macholibre/master/LICENSE
github.com_anchore/go_struct-converter;https://raw.githubusercontent.com/anchore/go-struct-converter/master/LICENSE
github.com_anchore/go_version;https://raw.githubusercontent.com/anchore/go-version/master/LICENSE
github.com_anchore/packageurl_go;https://raw.githubusercontent.com/anchore/packageurl-go/master/LICENSE
github.com_anchore/stereoscope;https://raw.githubusercontent.com/anchore/stereoscope/master/LICENSE
github.com_anchore/syft;https://raw.githubusercontent.com/anchore/syft/master/LICENSE
github.com_andybalholm/brotli;https://raw.githubusercontent.com/andybalholm/brotli/master/LICENSE
github.com_apache/arrow/go/v12;https://github.com/apache/arrow
github.com_apache/thrift;https://raw.githubusercontent.com/apache/thrift/master/LICENSE
github.com_apparentlymart/go_cidr;https://raw.githubusercontent.com/apparentlymart/go-cidr/master/LICENSE
github.com_apparentlymart/go_textseg/v13;https://raw.githubusercontent.com/apparentlymart/go-textseg/master/LICENSE
github.com_aquasecurity/go_pep440-version;https://github.com/aquasecurity/go-pep440-version
github.com_aquasecurity/go_version;https://raw.githubusercontent.com/aquasecurity/go-version/master/LICENSE
github.com_armon/go_metrics;https://raw.githubusercontent.com/armon/go-metrics/master/LICENSE
github.com_asaskevich/govalidator;https://raw.githubusercontent.com/asaskevich/govalidator/master/LICENSE
github.com_aws/aws_sdk-go;https://github.com/aws/aws-sdk-go
github.com_aws/aws_sdk-go-v2;https://github.com/aws/aws-sdk-go-v2
github.com_aws/aws_sdk-go-v2/aws/protocol/eventstream;https://github.com/aws/aws-sdk-go-v2
github.com_aws/aws_sdk-go-v2/credentials;https://github.com/aws/aws-sdk-go-v2
github.com_aws/aws_sdk-go-v2/feature/s3/manager;https://github.com/aws/aws-sdk-go-v2
github.com_aws/aws_sdk-go-v2/internal/configsources;https://github.com/aws/aws-sdk-go-v2
github.com_aws/aws_sdk-go-v2/internal/endpoints/v2;https://github.com/aws/aws-sdk-go-v2
github.com_aws/aws_sdk-go-v2/internal/v4a;https://github.com/aws/aws-sdk-go-v2
github.com_aws/aws_sdk-go-v2/service/internal/accept-encoding;https://github.com/aws/aws-sdk-go-v2
github.com_aws/aws_sdk-go-v2/service/internal/checksum;https://github.com/aws/aws-sdk-go-v2
github.com_aws/aws_sdk-go-v2/service/internal/presigned-url;https://github.com/aws/aws-sdk-go-v2
github.com_aws/aws_sdk-go-v2/service/internal/s3shared;https://github.com/aws/aws-sdk-go-v2
github.com_aws/aws_sdk-go-v2/service/s3;https://github.com/aws/aws-sdk-go-v2
github.com_aws/smithy_go;https://raw.githubusercontent.com/aws/smithy-go/master/LICENSE
github.com_aymanbagabas/go_osc52/v2;https://github.com/aymanbagabas/go-osc52
github.com_becheran/wildmatch_go;https://raw.githubusercontent.com/becheran/wildmatch-go/master/LICENSE
github.com_beorn7/perks;https://github.com/beorn7/perks
github.com_bits_and-blooms/bitset;https://raw.githubusercontent.com/bits-and-blooms/bitset/master/LICENSE
github.com_bmatcuk/doublestar/v4;https://raw.githubusercontent.com/bmatcuk/doublestar/master/LICENSE
github.com_cenkalti/backoff;https://raw.githubusercontent.com/cenkalti/backoff/master/LICENSE
github.com_cenkalti/backoff/v4;https://raw.githubusercontent.com/cenkalti/backoff/master/LICENSE
github.com_cespare/xxhash/v2;https://github.com/cespare/xxhash
github.com_chai2010/gettext_go;https://github.com/chai2010/gettext-go
github.com_charmbracelet/bubbles;https://raw.githubusercontent.com/charmbracelet/bubbles/master/LICENSE
github.com_charmbracelet/bubbletea;https://raw.githubusercontent.com/charmbracelet/bubbletea/master/LICENSE
github.com_charmbracelet/harmonica;https://raw.githubusercontent.com/charmbracelet/harmonica/master/LICENSE
github.com_charmbracelet/lipgloss;https://raw.githubusercontent.com/charmbracelet/lipgloss/master/LICENSE
github.com_cloudflare/circl;https://raw.githubusercontent.com/cloudflare/circl/master/LICENSE
github.com_cncf/xds/go;https://raw.githubusercontent.com/cncf/xds/master/LICENSE
github.com_containerd/console;https://raw.githubusercontent.com/containerd/console/master/LICENSE
github.com_containerd/containerd;https://raw.githubusercontent.com/containerd/containerd/master/LICENSE
github.com_containerd/continuity;https://raw.githubusercontent.com/containerd/continuity/master/LICENSE
github.com_containerd/fifo;https://raw.githubusercontent.com/containerd/fifo/master/LICENSE
github.com_containerd/log;https://raw.githubusercontent.com/containerd/log/master/LICENSE
github.com_containerd/stargz_snapshotter/estargz;https://raw.githubusercontent.com/containerd/stargz-snapshotter/master/LICENSE
github.com_containerd/ttrpc;https://raw.githubusercontent.com/containerd/ttrpc/master/LICENSE
github.com_containerd/typeurl/v2;https://raw.githubusercontent.com/containerd/typeurl/master/LICENSE
github.com_cyphar/filepath_securejoin;https://raw.githubusercontent.com/cyphar/filepath-securejoin/master/LICENSE
github.com_davecgh/go_spew;https://raw.githubusercontent.com/davecgh/go-spew/master/LICENSE
github.com_deitch/magic;https://github.com/deitch/magic/blob/main/LICENSE
github.com_denisenkom/go_mssqldb;https://github.com/denisenkom/go-mssqldb
github.com_dennwc/varint;https://raw.githubusercontent.com/dennwc/varint/master/LICENSE
github.com_dgryski/go_rendezvous;https://raw.githubusercontent.com/dgryski/go-rendezvous/master/LICENSE
github.com_digitalocean/godo;https://github.com/digitalocean/godo
github.com_distribution/reference;https://github.com/distribution/reference/blob/main/LICENSE
github.com_docker/cli;https://raw.githubusercontent.com/docker/cli/master/LICENSE
github.com_docker/distribution;https://raw.githubusercontent.com/docker/distribution/master/LICENSE
github.com_docker/docker;https://raw.githubusercontent.com/docker/docker/master/LICENSE
github.com_docker/docker_credential-helpers;https://raw.githubusercontent.com/docker/docker-credential-helpers/master/LICENSE
github.com_docker/go_connections;https://raw.githubusercontent.com/docker/go-connections/master/LICENSE
github.com_docker/go_events;https://raw.githubusercontent.com/docker/go-events/master/LICENSE
github.com_docker/go_units;https://raw.githubusercontent.com/docker/go-units/master/LICENSE
github.com_dsnet/compress;https://raw.githubusercontent.com/dsnet/compress/master/LICENSE.md
github.com_dustin/go_humanize;https://raw.githubusercontent.com/dustin/go-humanize/master/LICENSE
github.com_dvsekhvalnov/jose2go;https://github.com/dvsekhvalnov/jose2go
github.com_edsrzf/mmap_go;https://raw.githubusercontent.com/edsrzf/mmap-go/master/LICENSE
github.com_emicklei/go_restful;https://raw.githubusercontent.com/emicklei/go-restful/master/LICENSE
github.com_emicklei/go_restful/v3;https://raw.githubusercontent.com/emicklei/go-restful/master/LICENSE
github.com_emirpasic/gods;https://raw.githubusercontent.com/emirpasic/gods/master/LICENSE
github.com_envoyproxy/go_control-plane;https://raw.githubusercontent.com/envoyproxy/go-control-plane/master/LICENSE
github.com_envoyproxy/protoc_gen-validate;https://raw.githubusercontent.com/envoyproxy/protoc-gen-validate/master/LICENSE
github.com_evanphx/json_patch;https://raw.githubusercontent.com/evanphx/json-patch/master/LICENSE
github.com_exponent_io/jsonpath;https://raw.githubusercontent.com/exponent-io/jsonpath/master/LICENSE
github.com_expr_lang/expr;https://raw.githubusercontent.com/expr-lang/expr/master/LICENSE
github.com_facebookincubator/nvdtools;https://raw.githubusercontent.com/facebookincubator/nvdtools/master/LICENSE
github.com_fatih/color;https://raw.githubusercontent.com/fatih/color/master/LICENSE.md
github.com_felixge/fgprof;https://github.com/felixge/fgprof
github.com_felixge/httpsnoop;https://github.com/felixge/httpsnoop
github.com_form3tech_oss/jwt-go;https://github.com/form3tech-oss/jwt-go
github.com_fsnotify/fsnotify;https://raw.githubusercontent.com/fsnotify/fsnotify/master/LICENSE
github.com_gabriel_vasile/mimetype;https://raw.githubusercontent.com/gabriel-vasile/mimetype/master/LICENSE
github.com_gammazero/deque;https://raw.githubusercontent.com/gammazero/deque/master/LICENSE
github.com_gammazero/workerpool;https://raw.githubusercontent.com/gammazero/workerpool/master/LICENSE
github.com_ghodss/yaml;https://raw.githubusercontent.com/ghodss/yaml/master/LICENSE
github.com_github/go_spdx/v2;https://raw.githubusercontent.com/github/go-spdx/master/LICENSE
github.com_go_errors/errors;https://github.com/go-errors/errors
github.com_go_git/gcfg;https://raw.githubusercontent.com/go-git/gcfg/master/LICENSE
github.com_go_git/go-billy/v5;https://raw.githubusercontent.com/go-git/go-billy/master/LICENSE
github.com_go_git/go-git/v5;https://raw.githubusercontent.com/go-git/go-git/master/LICENSE
github.com_go_ini/ini;https://raw.githubusercontent.com/go-ini/ini/master/LICENSE
github.com_go_kit/log;https://raw.githubusercontent.com/go-kit/log/master/LICENSE
github.com_go_logfmt/logfmt;https://raw.githubusercontent.com/go-logfmt/logfmt/master/LICENSE
github.com_go_logr/logr;https://raw.githubusercontent.com/go-logr/logr/master/LICENSE
github.com_go_logr/stdr;https://raw.githubusercontent.com/go-logr/stdr/master/LICENSE
github.com_go_openapi/jsonpointer;https://raw.githubusercontent.com/go-openapi/jsonpointer/master/LICENSE
github.com_go_openapi/jsonreference;https://raw.githubusercontent.com/go-openapi/jsonreference/master/LICENSE
github.com_go_openapi/swag;https://raw.githubusercontent.com/go-openapi/swag/master/LICENSE
github.com_go_playground/locales;https://raw.githubusercontent.com/go-playground/locales/master/LICENSE
github.com_go_playground/universal-translator;https://raw.githubusercontent.com/go-playground/universal-translator/master/LICENSE
github.com_go_playground/validator/v10;https://raw.githubusercontent.com/go-playground/validator/master/LICENSE
github.com_go_restruct/restruct;https://github.com/go-restruct/restruct/blob/master/LICENSE.md
github.com_go_resty/resty/v2;https://raw.githubusercontent.com/go-resty/resty/master/LICENSE
github.com_go_sql-driver/mysql;https://raw.githubusercontent.com/go-sql-driver/mysql/master/LICENSE
github.com_go_zookeeper/zk;https://raw.githubusercontent.com/go-zookeeper/zk/master/LICENSE
github.com_gobwas/glob;https://raw.githubusercontent.com/gobwas/glob/master/LICENSE
github.com_goccy/go_json;https://raw.githubusercontent.com/goccy/go-json/master/LICENSE
github.com_goccy/go_yaml;https://raw.githubusercontent.com/goccy/go-yaml/master/LICENSE
github.com_godbus/dbus;https://raw.githubusercontent.com/godbus/dbus/master/LICENSE
github.com_gogo/protobuf;https://raw.githubusercontent.com/gogo/protobuf/master/LICENSE
github.com_golang_jwt/jwt/v4;https://raw.githubusercontent.com/golang-jwt/jwt/master/LICENSE
github.com_golang_jwt/jwt/v5;https://raw.githubusercontent.com/golang-jwt/jwt/master/LICENSE
github.com_golang_sql/civil;https://raw.githubusercontent.com/golang-sql/civil/master/LICENSE
github.com_golang_sql/sqlexp;https://raw.githubusercontent.com/golang-sql/sqlexp/master/LICENSE
github.com_golang/glog;https://raw.githubusercontent.com/golang/glog/master/LICENSE
github.com_golang/groupcache;https://raw.githubusercontent.com/golang/groupcache/master/LICENSE
github.com_golang/mock;https://raw.githubusercontent.com/golang/mock/master/LICENSE
github.com_golang/protobuf;https://raw.githubusercontent.com/golang/protobuf/master/LICENSE
github.com_golang/snappy;https://raw.githubusercontent.com/golang/snappy/master/LICENSE
github.com_google/btree;https://raw.githubusercontent.com/google/btree/master/LICENSE
github.com_google/flatbuffers;https://raw.githubusercontent.com/google/flatbuffers/master/LICENSE
github.com_google/gnostic;https://raw.githubusercontent.com/google/gnostic/master/LICENSE
github.com_google/gnostic_models;https://raw.githubusercontent.com/google/gnostic-models/master/LICENSE
github.com_google/go_cmp;https://raw.githubusercontent.com/google/go-cmp/master/LICENSE
github.com_google/go_containerregistry;https://raw.githubusercontent.com/google/go-containerregistry/master/LICENSE
github.com_google/go_cpy;https://raw.githubusercontent.com/google/go-cpy/master/LICENSE
github.com_google/go_querystring;https://raw.githubusercontent.com/google/go-querystring/master/LICENSE
github.com_google/go_sev-guest;https://raw.githubusercontent.com/google/go-sev-guest/master/LICENSE
github.com_google/go_tpm;https://raw.githubusercontent.com/google/go-tpm/master/LICENSE
github.com_google/go_tpm-tools;https://raw.githubusercontent.com/google/go-tpm-tools/master/LICENSE
github.com_google/gofuzz;https://raw.githubusercontent.com/google/gofuzz/master/LICENSE
github.com_google/licensecheck;https://raw.githubusercontent.com/google/licensecheck/master/LICENSE
github.com_google/logger;https://raw.githubusercontent.com/google/logger/master/LICENSE
github.com_google/pprof;https://raw.githubusercontent.com/google/pprof/master/LICENSE
github.com_google/s2a_go;https://github.com/google/s2a-go
github.com_google/shlex;https://github.com/google/shlex
github.com_google/tink/go;https://raw.githubusercontent.com/google/tink/master/LICENSE
github.com_google/uuid;https://raw.githubusercontent.com/google/uuid/master/LICENSE
github.com_googleapis/enterprise_certificate-proxy;https://raw.githubusercontent.com/googleapis/enterprise-certificate-proxy/master/LICENSE
github.com_googleapis/gax_go/v2;https://raw.githubusercontent.com/googleapis/gax-go/master/LICENSE
github.com_gookit/color;https://raw.githubusercontent.com/gookit/color/master/LICENSE
github.com_gophercloud/gophercloud;https://raw.githubusercontent.com/gophercloud/gophercloud/master/LICENSE
github.com_gorilla/websocket;https://raw.githubusercontent.com/gorilla/websocket/master/LICENSE
github.com_grafana/regexp;https://raw.githubusercontent.com/grafana/regexp/master/LICENSE
github.com_gregjones/httpcache;https://github.com/gregjones/httpcache
github.com_grobie/gomemcache;https://raw.githubusercontent.com/grobie/gomemcache/master/LICENSE
github.com_grpc_ecosystem/go-grpc-middleware;https://raw.githubusercontent.com/grpc-ecosystem/go-grpc-middleware/master/LICENSE
github.com_grpc_ecosystem/grpc-gateway/v2;https://raw.githubusercontent.com/grpc-ecosystem/grpc-gateway/master/LICENSE
github.com_gsterjov/go_libsecret;https://raw.githubusercontent.com/gsterjov/go-libsecret/master/LICENSE
github.com_hashicorp/consul/api;https://raw.githubusercontent.com/hashicorp/consul/master/LICENSE
github.com_hashicorp/cronexpr;https://raw.githubusercontent.com/hashicorp/cronexpr/master/LICENSE
github.com_hashicorp/errwrap;https://raw.githubusercontent.com/hashicorp/errwrap/master/LICENSE
github.com_hashicorp/go_checkpoint;https://raw.githubusercontent.com/hashicorp/go-checkpoint/master/LICENSE
github.com_hashicorp/go_cleanhttp;https://raw.githubusercontent.com/hashicorp/go-cleanhttp/master/LICENSE
github.com_hashicorp/go_cty;https://raw.githubusercontent.com/hashicorp/go-cty/master/LICENSE
github.com_hashicorp/go_hclog;https://raw.githubusercontent.com/hashicorp/go-hclog/master/LICENSE
github.com_hashicorp/go_immutable-radix;https://raw.githubusercontent.com/hashicorp/go-immutable-radix/master/LICENSE
github.com_hashicorp/go_multierror;https://raw.githubusercontent.com/hashicorp/go-multierror/master/LICENSE
github.com_hashicorp/go_plugin;https://raw.githubusercontent.com/hashicorp/go-plugin/master/LICENSE
github.com_hashicorp/go_retryablehttp;https://raw.githubusercontent.com/hashicorp/go-retryablehttp/master/LICENSE
github.com_hashicorp/go_rootcerts;https://raw.githubusercontent.com/hashicorp/go-rootcerts/master/LICENSE
github.com_hashicorp/go_uuid;https://raw.githubusercontent.com/hashicorp/go-uuid/master/LICENSE
github.com_hashicorp/go_version;https://raw.githubusercontent.com/hashicorp/go-version/master/LICENSE
github.com_hashicorp/golang_lru;https://raw.githubusercontent.com/hashicorp/golang-lru/master/LICENSE
github.com_hashicorp/hc_install;https://raw.githubusercontent.com/hashicorp/hc-install/master/LICENSE
github.com_hashicorp/hcl;https://raw.githubusercontent.com/hashicorp/hcl/master/LICENSE
github.com_hashicorp/hcl/v2;https://raw.githubusercontent.com/hashicorp/hcl/master/LICENSE
github.com_hashicorp/logutils;https://raw.githubusercontent.com/hashicorp/logutils/master/LICENSE
github.com_hashicorp/nomad/api;https://raw.githubusercontent.com/hashicorp/nomad/master/LICENSE
github.com_hashicorp/serf;https://raw.githubusercontent.com/hashicorp/serf/master/LICENSE
github.com_hashicorp/terraform_exec;https://raw.githubusercontent.com/hashicorp/terraform-exec/master/LICENSE
github.com_hashicorp/terraform_json;https://raw.githubusercontent.com/hashicorp/terraform-json/master/LICENSE
github.com_hashicorp/terraform_plugin-go;https://raw.githubusercontent.com/hashicorp/terraform-plugin-go/master/LICENSE
github.com_hashicorp/terraform_plugin-log;https://raw.githubusercontent.com/hashicorp/terraform-plugin-log/master/LICENSE
github.com_hashicorp/terraform_plugin-sdk/v2;https://raw.githubusercontent.com/hashicorp/terraform-plugin-sdk/master/LICENSE
github.com_hashicorp/terraform_registry-address;https://raw.githubusercontent.com/hashicorp/terraform-registry-address/master/LICENSE
github.com_hashicorp/terraform_svchost;https://raw.githubusercontent.com/hashicorp/terraform-svchost/master/LICENSE
github.com_hashicorp/yamux;https://raw.githubusercontent.com/hashicorp/yamux/master/LICENSE
github.com_hetznercloud/hcloud_go;https://raw.githubusercontent.com/hetznercloud/hcloud-go/master/LICENSE
github.com_hetznercloud/hcloud_go/v2;https://raw.githubusercontent.com/hetznercloud/hcloud-go/master/LICENSE
github.com_huandu/xstrings;https://raw.githubusercontent.com/huandu/xstrings/master/LICENSE
github.com_iancoleman/strcase;https://raw.githubusercontent.com/iancoleman/strcase/master/LICENSE
github.com_imdario/mergo;https://raw.githubusercontent.com/imdario/mergo/master/LICENSE
github.com_influxdata/go_syslog/v3;https://raw.githubusercontent.com/influxdata/go-syslog/master/LICENSE
github.com_ionos_cloud/sdk-go/v6;https://raw.githubusercontent.com/ionos-cloud/sdk-go/master/LICENSE
github.com_jbenet/go_context;https://raw.githubusercontent.com/jbenet/go-context/master/LICENSE
github.com_jinzhu/copier;https://github.com/jinzhu/copier
github.com_jmespath/go_jmespath;https://raw.githubusercontent.com/jmespath/go-jmespath/master/LICENSE
github.com_josharian/intern;https://raw.githubusercontent.com/josharian/intern/master/LICENSE.md
github.com_jpillora/backoff;https://raw.githubusercontent.com/jpillora/backoff/master/LICENSE
github.com_json_iterator/go;https://raw.githubusercontent.com/json-iterator/go/master/LICENSE
github.com_julienschmidt/httprouter;https://raw.githubusercontent.com/julienschmidt/httprouter/master/LICENSE
github.com_kardianos/osext;https://raw.githubusercontent.com/kardianos/osext/master/LICENSE
github.com_kardianos/service;https://raw.githubusercontent.com/kardianos/service/master/LICENSE
github.com_kastenhq/goversion;https://raw.githubusercontent.com/kastenhq/goversion/master/LICENSE
github.com_kevinburke/ssh_config;https://raw.githubusercontent.com/kevinburke/ssh_config/master/LICENSE
github.com_klauspost/compress;https://raw.githubusercontent.com/klauspost/compress/master/LICENSE
github.com_klauspost/cpuid/v2;https://raw.githubusercontent.com/klauspost/cpuid/master/LICENSE
github.com_klauspost/pgzip;https://raw.githubusercontent.com/klauspost/pgzip/master/LICENSE
github.com_knadh/koanf;https://raw.githubusercontent.com/knadh/koanf/master/LICENSE
github.com_knadh/koanf/v2;https://raw.githubusercontent.com/knadh/koanf/master/LICENSE
github.com_knqyf263/go_rpmdb;https://github.com/knqyf263/go-rpmdb
github.com_kolo/xmlrpc;https://raw.githubusercontent.com/kolo/xmlrpc/master/LICENSE
github.com_kylelemons/godebug;https://raw.githubusercontent.com/kylelemons/godebug/master/LICENSE
github.com_leodido/go_urn;https://raw.githubusercontent.com/leodido/go-urn/master/LICENSE
github.com_leodido/ragel_machinery;https://raw.githubusercontent.com/leodido/ragel-machinery/master/LICENSE
github.com_lib/pq;https://raw.githubusercontent.com/lib/pq/master/LICENSE.md
github.com_liggitt/tabwriter;https://raw.githubusercontent.com/liggitt/tabwriter/master/LICENSE
github.com_linode/linodego;https://raw.githubusercontent.com/linode/linodego/master/LICENSE
github.com_lucasb_eyer/go-colorful;https://raw.githubusercontent.com/lucasb-eyer/go-colorful/master/LICENSE
github.com_magiconair/properties;https://raw.githubusercontent.com/magiconair/properties/master/LICENSE.md
github.com_mailru/easyjson;https://raw.githubusercontent.com/mailru/easyjson/master/LICENSE
github.com_mattn/go_colorable;https://raw.githubusercontent.com/mattn/go-colorable/master/LICENSE
github.com_mattn/go_isatty;https://raw.githubusercontent.com/mattn/go-isatty/master/LICENSE
github.com_mattn/go_localereader;https://raw.githubusercontent.com/mattn/go-localereader/master/LICENSE
github.com_mattn/go_runewidth;https://raw.githubusercontent.com/mattn/go-runewidth/master/LICENSE
github.com_matttproud/golang_protobuf_extensions;https://raw.githubusercontent.com/matttproud/golang_protobuf_extensions/master/LICENSE
github.com_matttproud/golang_protobuf_extensions/v2;https://raw.githubusercontent.com/matttproud/golang_protobuf_extensions/master/LICENSE
github.com_mgutz/ansi;https://raw.githubusercontent.com/mgutz/ansi/master/LICENSE
github.com_mholt/archiver/v3;https://raw.githubusercontent.com/mholt/archiver/master/LICENSE
github.com_microsoft/go_rustaudit;https://raw.githubusercontent.com/microsoft/go-rustaudit/master/LICENSE
github.com_miekg/dns;https://raw.githubusercontent.com/miekg/dns/master/LICENSE
github.com_mitchellh/copystructure;https://raw.githubusercontent.com/mitchellh/copystructure/master/LICENSE
github.com_mitchellh/go_homedir;https://raw.githubusercontent.com/mitchellh/go-homedir/master/LICENSE
github.com_mitchellh/go_testing-interface;https://raw.githubusercontent.com/mitchellh/go-testing-interface/master/LICENSE
github.com_mitchellh/go_wordwrap;https://raw.githubusercontent.com/mitchellh/go-wordwrap/master/LICENSE.md
github.com_mitchellh/hashstructure;https://raw.githubusercontent.com/mitchellh/hashstructure/master/LICENSE
github.com_mitchellh/hashstructure/v2;https://raw.githubusercontent.com/mitchellh/hashstructure/master/LICENSE
github.com_mitchellh/mapstructure;https://raw.githubusercontent.com/mitchellh/mapstructure/master/LICENSE
github.com_mitchellh/reflectwalk;https://raw.githubusercontent.com/mitchellh/reflectwalk/master/LICENSE
github.com_moby/locker;https://raw.githubusercontent.com/moby/locker/master/LICENSE
github.com_moby/spdystream;https://raw.githubusercontent.com/moby/spdystream/master/LICENSE
github.com_moby/sys/mountinfo;https://raw.githubusercontent.com/moby/sys/master/LICENSE
github.com_moby/sys/signal;https://raw.githubusercontent.com/moby/sys/master/LICENSE
github.com_moby/term;https://raw.githubusercontent.com/moby/term/master/LICENSE
github.com_modern_go/concurrent;https://raw.githubusercontent.com/modern-go/concurrent/master/LICENSE
github.com_modern_go/reflect2;https://github.com/modern-go/reflect2
github.com_monochromegane/go_gitignore;https://raw.githubusercontent.com/monochromegane/go-gitignore/master/LICENSE
github.com_montanaflynn/stats;https://raw.githubusercontent.com/montanaflynn/stats/master/LICENSE
github.com_mostynb/go_grpc-compression;https://raw.githubusercontent.com/mostynb/go-grpc-compression/master/LICENSE
github.com_mtibben/percent;https://raw.githubusercontent.com/mtibben/percent/master/LICENSE
github.com_muesli/ansi;https://raw.githubusercontent.com/muesli/ansi/master/LICENSE
github.com_muesli/cancelreader;https://raw.githubusercontent.com/muesli/cancelreader/master/LICENSE
github.com_muesli/reflow;https://raw.githubusercontent.com/muesli/reflow/master/LICENSE
github.com_muesli/termenv;https://raw.githubusercontent.com/muesli/termenv/master/LICENSE
github.com_munnerz/goautoneg;https://raw.githubusercontent.com/munnerz/goautoneg/master/LICENSE
github.com_mwitkow/go_conntrack;https://raw.githubusercontent.com/mwitkow/go-conntrack/master/LICENSE
github.com_nasa9084/go_openapi;https://github.com/nasa9084/go-openapi
github.com_nginxinc/nginx_prometheus-exporter;https://raw.githubusercontent.com/nginxinc/nginx-prometheus-exporter/master/LICENSE
github.com_nwaples/rardecode;https://raw.githubusercontent.com/nwaples/rardecode/master/LICENSE
github.com_oklog/run;https://raw.githubusercontent.com/oklog/run/master/LICENSE
github.com_olekukonko/tablewriter;https://raw.githubusercontent.com/olekukonko/tablewriter/master/LICENSE.md
github.com_open_telemetry/opentelemetry-collector-contrib/exporter/fileexporter;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/exporter/googlecloudexporter;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/internal/aws/ecsutil;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/internal/common;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/internal/coreinternal;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/internal/filter;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/internal/k8sconfig;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/internal/metadataproviders;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/internal/sharedcomponent;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/pkg/ottl;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/pkg/pdatautil;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/pkg/stanza;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/pkg/translator/prometheus;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/processor/filterprocessor;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/processor/groupbyattrsprocessor;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/processor/metricstransformprocessor;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/processor/resourceprocessor;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/processor/transformprocessor;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/receiver/activedirectorydsreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/receiver/aerospikereceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/receiver/apachereceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/receiver/couchdbreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/receiver/elasticsearchreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/receiver/flinkmetricsreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/receiver/iisreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/receiver/memcachedreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/receiver/mysqlreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/receiver/nginxreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/receiver/rabbitmqreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/receiver/redisreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/receiver/saphanareceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/receiver/sqlserverreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/receiver/windowsperfcountersreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry/opentelemetry-collector-contrib/receiver/zookeeperreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_opencontainers/go_digest;https://raw.githubusercontent.com/opencontainers/go-digest/master/LICENSE
github.com_opencontainers/image_spec;https://raw.githubusercontent.com/opencontainers/image-spec/master/LICENSE
github.com_opencontainers/runc;https://raw.githubusercontent.com/opencontainers/runc/master/LICENSE
github.com_opencontainers/runtime_spec;https://raw.githubusercontent.com/opencontainers/runtime-spec/master/LICENSE
github.com_opencontainers/selinux;https://raw.githubusercontent.com/opencontainers/selinux/master/LICENSE
github.com_openshift/api;https://raw.githubusercontent.com/openshift/api/master/LICENSE
github.com_openshift/client_go;https://raw.githubusercontent.com/openshift/client-go/master/LICENSE
github.com_otiai10/copy;https://github.com/otiai10/copy
github.com_ovh/go_ovh;https://raw.githubusercontent.com/ovh/go-ovh/master/LICENSE
github.com_pborman/indent;https://raw.githubusercontent.com/pborman/indent/master/LICENSE
github.com_pborman/uuid;https://raw.githubusercontent.com/pborman/uuid/master/LICENSE
github.com_pelletier/go_toml;https://raw.githubusercontent.com/pelletier/go-toml/master/LICENSE
github.com_pelletier/go_toml/v2;https://raw.githubusercontent.com/pelletier/go-toml/master/LICENSE
github.com_peterbourgon/diskv;https://raw.githubusercontent.com/peterbourgon/diskv/master/LICENSE
github.com_pierrec/lz4/v4;https://github.com/pierrec/lz4
github.com_pjbgf/sha1cd;https://github.com/pjbgf/sha1cd
github.com_pkg/browser;https://raw.githubusercontent.com/pkg/browser/master/LICENSE
github.com_pkg/errors;https://raw.githubusercontent.com/pkg/errors/master/LICENSE
github.com_pkg/profile;https://raw.githubusercontent.com/pkg/profile/master/LICENSE
github.com_pmezard/go_difflib;https://raw.githubusercontent.com/pmezard/go-difflib/master/LICENSE
github.com_prometheus/client_golang;https://raw.githubusercontent.com/prometheus/client_golang/master/LICENSE
github.com_prometheus/client_model;https://raw.githubusercontent.com/prometheus/client_model/master/LICENSE
github.com_prometheus/common;https://raw.githubusercontent.com/prometheus/common/master/LICENSE
github.com_prometheus/common/sigv4;https://raw.githubusercontent.com/prometheus/common/master/LICENSE
github.com_prometheus/procfs;https://raw.githubusercontent.com/prometheus/procfs/master/LICENSE
github.com_prometheus/prometheus;https://raw.githubusercontent.com/prometheus/prometheus/master/LICENSE
github.com_prometheus/statsd_exporter;https://raw.githubusercontent.com/prometheus/statsd_exporter/master/LICENSE
github.com_redis/go_redis/v9;https://raw.githubusercontent.com/redis/go-redis/master/LICENSE
github.com_remyoudompheng/bigfft;https://raw.githubusercontent.com/remyoudompheng/bigfft/master/LICENSE
github.com_rivo/uniseg;https://github.com/rivo/uniseg
github.com_robfig/cron/v3;https://raw.githubusercontent.com/robfig/cron/master/LICENSE
github.com_rs/cors;https://raw.githubusercontent.com/rs/cors/master/LICENSE
github.com_russross/blackfriday;https://github.com/russross/blackfriday
github.com_saferwall/pe;https://raw.githubusercontent.com/saferwall/pe/master/LICENSE
github.com_saintfish/chardet;https://raw.githubusercontent.com/saintfish/chardet/master/LICENSE
github.com_sassoftware/go_rpmutils;https://raw.githubusercontent.com/sassoftware/go-rpmutils/master/LICENSE
github.com_scaleway/scaleway_sdk-go;https://raw.githubusercontent.com/scaleway/scaleway-sdk-go/master/LICENSE
github.com_scylladb/go_set;https://raw.githubusercontent.com/scylladb/go-set/master/LICENSE
github.com_sergi/go_diff;https://raw.githubusercontent.com/sergi/go-diff/master/LICENSE
github.com_shirou/gopsutil;https://raw.githubusercontent.com/shirou/gopsutil/master/LICENSE
github.com_shirou/gopsutil/v3;https://raw.githubusercontent.com/shirou/gopsutil/master/LICENSE
github.com_shopspring/decimal;https://raw.githubusercontent.com/shopspring/decimal/master/LICENSE
github.com_sijms/go_ora/v2;https://raw.githubusercontent.com/sijms/go-ora/master/LICENSE
github.com_sirupsen/logrus;https://raw.githubusercontent.com/sirupsen/logrus/master/LICENSE
github.com_skeema/knownhosts;https://raw.githubusercontent.com/skeema/knownhosts/master/LICENSE
github.com_snowflakedb/gosnowflake;https://raw.githubusercontent.com/snowflakedb/gosnowflake/master/LICENSE
github.com_spf13/afero;https://github.com/spf13/afero
github.com_spf13/cast;https://github.com/spf13/cast
github.com_spf13/cobra;https://github.com/spf13/cobra
github.com_spf13/jwalterweatherman;https://github.com/spf13/jwalterweatherman
github.com_spf13/pflag;https://github.com/spf13/pflag
github.com_spf13/viper;https://github.com/spf13/viper
github.com_stretchr/objx;https://raw.githubusercontent.com/stretchr/objx/master/LICENSE
github.com_stretchr/testify;https://raw.githubusercontent.com/stretchr/testify/master/LICENSE
github.com_subosito/gotenv;https://raw.githubusercontent.com/subosito/gotenv/master/LICENSE
github.com_sylabs/sif/v2;https://raw.githubusercontent.com/sylabs/sif/master/LICENSE.md
github.com_sylabs/squashfs;https://raw.githubusercontent.com/sylabs/squashfs/master/LICENSE
github.com_tarm/serial;https://raw.githubusercontent.com/tarm/serial/master/LICENSE
github.com_therootcompany/xz;https://raw.githubusercontent.com/therootcompany/xz/master/LICENSE
github.com_tidwall/gjson;https://raw.githubusercontent.com/tidwall/gjson/master/LICENSE
github.com_tidwall/match;https://raw.githubusercontent.com/tidwall/match/master/LICENSE
github.com_tidwall/pretty;https://raw.githubusercontent.com/tidwall/pretty/master/LICENSE
github.com_tidwall/tinylru;https://raw.githubusercontent.com/tidwall/tinylru/master/LICENSE
github.com_tidwall/wal;https://raw.githubusercontent.com/tidwall/wal/master/LICENSE
github.com_tklauser/go_sysconf;https://raw.githubusercontent.com/tklauser/go-sysconf/master/LICENSE
github.com_tklauser/numcpus;https://raw.githubusercontent.com/tklauser/numcpus/master/LICENSE
github.com_ulikunitz/xz;https://raw.githubusercontent.com/ulikunitz/xz/master/LICENSE
github.com_vbatts/go_mtree;https://raw.githubusercontent.com/vbatts/go-mtree/master/LICENSE
github.com_vbatts/tar_split;https://raw.githubusercontent.com/vbatts/tar-split/master/LICENSE
github.com_vifraa/gopom;https://raw.githubusercontent.com/vifraa/gopom/master/LICENSE
github.com_vmihailenco/msgpack;https://raw.githubusercontent.com/vmihailenco/msgpack/master/LICENSE
github.com_vmihailenco/msgpack/v4;https://raw.githubusercontent.com/vmihailenco/msgpack/master/LICENSE
github.com_vmihailenco/tagparser;https://raw.githubusercontent.com/vmihailenco/tagparser/master/LICENSE
github.com_vultr/govultr/v2;https://raw.githubusercontent.com/vultr/govultr/master/LICENSE
github.com_wagoodman/go_partybus;https://raw.githubusercontent.com/wagoodman/go-partybus/master/LICENSE
github.com_wagoodman/go_progress;https://raw.githubusercontent.com/wagoodman/go-progress/master/LICENSE
github.com_xanzy/ssh_agent;https://raw.githubusercontent.com/xanzy/ssh-agent/master/LICENSE
github.com_xdg_go/pbkdf2;https://github.com/xdg-go/pbkdf2
github.com_xdg_go/scram;https://raw.githubusercontent.com/xdg-go/scram/master/LICENSE
github.com_xdg_go/stringprep;https://raw.githubusercontent.com/xdg-go/stringprep/master/LICENSE
github.com_xi2/xz;https://github.com/xi2/xz
github.com_xlab/treeprint;https://raw.githubusercontent.com/xlab/treeprint/master/LICENSE
github.com_xo/terminfo;https://raw.githubusercontent.com/xo/terminfo/master/LICENSE
github.com_youmark/pkcs8;https://github.com/youmark/pkcs8/blob/master/LICENSE
github.com_yuin/gopher_lua;https://raw.githubusercontent.com/yuin/gopher-lua/master/LICENSE
github.com_zclconf/go_cty;https://raw.githubusercontent.com/zclconf/go-cty/master/LICENSE
github.com_zeebo/xxh3;https://github.com/zeebo/xxh3
github.com_zyedidia/generic;https://raw.githubusercontent.com/zyedidia/generic/master/LICENSE
github_codeql_action/analyze;https://github.com/github/codeql-action/blob/main/LICENSE
github_codeql_action/autobuild;https://github.com/github/codeql-action/blob/main/LICENSE
github_codeql_action/init;https://github.com/github/codeql-action/blob/main/LICENSE
go.chromium.org_luci;https://chromium.googlesource.com/infra/luci/luci-go
go.mongodb.org_mongo_driver;https://raw.githubusercontent.com/mongodb/mongo-go-driver/master/LICENSE
go.mozilla.org_pkcs7;https://github.com/mozilla-services/pkcs7
go.opencensus.io;https://raw.githubusercontent.com/census-instrumentation/opencensus-go/master/LICENSE
go.opentelemetry.io_collector;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/component;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/config/configauth;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/config/configcompression;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/config/configgrpc;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/config/confighttp;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/config/confignet;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/config/configopaque;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/config/configtelemetry;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/config/configtls;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/config/internal;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/confmap;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/connector;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/consumer;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/exporter;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/exporter/loggingexporter;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/exporter/otlpexporter;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/exporter/otlphttpexporter;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/extension;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/extension/auth;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/extension/ballastextension;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/extension/zpagesextension;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/featuregate;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/otelcol;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/pdata;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/processor;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/processor/batchprocessor;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/processor/memorylimiterprocessor;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/receiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/receiver/otlpreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/semconv;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector/service;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_contrib/config;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go-contrib/master/LICENSE
go.opentelemetry.io_contrib/detectors/gcp;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go-contrib/master/LICENSE
go.opentelemetry.io_contrib/instrumentation/google.golang.org/grpc/otelgrpc;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go-contrib/master/LICENSE
go.opentelemetry.io_contrib/instrumentation/net/http/otelhttp;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go-contrib/master/LICENSE
go.opentelemetry.io_contrib/propagators/b3;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go-contrib/master/LICENSE
go.opentelemetry.io_contrib/zpages;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go-contrib/master/LICENSE
go.opentelemetry.io_otel;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel/bridge/opencensus;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel/exporters/otlp/otlpmetric/otlpmetricgrpc;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel/exporters/otlp/otlpmetric/otlpmetrichttp;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel/exporters/otlp/otlptrace;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel/exporters/otlp/otlptrace/otlptracegrpc;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel/exporters/otlp/otlptrace/otlptracehttp;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel/exporters/prometheus;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel/exporters/stdout/stdoutmetric;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel/exporters/stdout/stdouttrace;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel/metric;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel/sdk;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel/sdk/metric;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel/trace;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_proto/otlp;https://raw.githubusercontent.com/open-telemetry/opentelemetry-proto-go/master/LICENSE
go.starlark.net;https://raw.githubusercontent.com/google/starlark-go/master/LICENSE
go.uber.org_atomic;https://github.com/uber-go/atomic
go.uber.org_multierr;https://github.com/uber-go/multierr
go.uber.org_zap;https://raw.githubusercontent.com/uber-go/zap/master/LICENSE
golang.org_x/crypto;https://go.googlesource.com/crypto
golang.org_x/exp;https://go.googlesource.com/exp
golang.org_x/mod;https://go.googlesource.com/mod
golang.org_x/net;https://go.googlesource.com/net
golang.org_x/oauth2;https://go.googlesource.com/oauth2
golang.org_x/sync;https://go.googlesource.com/sync
golang.org_x/sys;https://go.googlesource.com/sys
golang.org_x/term;https://go.googlesource.com/term
golang.org_x/text;https://go.googlesource.com/text
golang.org_x/time;https://go.googlesource.com/time
golang.org_x/xerrors;https://go.googlesource.com/xerrors
gonum.org_v1/gonum;https://raw.githubusercontent.com/gonum/gonum/master/LICENSE
google_api-core;https://raw.githubusercontent.com/googleapis/python-api-core/master/LICENSE
google_auth;https://raw.githubusercontent.com/googleapis/google-auth-library-python/master/LICENSE
google_cloud-compute;https://raw.githubusercontent.com/googleapis/python-compute/master/LICENSE
google_cloud-core;https://raw.githubusercontent.com/googleapis/python-cloud-core/master/LICENSE
google_cloud-storage;https://raw.githubusercontent.com/googleapis/python-storage/master/LICENSE
google_crc32c;https://github.com/googleapis/python-crc32c
google_resumable-media;https://raw.githubusercontent.com/googleapis/google-resumable-media-python/master/LICENSE
google.golang.org_api;https://raw.githubusercontent.com/googleapis/google-api-go-client/master/LICENSE
google.golang.org_appengine;https://raw.githubusercontent.com/golang/appengine/master/LICENSE
google.golang.org_genproto;https://raw.githubusercontent.com/googleapis/go-genproto/master/LICENSE
google.golang.org_genproto/googleapis/api;https://raw.githubusercontent.com/googleapis/go-genproto/master/LICENSE
google.golang.org_genproto/googleapis/rpc;https://raw.githubusercontent.com/googleapis/go-genproto/master/LICENSE
google.golang.org_grpc;https://raw.githubusercontent.com/grpc/grpc-go/master/LICENSE
google.golang.org_protobuf;https://go.googlesource.com/protobuf
googleapis_common-protos;https://raw.githubusercontent.com/googleapis/python-api-common-protos/master/LICENSE
gopkg.in_inf.v0;https://gopkg.in/inf.v0
gopkg.in_ini.v1;https://gopkg.in/ini.v1
gopkg.in_natefinch/lumberjack.v2;https://gopkg.in/natefinch/lumberjack.v2
gopkg.in_warnings.v0;https://gopkg.in/warnings.v0
gopkg.in_yaml.v2;https://gopkg.in/yaml.v2
gopkg.in_yaml.v3;https://gopkg.in/yaml.v3
grpcio;https://raw.githubusercontent.com/grpc/grpc/master/LICENSE
gson;https://raw.githubusercontent.com/google/gson/master/LICENSE
guava;https://raw.githubusercontent.com/google/guava/master/LICENSE
hk2_api;https://github.com/eclipse-ee4j/glassfish-hk2
hk2_locator;https://github.com/eclipse-ee4j/glassfish-hk2
hk2_utils;https://github.com/eclipse-ee4j/glassfish-hk2
httpbin;https://raw.githubusercontent.com/requests/httpbin/master/LICENSE
httplib2;https://github.com/httplib2/httplib2
idna;https://raw.githubusercontent.com/kjd/idna/master/LICENSE.md
importlib_metadata;https://raw.githubusercontent.com/python/importlib_metadata/master/LICENSE
jackson_annotations;http://github.com/FasterXML/jackson-annotations
jackson_core;http://github.com/FasterXML/jackson-core
jackson_databind;http://github.com/FasterXML/jackson-databind
jackson_dataformat-csv;http://github.com/FasterXML/jackson-dataformats-text
jackson_datatype-jdk8;http://github.com/FasterXML/jackson-modules-java8
jackson_jaxrs-base;http://github.com/FasterXML/jackson-jaxrs-providers
jackson_jaxrs-json-provider;http://github.com/FasterXML/jackson-jaxrs-providers
jackson_module-jaxb-annotations;http://github.com/FasterXML/jackson-modules-base
jakarta.activation_api;https://github.com/eclipse-ee4j/jaf
jakarta.annotation_api;https://github.com/eclipse-ee4j/common-annotations-api
jakarta.inject;https://github.com/eclipse-ee4j/glassfish-hk2
jakarta.validation_api;https://github.com/eclipse-ee4j/beanvalidation-api
jakarta.ws.rs_api;https://github.com/eclipse-ee4j/jaxrs-api
jakarta.xml.bind_api;https://github.com/eclipse-ee4j/jaxb-api.git
jaraco_classes;https://github.com/jaraco/jaraco.classes
javassist;scm:git:https://github.com/jboss-javassist/javassist
javax.activation_api;https://github.com/javaee/activation
javax.annotation_api;https://github.com/javaee/javax.annotation
javax.servlet_api;http://java.net/projects/glassfish/sources/svn/show/tags/javax.servlet-api-3.1.0
javax.ws.rs_api;https://github.com/eclipse-ee4j/jaxrs-api
jaxb_api;https://github.com/javaee/jaxb-spec.git
jcl_over-slf4j;https://github.com/qos-ch/slf4j
jctools_core;https://raw.githubusercontent.com/JCTools/JCTools/master/LICENSE
jeepney;https://gitlab.com/takluyver/jeepney
jersey_client;https://github.com/eclipse-ee4j/jersey
jersey_common;https://github.com/eclipse-ee4j/jersey
jersey_container-servlet;https://github.com/eclipse-ee4j/jersey
jersey_container-servlet-core;https://github.com/eclipse-ee4j/jersey
jersey_hk2;https://github.com/eclipse-ee4j/jersey
jersey_server;https://github.com/eclipse-ee4j/jersey
jetty_client;https://github.com/eclipse/jetty.project
jetty_continuation;https://github.com/eclipse/jetty.project
jetty_http;https://github.com/eclipse/jetty.project
jetty_io;https://github.com/eclipse/jetty.project
jetty_security;https://github.com/eclipse/jetty.project
jetty_server;https://github.com/eclipse/jetty.project
jetty_servlet;https://github.com/jetty/jetty.project
jetty_servlets;https://github.com/eclipse/jetty.project
jetty_util;https://github.com/jetty/jetty.project
jetty_util-ajax;https://github.com/eclipse/jetty.project
jinja2;https://raw.githubusercontent.com/pallets/jinja/master/LICENSE.rst
jline;https://github.com/jline/jline
jline;http://github.com/jline/jline3
jline_builtins;http://github.com/jline/jline3
jline_reader;http://github.com/jline/jline3
jline_remote-ssh;http://github.com/jline/jline3
jline_remote-telnet;http://github.com/jline/jline3
jline_style;http://github.com/jline/jline3
jline_terminal;http://github.com/jline/jline3
jline_terminal-jansi;http://github.com/jline/jline3
jline_terminal-jna;http://github.com/jline/jline3
jopt_simple;https://github.com/jopt-simple/jopt-simple
jose4j;https://bitbucket.org/b_c/jose4j
jrt_fs;https://raw.githubusercontent.com/AdoptOpenJDK/openjdk-jdk11/master/LICENSE
jsr305;https://code.google.com/p/jsr-305/
jul_to-slf4j;https://github.com/qos-ch/slf4j
k8s.io_api;https://raw.githubusercontent.com/kubernetes/api/master/LICENSE
k8s.io_apiextensions_apiserver;https://raw.githubusercontent.com/kubernetes/apiextensions-apiserver/master/LICENSE
k8s.io_apimachinery;https://raw.githubusercontent.com/kubernetes/apimachinery/master/LICENSE
k8s.io_cli_runtime;https://raw.githubusercontent.com/kubernetes/cli-runtime/master/LICENSE
k8s.io_client_go;https://raw.githubusercontent.com/kubernetes/client-go/master/LICENSE
k8s.io_component_base;https://raw.githubusercontent.com/kubernetes/component-base/master/LICENSE
k8s.io_klog/v2;https://raw.githubusercontent.com/kubernetes/klog/master/LICENSE
k8s.io_kube_openapi;https://raw.githubusercontent.com/kubernetes/kube-openapi/master/LICENSE
k8s.io_kubectl;https://raw.githubusercontent.com/kubernetes/kubectl/master/LICENSE
k8s.io_utils;https://raw.githubusercontent.com/kubernetes/utils/master/LICENSE
kafka_clients;https://raw.githubusercontent.com/apache/kafka/trunk/LICENSE
kafka_group-coordinator;https://raw.githubusercontent.com/apache/kafka/trunk/LICENSE
kafka_log4j-appender;https://raw.githubusercontent.com/apache/kafka/trunk/LICENSE
kafka_metadata;https://raw.githubusercontent.com/apache/kafka/trunk/LICENSE
kafka_raft;https://raw.githubusercontent.com/apache/kafka/trunk/LICENSE
kafka_server-common;https://raw.githubusercontent.com/apache/kafka/trunk/LICENSE
kafka_shell;https://raw.githubusercontent.com/apache/kafka/trunk/LICENSE
kafka_storage;https://raw.githubusercontent.com/apache/kafka/trunk/LICENSE
kafka_storage-api;https://raw.githubusercontent.com/apache/kafka/trunk/LICENSE
kafka_streams;https://raw.githubusercontent.com/apache/kafka/trunk/LICENSE
kafka_streams-examples;https://raw.githubusercontent.com/apache/kafka/trunk/LICENSE
kafka_streams-test-utils;https://raw.githubusercontent.com/apache/kafka/trunk/LICENSE
kafka_tools;https://raw.githubusercontent.com/apache/kafka/trunk/LICENSE
kafka_tools-api;https://raw.githubusercontent.com/apache/kafka/trunk/LICENSE
keyring;https://raw.githubusercontent.com/jaraco/keyring/master/LICENSE
libintl;https://mvnrepository.com/artifact/org.gnu.gettext/libintl/0.18.3
log4j;https://github.com/qos-ch/slf4j/blob/master/LICENSE.txt
log4j_over-slf4j;https://github.com/qos-ch/slf4j
lz4_java;https://raw.githubusercontent.com/lz4/lz4-java/master/LICENSE.txt
markupsafe;https://raw.githubusercontent.com/pallets/markupsafe/master/LICENSE.rst
maven_artifact;https://maven.apache.org/ref/${project.version}/
metrics_core;http://github.com/codahale/metrics/
metrics_core;https://raw.githubusercontent.com/dropwizard/metrics/master/LICENSE
mock;https://github.com/testing-cabal/mock
mock;https://raw.githubusercontent.com/uber/mock/master/LICENSE
modernc.org_libc;https://gitlab.com/cznic/libc
modernc.org_mathutil;https://gitlab.com/cznic/mathutil
modernc.org_memory;https://gitlab.com/cznic/memory
modernc.org_sqlite;https://gitlab.com/cznic/sqlite
more_itertools;https://raw.githubusercontent.com/more-itertools/more-itertools/master/LICENSE
mypy;https://raw.githubusercontent.com/python/mypy/master/LICENSE
netty_buffer;https://github.com/netty/netty
netty_codec;https://github.com/netty/netty
netty_common;https://github.com/netty/netty
netty_handler;https://github.com/netty/netty
netty_resolver;https://github.com/netty/netty
netty_transport;https://github.com/netty/netty
netty_transport-classes-epoll;https://github.com/netty/netty
netty_transport-native-epoll;https://raw.githubusercontent.com/netty/netty/4.1/LICENSE.txt
netty_transport-native-unix-common;https://raw.githubusercontent.com/netty/netty/4.1/LICENSE.txt
nox;https://raw.githubusercontent.com/wntrblm/nox/master/LICENSE
opentelemetry_java-contrib-jmx-metrics;https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/LICENSE
osgi_resource-locator;https://github.com/eclipse-ee4j/glassfish-hk2-extra
packaging;https://raw.githubusercontent.com/pypa/packaging/master/LICENSE
paranamer;https://github.com/paul-hammant/paranamer
pcollections;https://raw.githubusercontent.com/hrldcpr/pcollections/master/LICENSE
peter_evans_create-pull-request;https://github.com/peter-evans/create-pull-request/blob/main/LICENSE
pip;https://github.com/pypa/pip
platformdirs;https://raw.githubusercontent.com/platformdirs/platformdirs/master/LICENSE
plexus_utils;http://github.com/codehaus-plexus/plexus-utils
pre_commit_action;https://github.com/pre-commit/action/blob/main/LICENSE
protobuf;https://raw.githubusercontent.com/golang/protobuf/master/LICENSE
pyOpenSSL;https://raw.githubusercontent.com/pyca/pyopenssl/master/LICENSE
pyasn1;https://github.com/etingof/pyasn1
pyasn1_modules;https://github.com/etingof/pyasn1-modules
pycparser;https://raw.githubusercontent.com/eliben/pycparser/master/LICENSE
pycurl;https://github.com/pycurl/pycurl/blob/master/COPYING-MIT
pygments;https://raw.githubusercontent.com/pygments/pygments/master/LICENSE
pyjwt;https://raw.githubusercontent.com/jpadilla/pyjwt/master/LICENSE
pyopenssl;https://raw.githubusercontent.com/pyca/pyopenssl/master/LICENSE
pypa_gh_action-pypi-publish;https://github.com/pypa/gh-action-pypi-publish/blob/unstable/v1/LICENSE.md
pyparsing;https://raw.githubusercontent.com/pyparsing/pyparsing/master/LICENSE
pyperclip;https://github.com/asweigart/pyperclip
pytest;https://raw.githubusercontent.com/pytest-dev/pytest/master/LICENSE
pytest_cov;https://raw.githubusercontent.com/pytest-dev/pytest-cov/master/LICENSE
pytest_forked;https://raw.githubusercontent.com/pytest-dev/pytest-forked/master/LICENSE
pytest_freezegun;https://raw.githubusercontent.com/ktosiek/pytest-freezegun/master/LICENSE
pytest_httpbin;https://github.com/kevin1024/pytest-httpbin
pytest_mock;https://raw.githubusercontent.com/pytest-dev/pytest-mock/master/LICENSE
pytest_randomly;https://raw.githubusercontent.com/adamchainz/pytest-randomly/master/LICENSE
pytest_timeout;http://github.com/pytest-dev/pytest-timeout
pytest_xdist;https://raw.githubusercontent.com/pytest-dev/pytest-xdist/master/LICENSE
python;https://raw.githubusercontent.com/rthalley/dnspython/master/LICENSE
python_apt;https://github.com/excid3/python-apt/blob/master/COPYING.GPL
python_dateutil;https://raw.githubusercontent.com/dateutil/dateutil/master/LICENSE
python_debian;https://raw.githubusercontent.com/venthur/python-debianbts/master/LICENSE
python_debianbts;https://raw.githubusercontent.com/venthur/python-debianbts/master/LICENSE
readme_renderer;https://raw.githubusercontent.com/pypa/readme_renderer/master/LICENSE
reflections;https://github.com/ronmamo/reflections/issues
reload4j;https://github.com/qos-ch/reload4j
reportbug;https://github.com/venthur/reportbug-ng/blob/master/LICENSE
requests;https://raw.githubusercontent.com/psf/requests/master/LICENSE
requests_toolbelt;https://raw.githubusercontent.com/requests/toolbelt/master/LICENSE
rfc3986;https://raw.githubusercontent.com/python-hyper/rfc3986/main/LICENSE
rich;https://raw.githubusercontent.com/willmcgugan/rich/master/LICENSE
rocksdbjni;https://raw.githubusercontent.com/fusesource/rocksdbjni/master/license.txt
rsa;https://raw.githubusercontent.com/go-playground/universal-translator/master/LICENSE
rsa;https://raw.githubusercontent.com/sybrenstuvel/python-rsa/master/LICENSE
scala_library;https://raw.githubusercontent.com/scala/scala/2.13.x/LICENSE
scala_reflect;https://raw.githubusercontent.com/scala/scala/2.13.x/LICENSE
secretstorage;https://github.com/mitya57/secretstorage
setuptools;https://raw.githubusercontent.com/pypa/setuptools/master/LICENSE
sigs.k8s.io_cli_utils;https://raw.githubusercontent.com/kubernetes-sigs/cli-utils/master/LICENSE
sigs.k8s.io_controller_runtime;https://raw.githubusercontent.com/kubernetes-sigs/controller-runtime/master/LICENSE
sigs.k8s.io_json;https://raw.githubusercontent.com/kubernetes-sigs/json/master/LICENSE
sigs.k8s.io_kustomize/api;https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/LICENSE
sigs.k8s.io_kustomize/kyaml;https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/LICENSE
sigs.k8s.io_structured_merge-diff/v4;https://raw.githubusercontent.com/kubernetes-sigs/structured-merge-diff/master/LICENSE
sigs.k8s.io_yaml;https://raw.githubusercontent.com/kubernetes-sigs/yaml/master/LICENSE
simpleclient;https://github.com/prometheus/client_java
simpleclient_common;https://github.com/prometheus/client_java
simpleclient_httpserver;https://github.com/prometheus/client_java
simpleclient_tracer_common;https://github.com/prometheus/client_java
simpleclient_tracer_otel;https://github.com/prometheus/client_java
simpleclient_tracer_otel_agent;https://github.com/prometheus/client_java
simplejson;http://github.com/simplejson/simplejson
six;https://raw.githubusercontent.com/benjaminp/six/master/LICENSE
slf4j_api;https://github.com/qos-ch/slf4j
slf4j_jcl;https://github.com/qos-ch/slf4j
slf4j_jdk14;https://github.com/qos-ch/slf4j
slf4j_log4j12;https://github.com/qos-ch/slf4j
slf4j_migrator;https://github.com/qos-ch/slf4j
slf4j_nop;https://github.com/qos-ch/slf4j
slf4j_reload4j;https://github.com/qos-ch/slf4j
slf4j_simple;https://github.com/qos-ch/slf4j
snappy_java;https://raw.githubusercontent.com/xerial/snappy-java/master/LICENSE
stdlib;https://pkg.go.dev/github.com/radisvaliullin/test-golang/stdlib?tab=licenses
swagger_annotations;https://raw.githubusercontent.com/swagger-api/swagger-core/master/LICENSE
tornado;https://raw.githubusercontent.com/tornadoweb/tornado/master/LICENSE
tox;https://raw.githubusercontent.com/FasterXML/woodstox/master/LICENSE
trogdor;https://raw.githubusercontent.com/apache/kafka/trunk/LICENSE
trustme;https://raw.githubusercontent.com/python-trio/trustme/master/LICENSE
twine;https://raw.githubusercontent.com/pypa/twine/master/LICENSE
typing_extensions;https://raw.githubusercontent.com/python/typing_extensions/master/LICENSE
unattended_upgrades;https://github.com/mvo5/unattended-upgrades/blob/master/COPYING
urllib3;https://github.com/urllib3/urllib3
virtualenv;https://raw.githubusercontent.com/pypa/virtualenv/master/LICENSE
webencodings;https://raw.githubusercontent.com/SimonSapin/python-webencodings/master/LICENSE
wheel;https://github.com/pypa/wheel
win_inet-pton;https://raw.githubusercontent.com/hickeroar/win_inet_pton/master/LICENSE
wrapt;https://raw.githubusercontent.com/GrahamDumpleton/wrapt/master/LICENSE
xercesImpl;https://github.com/codelibs/xerces/blob/master/LICENSE
xercesSamples;https://github.com/Starlink/xerces/blob/master/LICENSE
zipp;https://raw.githubusercontent.com/jaraco/zipp/master/LICENSE
zookeeper;https://raw.githubusercontent.com/go-zookeeper/zk/master/LICENSE
zookeeper;https://gitbox.apache.org/repos/asf/zookeeper.git
zookeeper_jute;https://gitbox.apache.org/repos/asf/zookeeper.git
zstd_jni;https://github.com/luben/zstd-jni/blob/master/LICENSE

EOF
end
