#!/bin/bash -eu
#
# Copyright 2021 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/c2d-utils || exit 1

#######################################
# Awaits for website at localhost be ready.
#######################################
function wait_for_app() {
  local max_retries=10
  local retry=1
  local http_code=0
  local host_ip=""

  # Prevent exit on error in case of request max-time reached.
  set +e

  echo "Checking for app readiness..."

  while [[ "${http_code}" -ne 200 && "${retry}" -le "${max_retries}" ]]; do
    echo "Retry: ${retry}"
    http_code="$(curl --max-time 5 -s -L -o /dev/null -w "%{http_code}" http://localhost)"
    echo "Http Code: ${http_code}"
    (( retry=retry+1 ))

    if [[ "${http_code}" -ne 200 ]]; then
      systemctl restart apache2
      sleep 30
    fi
  done

  if [[ "${retry}" -gt "${max_retries}" ]]; then
    echo "Max retries exceeded."
    exit 1
  else
    echo "App is ready."
  fi

  set -e
}

# Magento cache, var, media permission setup

cd /var/www/html
mkdir -p var
mkdir -p media
mkdir -p includes

# We set directories permissions to 700, and files to 600 to ensure the running
# PHP code can upload content, write to cache, or rewrite it's own config file

find var/ -type f -exec chmod 600 {} \;
find media/ -type f -exec chmod 600 {} \;
find var/ -type d -exec chmod 700 {} \;
find media/ -type d -exec chmod 700 {} \;
chmod 700 includes

# Magento cron and cache setup

php /var/www/html/bin/magento indexer:reindex
php /var/www/html/bin/magento cache:clean
php /var/www/html/bin/magento cache:flush

# The below command is needed because its important to allow magento to edit its
# own config files or write cache. When we execute bin/magento files are created
# as root as that is what the configuration script is running as. The below
# command ensures all files in var are owned by the user and group www-data.

chown -R www-data:www-data var/

wait_for_app

# Reconfigure correct base_url
declare base_url=""
if has_external_ip; then
  base_url="http://$(get_external_ip)/"
else
  base_url="http://$(get_internal_ip)/"
fi

php /var/www/html/bin/magento setup:store-config:set --base-url="${base_url}"
php /var/www/html/bin/magento cache:flush
