#!/bin/bash -eu
#
# Copyright 2021 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/c2d-utils || exit 1

declare -r redis_host="localhost"
declare -r redis_port="6379"
declare -r redis_password="$(get_attribute_value "redis-password")"

declare -a args=()
args+=(
  --base-url="http://localhost" \
  --admin-firstname="owner" \
  --admin-lastname="owner" \
  --admin-email="owner@example.com" \
  --admin-user="admin" \
  --admin-password=$(get_attribute_value "magento-admin-password") \
  --db-host="localhost" \
  --db-name="magento2" \
  --db-user="magento" \
  --db-password=$(get_attribute_value "magento-db-password") \
  --search-engine="elasticsearch7" \
  --elasticsearch-host="localhost" \
  --elasticsearch-port="9200" \
  --session-save redis \
  --session-save-redis-host "${redis_host}" \
  --session-save-redis-port "${redis_port}" \
  --session-save-redis-password "${redis_password}" \
  --session-save-redis-persistent-id sess-db0 \
  --session-save-redis-db 2 \
  --cache-backend redis \
  --cache-backend-redis-server "${redis_host}" \
  --cache-backend-redis-db 0 \
  --cache-backend-redis-port "${redis_port}" \
  --cache-backend-redis-password "${redis_password}" \
  --page-cache redis \
  --page-cache-redis-server "${redis_host}" \
  --page-cache-redis-db 1 \
  --page-cache-redis-port "${redis_port}" \
  --page-cache-redis-password "${redis_password}" \
  --backend-frontname="admin" ) #MAGENTO ADMIN URL

php /var/www/html/bin/magento setup:install "${args[@]}"

php /var/www/html/bin/magento setup:upgrade

php /var/www/html/bin/magento setup:di:compile

php /var/www/html/bin/magento cache:flush
