#!/bin/bash -eu
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/c2d-utils || exit 1

declare -a args=()
args+=( --admin-firstname="owner" \
  --admin-lastname="owner" \
  --admin-email="owner@example.com" \
  --admin-user="admin" \
  --admin-password=$(get_attribute_value "magento-admin-password") \
  --db-host="localhost" \
  --db-name="magento" \
  --db-user="magento" \
  --db-password=$(get_attribute_value "magento-db-password") \
  --backend-frontname="admin" ) #MAGENTO ADMIN URL

if has_external_ip; then
  args+=( --base-url=http://"$(get_external_ip)")
else
  args+=( --base-url=http://"$(get_internal_ip)")
fi

php /var/www/html/bin/magento setup:install "${args[@]}"
