#!/bin/bash -eu
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/c2d-utils || exit 1

declare -a args=()
args+=( --admin-firstname="owner" \
  --admin-lastname="owner" \
  --admin-email="owner@example.com" \
  --admin-user="admin" \
  --admin-password=$(get_attribute_value "magento-admin-password") \
  --db-host="localhost" \
  --db-name="magento2" \
  --db-user="magento" \
  --db-password=$(get_attribute_value "magento-db-password") \
  --search-engine="elasticsearch7" \
  --elasticsearch-host="localhost" \
  --elasticsearch-port="9200" \
  --backend-frontname="admin" ) #MAGENTO ADMIN URL

if has_external_ip; then
  args+=( --base-url=http://"$(get_external_ip)")
else
  args+=( --base-url=http://"$(get_internal_ip)")
fi

php /var/www/html/bin/magento setup:install "${args[@]}"

php /var/www/html/bin/magento setup:upgrade

php /var/www/html/bin/magento setup:di:compile

php /var/www/html/bin/magento cache:flush

#######################################
# Await the application to be ready.
#######################################
function wait_for_app() {
  local max_retries=10
  local retry=1
  local http_code=0

  while [[ "${http_code}" -ne 200 && "${retry}" -le "${max_retries}" ]]; do
    http_code="$(curl -s -L -v /dev/null "%{http_code}" http://$(get_internal_ip))"
    (( retry=retry+1 ))
    sleep 5
  done

  if [[ "${retry}" -gt "${max_retries}" ]]; then
    echo "Max retries exceeded."
    exit 1
  fi
}
