# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


cloudbuild:
  docker_image: gcr.io/cloud-builders/docker@sha256:1a9553236b25fd6e1bf2a864c8becb26782c429f4570695b27f4ad6f1a0ed75e
  enable_parallel: false
versions:
- annotations:
  - key: com.googleapis.cloudmarketplace.product.service.name
    value: services/8be1fafd-f0c6-4770-b23e-bce06be7b750.cloudpartnerservices.goog
  dir: 3/debian12/3.6
  from: marketplace.gcr.io/google/debian12@sha256:c2a5eb3516da4c3bb0cf2d6fea739bd7b2dc7b1ac444b5fbd7c4def2aa57d4a0
  packages:
    etcd:
      sha256: ffe840ff9295808e88cce2794a18a5ac87f12a5203c8314d0bf6aa119b41bac5
      version: 3.6.14
    golang:
      version: 1.25.9
  templateArgs:
    c2dRelease: 3.6.14
  repo: etcd3
  tags:
  - 3.6.14-debian12
  - 3.6-debian12
  - 3-debian12
  - 3.6.14
  - '3.6'
  - '3'
  - latest
  allowlist:
  - marketplace.gcr.io
  - deb.debian.org
  - dl.google.com/go/
- annotations:
  - key: com.googleapis.cloudmarketplace.product.service.name
    value: services/8be1fafd-f0c6-4770-b23e-bce06be7b750.cloudpartnerservices.goog
  dir: 3/debian12/3.5
  from: marketplace.gcr.io/google/debian12@sha256:c2a5eb3516da4c3bb0cf2d6fea739bd7b2dc7b1ac444b5fbd7c4def2aa57d4a0
  packages:
    etcd:
      sha256: 5025b5b24d81a9616b6e284ccd439b9a3df055ef8fdcdc142af3ec8f6a3b3c95
      version: 3.5.33
    golang:
      version: 1.25.9
  templateArgs:
    c2dRelease: 3.5.33
  repo: etcd3
  tags:
  - 3.5.33-debian12
  - 3.5-debian12
  - 3.5.33
  - '3.5'
  allowlist:
  - marketplace.gcr.io
  - deb.debian.org
  - dl.google.com/go/
