#!/bin/bash -eu
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/c2d-utils || exit 1

readonly installphpMyAdmin="$(get_attribute_value "installphpmyadmin" \
  | tr '[:upper:]' '[:lower:]')"

if [[ "${installphpMyAdmin:-}" == "true" ]]; then
  echo "phpMyAdmin has been selected to be installed."
  setup_folder="/opt/c2d/downloads/phpmyadmin"

  # Set up blowfish_secret parameter
  secret="$(openssl rand -base64 32 | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]' | fold -w 32 | head -n 1 | tr -d '\r\n')"
  cat "${setup_folder}/config.sample.inc.php" \
    | sed "s/\['blowfish_secret'\] = ''; /\['blowfish_secret'\] = '$secret'; /g" \
    > "${setup_folder}/config.inc.php"

  # Grant permission on tmp folder
  mkdir -p "${setup_folder}/tmp/" \
    && chown -R www-data:www-data "${setup_folder}/tmp/"

  # Configure phpMyAdmin website
  ln -s "${setup_folder}/" /var/www/html/phpmyadmin

  # Restart apache2 in order to apply PHP changes
  systemctl restart apache2

  echo "phpMyAdmin configured."
elif [[ "${installphpMyAdmin:-}" == "false" ]]; then
  echo "phpMyAdmin not selected for install."
  rm -rf /opt/c2d/downloads/phpmyadmin
fi
