{{- $spark := index .Packages "spark" -}}
{{- $scala := index .Packages "scala" -}}

FROM {{ .From }}

ENV C2D_RELEASE {{ $spark.Version }}

# Add Java JDK
RUN apt-get update \
  && apt-get install -y \
    openjdk-17-jdk

# Add Dependencies for PySpark and Spark
RUN apt-get install -y \
    ca-certificates \
    curl \
    software-properties-common \
    ssh \
    net-tools \
    python3 \
    python3-pip \
    python3-numpy \
    python3-matplotlib \
    python3-scipy \
    python3-pandas \
    python3-sympy \
    supervisor \
    vim \
    wget

RUN update-alternatives --install "/usr/bin/python" "python" "$(which python3)" 1

# Fix the value of PYTHONHASHSEED
# Note: this is needed when you use Python 3.3 or greater
ENV SPARK_VERSION={{ $spark.Version }}
ENV SCALA_VERSION={{ $scala.Minor }}
ENV SPARK_HOME=/opt/spark
ENV PYTHONHASHSEED=1

# Download and uncompress spark from the apache archive
RUN curl -L -o apache-spark.tgz "https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop3-scala${SCALA_VERSION}.tgz" \
      && mkdir -p /opt/spark \
      && tar -xf apache-spark.tgz -C /opt/spark --strip-components=1 \
      && rm -f apache-spark.tgz

WORKDIR /opt/spark

ENV SPARK_MASTER_PORT=7077
ENV SPARK_MASTER_WEBUI_PORT=8080
ENV SPARK_LOG_DIR=/opt/spark/logs
ENV SPARK_MASTER_LOG=/opt/spark/logs/spark-master.out
ENV SPARK_WORKER_LOG=/opt/spark/logs/spark-worker.out
ENV SPARK_WORKER_WEBUI_PORT=8080
ENV SPARK_WORKER_PORT=7000
ENV SPARK_MASTER="spark://spark-master:7077"
ENV SPARK_WORKLOAD="master"

EXPOSE 8080 7077 6066

RUN mkdir -p $SPARK_LOG_DIR \
      && touch $SPARK_MASTER_LOG \
      && touch $SPARK_WORKER_LOG \
      && ln -sf /dev/stdout $SPARK_MASTER_LOG \
      && ln -sf /dev/stdout $SPARK_WORKER_LOG

COPY start-spark.sh /
COPY metrics.properties /opt/spark/conf/metrics.properties
COPY test_job.py /opt/spark-apps/test_job.py
COPY supervisor.conf /etc/supervisor/conf.d/supervisor.conf

# Patch zookeeper as per CVE-2023-44981
RUN rm -f /opt/spark/jars/zookeeper-*.jar \
  && curl -s -L -o /tmp/zookeeper.tar.gz https://dlcdn.apache.org/zookeeper/zookeeper-3.8.4/apache-zookeeper-3.8.4-bin.tar.gz \
  && mkdir -p /tmp/zookeeper/  \
  && tar -zxf /tmp/zookeeper.tar.gz -C /tmp/zookeeper --strip-components=1  \
  && cp /tmp/zookeeper/lib/zookeeper-*.jar /opt/spark/jars/  \
  && rm -rf /tmp/zookeeper  \
  && rm -f /tmp/zookeeper.tar.gz

WORKDIR /opt/spark

ENTRYPOINT [ "/start-spark.sh" ]
