# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ospo_download 'Licenses and Source-code' do
  ref_repos <<-EOF
https://github.com/pysimplesoap/pysimplesoap
https://github.com/AndrewSpangler/py_simple_launcher
http://github.com/neithere/argh
https://github.com/certifi/python-certifi
https://github.com/chardet/chardet
https://github.com/timotheus/ebaysdk-python
https://github.com/anchore/go-version
https://github.com/go-sql-driver
https://github.com/hashicorp/consul
https://github.com/hashicorp/errwrap
https://github.com/hashicorp/go-checkpoint
https://github.com/hashicorp/go-cleanhttp
https://github.com/hashicorp/go-immutable-radix
https://github.com/hashicorp/go-multierror
https://github.com/hashicorp/go-plugin
https://github.com/hashicorp/go-retryablehttp
https://github.com/hashicorp/go-rootcerts
https://github.com/hashicorp/go-uuid
https://github.com/hashicorp/go-version
https://github.com/hashicorp/golang-lru
https://github.com/hashicorp/hc-install
https://github.com/hashicorp/hcl
https://github.com/hashicorp/logutils
https://github.com/hashicorp/nomad
https://github.com/hashicorp/serf
https://github.com/hashicorp/terraform-exec
https://github.com/hashicorp/terraform-json
https://github.com/hashicorp/terraform-plugin-go
https://github.com/hashicorp/terraform-plugin-log
https://github.com/hashicorp/terraform-plugin-sdk
https://github.com/hashicorp/terraform-registry-address
https://github.com/hashicorp/terraform-svchost
https://github.com/hashicorp/yamux
https://mvnrepository.com/artifact/org.gnu.gettext/libintl/0.18.3
https://github.com/savoirfairelinux/num2words
https://github.com/odoo/odoo
https://github.com/psycopg/psycopg2
https://github.com/excid3/python-apt
https://github.com/venthur/python-debianbts
https://github.com/arthurdejong/python-stdnum
https://github.com/mvo5/unattended-upgrades

EOF
  licenses <<-EOF
Babel;https://raw.githubusercontent.com/babel/babel/master/LICENSE
Jinja2;https://raw.githubusercontent.com/pallets/jinja/master/LICENSE.rst
MarkupSafe;https://raw.githubusercontent.com/pallets/markupsafe/master/LICENSE.rst
Pillow;https://raw.githubusercontent.com/python-pillow/Pillow/master/LICENSE
PyPDF2;https://github.com/talumbau/PyPDF2/blob/master/LICENSE
PySimpleSOAP;https://github.com/pysimplesoap/pysimplesoap
PySocks;https://raw.githubusercontent.com/Anorov/PySocks/master/LICENSE
PyYAML;https://raw.githubusercontent.com/yaml/pyyaml/master/LICENSE
SimpleLauncherExecutable;https://github.com/AndrewSpangler/py_simple_launcher/blob/main/LICENSE
Sphinx;https://raw.githubusercontent.com/sphinx-doc/sphinx/master/LICENSE.rst
Werkzeug;https://github.com/pallets/werkzeug
XlsxWriter;https://github.com/jmcnamara/XlsxWriter
actions_cache;https://github.com/actions/cache/blob/main/LICENSE
actions_checkout;https://github.com/actions/checkout/blob/main/LICENSE
actions_download_artifact;https://github.com/actions/download-artifact/blob/main/LICENSE
actions_setup_python;https://github.com/actions/setup-python/blob/main/LICENSE
actions_upload_artifact;https://github.com/actions/upload-artifact/blob/main/LICENSE
animal_sniffer_annotations;https://raw.githubusercontent.com/mojohaus/animal-sniffer/master/LICENSE
annotations;https://github.com/JetBrains/intellij-community
annotations;https://android.git.kernel.org/
anthoscli;https://github.com/GoogleCloudPlatform/cloud-sdk-docker/blob/master/LICENSE
appdirs;http://github.com/ActiveState/appdirs
argcomplete;https://raw.githubusercontent.com/kislyuk/argcomplete/master/LICENSE.rst
argh;http://github.com/neithere/argh
argparse;https://github.com/nodeca/argparse
attrs;https://raw.githubusercontent.com/python-attrs/attrs/master/LICENSE
base58;https://github.com/keis/base58
bash;git+https://github.com/streetsidesoftware/cspell-dicts.git
beautifulsoup4;https://www.crummy.com/software/BeautifulSoup/bs4/
bitbucket.org_creachadair_stringset;https://bitbucket.org/creachadair/stringset
black;https://raw.githubusercontent.com/psf/black/master/LICENSE
bleach;https://raw.githubusercontent.com/mozilla/bleach/master/LICENSE
cached_property;https://raw.githubusercontent.com/pydanny/cached-property/master/LICENSE
cachetools;https://raw.githubusercontent.com/tkem/cachetools/master/LICENSE
certifi;https://raw.githubusercontent.com/certifi/python-certifi/master/LICENSE
cffi;https://raw.githubusercontent.com/python-cffi/cffi/master/LICENSE
chardet;https://raw.githubusercontent.com/chardet/chardet/master/LICENSE
charset_normalizer;https://raw.githubusercontent.com/ousret/charset_normalizer/master/LICENSE
click;https://raw.githubusercontent.com/pallets/click/master/LICENSE.rst
cloud.google.com_go;https://raw.githubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_bigtable;https://raw.githubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_compute_metadata;https://raw.githubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_iam;https://raw.githubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_logging;https://raw.githubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_longrunning;https://raw.githubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_monitoring;https://raw.githubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_osconfig;https://raw.githubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_storage;https://raw.githubusercontent.com/googleapis/google-cloud-go/master/LICENSE
cloud.google.com_go_trace;https://raw.githubusercontent.com/googleapis/google-cloud-go/master/LICENSE
codecov_codecov_action;https://github.com/codecov/codecov-action/blob/main/LICENSE
colorlog;https://raw.githubusercontent.com/borntyping/python-colorlog/master/LICENSE
commonmark;https://github.com/rtfd/commonmark.py
contrib.go.opencensus.io_exporter_prometheus;https://raw.githubusercontent.com/census-ecosystem/opencensus-go-exporter-prometheus/master/LICENSE
cos.googlesource.com_cos_tools.git;https://cos.googlesource.com/cos/tools
coverage;https://bitbucket.org/ned/coveragepy
crcmod;https://github.com/gsutil-mirrors/crcmod/blob/master/LICENSE
cryptography;https://raw.githubusercontent.com/pyca/cryptography/master/LICENSE
dario.cat_mergo;https://raw.githubusercontent.com/imdario/mergo/master/LICENSE
dbus_python;https://github.com/posborne/dbus-python/blob/master/COPYING
decorator;https://github.com/micheles/decorator
defusedxml;https://raw.githubusercontent.com/tiran/defusedxml/master/LICENSE
dessant_lock_threads;https://github.com/dessant/lock-threads/blob/main/LICENSE
distlib;https://github.com/pypa/distlib
distro_info;https://github.com/softwarefactory-project/distroinfo/blob/master/LICENSE
docopt;https://github.com/docopt/docopt/blob/master/LICENSE-MIT
docutils;https://raw.githubusercontent.com/docutils/docutils/master/docutils/licenses/BSD-2-Clause.txt
ebaysdk;https://github.com/timotheus/ebaysdk-python/blob/master/LICENSE
error_prone_annotations;https://github.com/google/error-prone
failureaccess;https://raw.githubusercontent.com/google/guava/master/LICENSE
filelock;https://raw.githubusercontent.com/tox-dev/py-filelock/master/LICENSE
flake8;https://gitlab.com/pycqa/flake8
flake8;https://github.com/pycqa/flake8
flaky;https://raw.githubusercontent.com/box/flaky/master/LICENSE
freezegun;https://raw.githubusercontent.com/spulec/freezegun/master/LICENSE
future;https://raw.githubusercontent.com/google/guava/master/LICENSE
gcp_devrel_py_tools;https://raw.githubusercontent.com/GoogleCloudPlatform/python-repo-tools/master/LICENSE
gcp_docuploader;https://github.com/googleapis/docuploader/blob/main/LICENSE
gcp_releasetool;https://github.com/googleapis/releasetool/blob/master/LICENSE
gevent;https://raw.githubusercontent.com/gevent/gevent/master/LICENSE
github.com_99designs_keyring;https://github.com/99designs/keyring
github.com_Azure_azure_sdk_for_go;https://github.com/azure/azure-sdk-for-go
github.com_Azure_azure_sdk_for_go_sdk_azcore;https://github.com/azure/azure-sdk-for-go
github.com_Azure_azure_sdk_for_go_sdk_azidentity;https://github.com/azure/azure-sdk-for-go
github.com_Azure_azure_sdk_for_go_sdk_internal;https://github.com/azure/azure-sdk-for-go
github.com_Azure_azure_sdk_for_go_sdk_resourcemanager_compute_armcompute_v4;https://github.com/azure/azure-sdk-for-go
github.com_Azure_azure_sdk_for_go_sdk_resourcemanager_network_armnetwork_v2;https://github.com/azure/azure-sdk-for-go
github.com_Azure_azure_sdk_for_go_sdk_storage_azblob;https://github.com/azure/azure-sdk-for-go
github.com_Azure_go_autorest_autorest;https://raw.githubusercontent.com/azure/go-autorest/master/LICENSE
github.com_Azure_go_autorest_autorest_adal;https://raw.githubusercontent.com/azure/go-autorest/master/LICENSE
github.com_Azure_go_autorest_autorest_date;https://raw.githubusercontent.com/azure/go-autorest/master/LICENSE
github.com_Azure_go_autorest_autorest_to;https://raw.githubusercontent.com/azure/go-autorest/master/LICENSE
github.com_Azure_go_autorest_autorest_validation;https://raw.githubusercontent.com/azure/go-autorest/master/LICENSE
github.com_Azure_go_autorest_logger;https://raw.githubusercontent.com/azure/go-autorest/master/LICENSE
github.com_Azure_go_autorest_tracing;https://raw.githubusercontent.com/azure/go-autorest/master/LICENSE
github.com_AzureAD_microsoft_authentication_library_for_go;https://raw.githubusercontent.com/azuread/microsoft-authentication-library-for-go/master/LICENSE
github.com_CycloneDX_cyclonedx_go;https://raw.githubusercontent.com/cyclonedx/cyclonedx-go/master/LICENSE
github.com_GoogleCloudPlatform_declarative_resource_client_library;https://raw.githubusercontent.com/googlecloudplatform/declarative-resource-client-library/master/LICENSE
github.com_GoogleCloudPlatform_guest_agent;https://github.com/GoogleCloudPlatform/guest-agent/blob/main/LICENSE
github.com_GoogleCloudPlatform_guest_logging_go;https://raw.githubusercontent.com/googlecloudplatform/guest-logging-go/master/LICENSE
github.com_GoogleCloudPlatform_opentelemetry_operations_collector;https://github.com/GoogleCloudPlatform/opentelemetry-operations-collector/blob/master/LICENSE
github.com_GoogleCloudPlatform_opentelemetry_operations_go_detectors_gcp;https://raw.githubusercontent.com/googlecloudplatform/opentelemetry-operations-go/master/LICENSE
github.com_GoogleCloudPlatform_opentelemetry_operations_go_exporter_collector;https://raw.githubusercontent.com/googlecloudplatform/opentelemetry-operations-go/master/LICENSE
github.com_GoogleCloudPlatform_opentelemetry_operations_go_exporter_collector_googlemanagedprometheus;https://raw.githubusercontent.com/googlecloudplatform/opentelemetry-operations-go/master/LICENSE
github.com_GoogleCloudPlatform_opentelemetry_operations_go_exporter_metric;https://raw.githubusercontent.com/googlecloudplatform/opentelemetry-operations-go/master/LICENSE
github.com_GoogleCloudPlatform_opentelemetry_operations_go_exporter_trace;https://raw.githubusercontent.com/googlecloudplatform/opentelemetry-operations-go/master/LICENSE
github.com_GoogleCloudPlatform_opentelemetry_operations_go_internal_resourcemapping;https://raw.githubusercontent.com/googlecloudplatform/opentelemetry-operations-go/master/LICENSE
github.com_GoogleCloudPlatform_ops_agent;https://github.com/GoogleCloudPlatform/ops-agent/blob/master/LICENSE
github.com_GoogleCloudPlatform_osconfig;https://github.com/GoogleCloudPlatform/osconfig/blob/master/LICENSE
github.com_GoogleContainerTools_kpt;https://raw.githubusercontent.com/googlecontainertools/kpt/master/LICENSE
github.com_GoogleContainerTools_kpt_porch_api;https://raw.githubusercontent.com/googlecontainertools/kpt/master/LICENSE
github.com_JohnCGriffin_overflow;https://github.com/johncgriffin/overflow
github.com_MakeNowJust_heredoc;https://raw.githubusercontent.com/makenowjust/heredoc/master/LICENSE
github.com_Masterminds_goutils;https://github.com/masterminds/goutils
github.com_Masterminds_semver;https://github.com/masterminds/semver
github.com_Masterminds_semver_v3;https://github.com/masterminds/semver
github.com_Masterminds_sprig_v3;https://github.com/masterminds/sprig
github.com_NVIDIA_go_dcgm;https://raw.githubusercontent.com/nvidia/go-dcgm/master/LICENSE
github.com_NVIDIA_go_nvml;https://github.com/NVIDIA/go-nvml/blob/main/LICENSE
github.com_ProtonMail_go_crypto;https://raw.githubusercontent.com/protonmail/go-crypto/master/LICENSE
github.com_SAP_go_hdb;https://raw.githubusercontent.com/sap/go-hdb/master/LICENSE.md
github.com_Showmax_go_fqdn;https://raw.githubusercontent.com/showmax/go-fqdn/master/LICENSE
github.com_acarl005_stripansi;https://github.com/acarl005/stripansi
github.com_acobaugh_osrelease;https://raw.githubusercontent.com/acobaugh/osrelease/master/LICENSE
github.com_adrg_xdg;https://raw.githubusercontent.com/adrg/xdg/master/LICENSE
github.com_aerospike_aerospike_client_go_v6;https://raw.githubusercontent.com/aerospike/aerospike-client-go/master/LICENSE
github.com_agext_levenshtein;https://raw.githubusercontent.com/agext/levenshtein/master/LICENSE
github.com_alecthomas_participle_v2;https://github.com/alecthomas/participle
github.com_alecthomas_units;https://github.com/alecthomas/units
github.com_anchore_bubbly;https://raw.githubusercontent.com/anchore/bubbly/master/LICENSE
github.com_anchore_clio;https://raw.githubusercontent.com/anchore/clio/master/LICENSE
github.com_anchore_fangs;https://raw.githubusercontent.com/anchore/fangs/master/LICENSE
github.com_anchore_go_logger;https://raw.githubusercontent.com/anchore/go-logger/master/LICENSE
github.com_anchore_go_macholibre;https://raw.githubusercontent.com/anchore/go-macholibre/master/LICENSE
github.com_anchore_go_struct_converter;https://raw.githubusercontent.com/anchore/go-struct-converter/master/LICENSE
github.com_anchore_go_version;https://raw.githubusercontent.com/anchore/go-version/master/LICENSE
github.com_anchore_packageurl_go;https://raw.githubusercontent.com/anchore/packageurl-go/master/LICENSE
github.com_anchore_stereoscope;https://raw.githubusercontent.com/anchore/stereoscope/master/LICENSE
github.com_anchore_syft;https://raw.githubusercontent.com/anchore/syft/master/LICENSE
github.com_andybalholm_brotli;https://raw.githubusercontent.com/andybalholm/brotli/master/LICENSE
github.com_apache_arrow_go_v12;https://github.com/apache/arrow
github.com_apache_thrift;https://raw.githubusercontent.com/apache/thrift/master/LICENSE
github.com_apparentlymart_go_cidr;https://raw.githubusercontent.com/apparentlymart/go-cidr/master/LICENSE
github.com_apparentlymart_go_textseg_v13;https://raw.githubusercontent.com/apparentlymart/go-textseg/master/LICENSE
github.com_aquasecurity_go_pep440_version;https://github.com/aquasecurity/go-pep440-version
github.com_aquasecurity_go_version;https://raw.githubusercontent.com/aquasecurity/go-version/master/LICENSE
github.com_armon_go_metrics;https://raw.githubusercontent.com/armon/go-metrics/master/LICENSE
github.com_asaskevich_govalidator;https://raw.githubusercontent.com/asaskevich/govalidator/master/LICENSE
github.com_aws_aws_sdk_go;https://github.com/aws/aws-sdk-go
github.com_aws_aws_sdk_go_v2;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_aws_protocol_eventstream;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_credentials;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_feature_s3_manager;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_internal_configsources;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_internal_endpoints_v2;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_internal_v4a;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_service_internal_accept_encoding;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_service_internal_checksum;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_service_internal_presigned_url;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_service_internal_s3shared;https://github.com/aws/aws-sdk-go-v2
github.com_aws_aws_sdk_go_v2_service_s3;https://github.com/aws/aws-sdk-go-v2
github.com_aws_smithy_go;https://raw.githubusercontent.com/aws/smithy-go/master/LICENSE
github.com_aymanbagabas_go_osc52_v2;https://github.com/aymanbagabas/go-osc52
github.com_becheran_wildmatch_go;https://raw.githubusercontent.com/becheran/wildmatch-go/master/LICENSE
github.com_beorn7_perks;https://github.com/beorn7/perks
github.com_bits_and_blooms_bitset;https://raw.githubusercontent.com/bits-and-blooms/bitset/master/LICENSE
github.com_bmatcuk_doublestar_v4;https://raw.githubusercontent.com/bmatcuk/doublestar/master/LICENSE
github.com_cenkalti_backoff;https://raw.githubusercontent.com/cenkalti/backoff/master/LICENSE
github.com_cenkalti_backoff_v4;https://raw.githubusercontent.com/cenkalti/backoff/master/LICENSE
github.com_cespare_xxhash_v2;https://github.com/cespare/xxhash
github.com_chai2010_gettext_go;https://github.com/chai2010/gettext-go
github.com_charmbracelet_bubbles;https://raw.githubusercontent.com/charmbracelet/bubbles/master/LICENSE
github.com_charmbracelet_bubbletea;https://raw.githubusercontent.com/charmbracelet/bubbletea/master/LICENSE
github.com_charmbracelet_harmonica;https://raw.githubusercontent.com/charmbracelet/harmonica/master/LICENSE
github.com_charmbracelet_lipgloss;https://raw.githubusercontent.com/charmbracelet/lipgloss/master/LICENSE
github.com_cloudflare_circl;https://raw.githubusercontent.com/cloudflare/circl/master/LICENSE
github.com_cncf_xds_go;https://raw.githubusercontent.com/cncf/xds/master/LICENSE
github.com_containerd_console;https://raw.githubusercontent.com/containerd/console/master/LICENSE
github.com_containerd_containerd;https://raw.githubusercontent.com/containerd/containerd/master/LICENSE
github.com_containerd_continuity;https://raw.githubusercontent.com/containerd/continuity/master/LICENSE
github.com_containerd_fifo;https://raw.githubusercontent.com/containerd/fifo/master/LICENSE
github.com_containerd_log;https://raw.githubusercontent.com/containerd/log/master/LICENSE
github.com_containerd_stargz_snapshotter_estargz;https://raw.githubusercontent.com/containerd/stargz-snapshotter/master/LICENSE
github.com_containerd_ttrpc;https://raw.githubusercontent.com/containerd/ttrpc/master/LICENSE
github.com_containerd_typeurl_v2;https://raw.githubusercontent.com/containerd/typeurl/master/LICENSE
github.com_cyphar_filepath_securejoin;https://raw.githubusercontent.com/cyphar/filepath-securejoin/master/LICENSE
github.com_davecgh_go_spew;https://raw.githubusercontent.com/davecgh/go-spew/master/LICENSE
github.com_deitch_magic;https://github.com/deitch/magic/blob/main/LICENSE
github.com_denisenkom_go_mssqldb;https://github.com/denisenkom/go-mssqldb
github.com_dennwc_varint;https://raw.githubusercontent.com/dennwc/varint/master/LICENSE
github.com_dgryski_go_rendezvous;https://raw.githubusercontent.com/dgryski/go-rendezvous/master/LICENSE
github.com_digitalocean_godo;https://github.com/digitalocean/godo
github.com_distribution_reference;https://github.com/distribution/reference/blob/main/LICENSE
github.com_docker_cli;https://raw.githubusercontent.com/docker/cli/master/LICENSE
github.com_docker_distribution;https://raw.githubusercontent.com/docker/distribution/master/LICENSE
github.com_docker_docker;https://raw.githubusercontent.com/docker/docker/master/LICENSE
github.com_docker_docker_credential_helpers;https://raw.githubusercontent.com/docker/docker-credential-helpers/master/LICENSE
github.com_docker_go_connections;https://raw.githubusercontent.com/docker/go-connections/master/LICENSE
github.com_docker_go_events;https://raw.githubusercontent.com/docker/go-events/master/LICENSE
github.com_docker_go_units;https://raw.githubusercontent.com/docker/go-units/master/LICENSE
github.com_dsnet_compress;https://raw.githubusercontent.com/dsnet/compress/master/LICENSE.md
github.com_dustin_go_humanize;https://raw.githubusercontent.com/dustin/go-humanize/master/LICENSE
github.com_dvsekhvalnov_jose2go;https://github.com/dvsekhvalnov/jose2go
github.com_edsrzf_mmap_go;https://raw.githubusercontent.com/edsrzf/mmap-go/master/LICENSE
github.com_emicklei_go_restful;https://raw.githubusercontent.com/emicklei/go-restful/master/LICENSE
github.com_emicklei_go_restful_v3;https://raw.githubusercontent.com/emicklei/go-restful/master/LICENSE
github.com_emirpasic_gods;https://raw.githubusercontent.com/emirpasic/gods/master/LICENSE
github.com_envoyproxy_go_control_plane;https://raw.githubusercontent.com/envoyproxy/go-control-plane/master/LICENSE
github.com_envoyproxy_protoc_gen_validate;https://raw.githubusercontent.com/envoyproxy/protoc-gen-validate/master/LICENSE
github.com_evanphx_json_patch;https://raw.githubusercontent.com/evanphx/json-patch/master/LICENSE
github.com_exponent_io_jsonpath;https://raw.githubusercontent.com/exponent-io/jsonpath/master/LICENSE
github.com_expr_lang_expr;https://raw.githubusercontent.com/expr-lang/expr/master/LICENSE
github.com_facebookincubator_nvdtools;https://raw.githubusercontent.com/facebookincubator/nvdtools/master/LICENSE
github.com_fatih_color;https://raw.githubusercontent.com/fatih/color/master/LICENSE.md
github.com_felixge_fgprof;https://github.com/felixge/fgprof
github.com_felixge_httpsnoop;https://github.com/felixge/httpsnoop
github.com_form3tech_oss_jwt_go;https://github.com/form3tech-oss/jwt-go
github.com_fsnotify_fsnotify;https://raw.githubusercontent.com/fsnotify/fsnotify/master/LICENSE
github.com_gabriel_vasile_mimetype;https://raw.githubusercontent.com/gabriel-vasile/mimetype/master/LICENSE
github.com_gammazero_deque;https://raw.githubusercontent.com/gammazero/deque/master/LICENSE
github.com_gammazero_workerpool;https://raw.githubusercontent.com/gammazero/workerpool/master/LICENSE
github.com_ghodss_yaml;https://raw.githubusercontent.com/ghodss/yaml/master/LICENSE
github.com_github_go_spdx_v2;https://raw.githubusercontent.com/github/go-spdx/master/LICENSE
github.com_go_errors_errors;https://github.com/go-errors/errors
github.com_go_git_gcfg;https://raw.githubusercontent.com/go-git/gcfg/master/LICENSE
github.com_go_git_go_billy_v5;https://raw.githubusercontent.com/go-git/go-billy/master/LICENSE
github.com_go_git_go_git_v5;https://raw.githubusercontent.com/go-git/go-git/master/LICENSE
github.com_go_ini_ini;https://raw.githubusercontent.com/go-ini/ini/master/LICENSE
github.com_go_kit_log;https://raw.githubusercontent.com/go-kit/log/master/LICENSE
github.com_go_logfmt_logfmt;https://raw.githubusercontent.com/go-logfmt/logfmt/master/LICENSE
github.com_go_logr_logr;https://raw.githubusercontent.com/go-logr/logr/master/LICENSE
github.com_go_logr_stdr;https://raw.githubusercontent.com/go-logr/stdr/master/LICENSE
github.com_go_openapi_jsonpointer;https://raw.githubusercontent.com/go-openapi/jsonpointer/master/LICENSE
github.com_go_openapi_jsonreference;https://raw.githubusercontent.com/go-openapi/jsonreference/master/LICENSE
github.com_go_openapi_swag;https://raw.githubusercontent.com/go-openapi/swag/master/LICENSE
github.com_go_playground_locales;https://raw.githubusercontent.com/go-playground/locales/master/LICENSE
github.com_go_playground_universal_translator;https://raw.githubusercontent.com/go-playground/universal-translator/master/LICENSE
github.com_go_playground_validator_v10;https://raw.githubusercontent.com/go-playground/validator/master/LICENSE
github.com_go_restruct_restruct;https://github.com/go-restruct/restruct/blob/master/LICENSE.md
github.com_go_resty_resty_v2;https://raw.githubusercontent.com/go-resty/resty/master/LICENSE
github.com_go_sql_driver_mysql;https://raw.githubusercontent.com/go-sql-driver/mysql/master/LICENSE
github.com_go_zookeeper_zk;https://raw.githubusercontent.com/go-zookeeper/zk/master/LICENSE
github.com_gobwas_glob;https://raw.githubusercontent.com/gobwas/glob/master/LICENSE
github.com_goccy_go_json;https://raw.githubusercontent.com/goccy/go-json/master/LICENSE
github.com_goccy_go_yaml;https://raw.githubusercontent.com/goccy/go-yaml/master/LICENSE
github.com_godbus_dbus;https://raw.githubusercontent.com/godbus/dbus/master/LICENSE
github.com_gogo_protobuf;https://raw.githubusercontent.com/gogo/protobuf/master/LICENSE
github.com_golang_jwt_jwt_v4;https://raw.githubusercontent.com/golang-jwt/jwt/master/LICENSE
github.com_golang_jwt_jwt_v5;https://raw.githubusercontent.com/golang-jwt/jwt/master/LICENSE
github.com_golang_sql_civil;https://raw.githubusercontent.com/golang-sql/civil/master/LICENSE
github.com_golang_sql_sqlexp;https://raw.githubusercontent.com/golang-sql/sqlexp/master/LICENSE
github.com_golang_glog;https://raw.githubusercontent.com/golang/glog/master/LICENSE
github.com_golang_groupcache;https://raw.githubusercontent.com/golang/groupcache/master/LICENSE
github.com_golang_mock;https://raw.githubusercontent.com/golang/mock/master/LICENSE
github.com_golang_protobuf;https://raw.githubusercontent.com/golang/protobuf/master/LICENSE
github.com_golang_snappy;https://raw.githubusercontent.com/golang/snappy/master/LICENSE
github.com_google_btree;https://raw.githubusercontent.com/google/btree/master/LICENSE
github.com_google_flatbuffers;https://raw.githubusercontent.com/google/flatbuffers/master/LICENSE
github.com_google_gnostic;https://raw.githubusercontent.com/google/gnostic/master/LICENSE
github.com_google_gnostic_models;https://raw.githubusercontent.com/google/gnostic-models/master/LICENSE
github.com_google_go_cmp;https://raw.githubusercontent.com/google/go-cmp/master/LICENSE
github.com_google_go_containerregistry;https://raw.githubusercontent.com/google/go-containerregistry/master/LICENSE
github.com_google_go_cpy;https://raw.githubusercontent.com/google/go-cpy/master/LICENSE
github.com_google_go_querystring;https://raw.githubusercontent.com/google/go-querystring/master/LICENSE
github.com_google_go_sev_guest;https://raw.githubusercontent.com/google/go-sev-guest/master/LICENSE
github.com_google_go_tpm;https://raw.githubusercontent.com/google/go-tpm/master/LICENSE
github.com_google_go_tpm_tools;https://raw.githubusercontent.com/google/go-tpm-tools/master/LICENSE
github.com_google_gofuzz;https://raw.githubusercontent.com/google/gofuzz/master/LICENSE
github.com_google_licensecheck;https://raw.githubusercontent.com/google/licensecheck/master/LICENSE
github.com_google_logger;https://raw.githubusercontent.com/google/logger/master/LICENSE
github.com_google_pprof;https://raw.githubusercontent.com/google/pprof/master/LICENSE
github.com_google_s2a_go;https://github.com/google/s2a-go
github.com_google_shlex;https://github.com/google/shlex
github.com_google_tink_go;https://raw.githubusercontent.com/google/tink/master/LICENSE
github.com_google_uuid;https://raw.githubusercontent.com/google/uuid/master/LICENSE
github.com_googleapis_enterprise_certificate_proxy;https://raw.githubusercontent.com/googleapis/enterprise-certificate-proxy/master/LICENSE
github.com_googleapis_gax_go_v2;https://raw.githubusercontent.com/googleapis/gax-go/master/LICENSE
github.com_gookit_color;https://raw.githubusercontent.com/gookit/color/master/LICENSE
github.com_gophercloud_gophercloud;https://raw.githubusercontent.com/gophercloud/gophercloud/master/LICENSE
github.com_gorilla_websocket;https://raw.githubusercontent.com/gorilla/websocket/master/LICENSE
github.com_grafana_regexp;https://raw.githubusercontent.com/grafana/regexp/master/LICENSE
github.com_gregjones_httpcache;https://github.com/gregjones/httpcache
github.com_grobie_gomemcache;https://raw.githubusercontent.com/grobie/gomemcache/master/LICENSE
github.com_grpc_ecosystem_go_grpc_middleware;https://raw.githubusercontent.com/grpc-ecosystem/go-grpc-middleware/master/LICENSE
github.com_grpc_ecosystem_grpc_gateway_v2;https://raw.githubusercontent.com/grpc-ecosystem/grpc-gateway/master/LICENSE
github.com_gsterjov_go_libsecret;https://raw.githubusercontent.com/gsterjov/go-libsecret/master/LICENSE
github.com_hashicorp_consul_api;https://raw.githubusercontent.com/hashicorp/consul/master/LICENSE
github.com_hashicorp_cronexpr;https://raw.githubusercontent.com/hashicorp/cronexpr/master/LICENSE
github.com_hashicorp_errwrap;https://raw.githubusercontent.com/hashicorp/errwrap/master/LICENSE
github.com_hashicorp_go_checkpoint;https://raw.githubusercontent.com/hashicorp/go-checkpoint/master/LICENSE
github.com_hashicorp_go_cleanhttp;https://raw.githubusercontent.com/hashicorp/go-cleanhttp/master/LICENSE
github.com_hashicorp_go_cty;https://raw.githubusercontent.com/hashicorp/go-cty/master/LICENSE
github.com_hashicorp_go_hclog;https://raw.githubusercontent.com/hashicorp/go-hclog/master/LICENSE
github.com_hashicorp_go_immutable_radix;https://raw.githubusercontent.com/hashicorp/go-immutable-radix/master/LICENSE
github.com_hashicorp_go_multierror;https://raw.githubusercontent.com/hashicorp/go-multierror/master/LICENSE
github.com_hashicorp_go_plugin;https://raw.githubusercontent.com/hashicorp/go-plugin/master/LICENSE
github.com_hashicorp_go_retryablehttp;https://raw.githubusercontent.com/hashicorp/go-retryablehttp/master/LICENSE
github.com_hashicorp_go_rootcerts;https://raw.githubusercontent.com/hashicorp/go-rootcerts/master/LICENSE
github.com_hashicorp_go_uuid;https://raw.githubusercontent.com/hashicorp/go-uuid/master/LICENSE
github.com_hashicorp_go_version;https://raw.githubusercontent.com/hashicorp/go-version/master/LICENSE
github.com_hashicorp_golang_lru;https://raw.githubusercontent.com/hashicorp/golang-lru/master/LICENSE
github.com_hashicorp_hc_install;https://raw.githubusercontent.com/hashicorp/hc-install/master/LICENSE
github.com_hashicorp_hcl;https://raw.githubusercontent.com/hashicorp/hcl/master/LICENSE
github.com_hashicorp_hcl_v2;https://raw.githubusercontent.com/hashicorp/hcl/master/LICENSE
github.com_hashicorp_logutils;https://raw.githubusercontent.com/hashicorp/logutils/master/LICENSE
github.com_hashicorp_nomad_api;https://raw.githubusercontent.com/hashicorp/nomad/master/LICENSE
github.com_hashicorp_serf;https://raw.githubusercontent.com/hashicorp/serf/master/LICENSE
github.com_hashicorp_terraform_exec;https://raw.githubusercontent.com/hashicorp/terraform-exec/master/LICENSE
github.com_hashicorp_terraform_json;https://raw.githubusercontent.com/hashicorp/terraform-json/master/LICENSE
github.com_hashicorp_terraform_plugin_go;https://raw.githubusercontent.com/hashicorp/terraform-plugin-go/master/LICENSE
github.com_hashicorp_terraform_plugin_log;https://raw.githubusercontent.com/hashicorp/terraform-plugin-log/master/LICENSE
github.com_hashicorp_terraform_plugin_sdk_v2;https://raw.githubusercontent.com/hashicorp/terraform-plugin-sdk/master/LICENSE
github.com_hashicorp_terraform_registry_address;https://raw.githubusercontent.com/hashicorp/terraform-registry-address/master/LICENSE
github.com_hashicorp_terraform_svchost;https://raw.githubusercontent.com/hashicorp/terraform-svchost/master/LICENSE
github.com_hashicorp_yamux;https://raw.githubusercontent.com/hashicorp/yamux/master/LICENSE
github.com_hetznercloud_hcloud_go;https://raw.githubusercontent.com/hetznercloud/hcloud-go/master/LICENSE
github.com_hetznercloud_hcloud_go_v2;https://raw.githubusercontent.com/hetznercloud/hcloud-go/master/LICENSE
github.com_huandu_xstrings;https://raw.githubusercontent.com/huandu/xstrings/master/LICENSE
github.com_iancoleman_strcase;https://raw.githubusercontent.com/iancoleman/strcase/master/LICENSE
github.com_imdario_mergo;https://raw.githubusercontent.com/imdario/mergo/master/LICENSE
github.com_influxdata_go_syslog_v3;https://raw.githubusercontent.com/influxdata/go-syslog/master/LICENSE
github.com_ionos_cloud_sdk_go_v6;https://raw.githubusercontent.com/ionos-cloud/sdk-go/master/LICENSE
github.com_jbenet_go_context;https://raw.githubusercontent.com/jbenet/go-context/master/LICENSE
github.com_jinzhu_copier;https://github.com/jinzhu/copier
github.com_jmespath_go_jmespath;https://raw.githubusercontent.com/jmespath/go-jmespath/master/LICENSE
github.com_josharian_intern;https://raw.githubusercontent.com/josharian/intern/master/LICENSE.md
github.com_jpillora_backoff;https://raw.githubusercontent.com/jpillora/backoff/master/LICENSE
github.com_json_iterator_go;https://raw.githubusercontent.com/json-iterator/go/master/LICENSE
github.com_julienschmidt_httprouter;https://raw.githubusercontent.com/julienschmidt/httprouter/master/LICENSE
github.com_kardianos_osext;https://raw.githubusercontent.com/kardianos/osext/master/LICENSE
github.com_kardianos_service;https://raw.githubusercontent.com/kardianos/service/master/LICENSE
github.com_kastenhq_goversion;https://raw.githubusercontent.com/kastenhq/goversion/master/LICENSE
github.com_kevinburke_ssh_config;https://raw.githubusercontent.com/kevinburke/ssh_config/master/LICENSE
github.com_klauspost_compress;https://raw.githubusercontent.com/klauspost/compress/master/LICENSE
github.com_klauspost_cpuid_v2;https://raw.githubusercontent.com/klauspost/cpuid/master/LICENSE
github.com_klauspost_pgzip;https://raw.githubusercontent.com/klauspost/pgzip/master/LICENSE
github.com_knadh_koanf;https://raw.githubusercontent.com/knadh/koanf/master/LICENSE
github.com_knadh_koanf_v2;https://raw.githubusercontent.com/knadh/koanf/master/LICENSE
github.com_knqyf263_go_rpmdb;https://github.com/knqyf263/go-rpmdb
github.com_kolo_xmlrpc;https://raw.githubusercontent.com/kolo/xmlrpc/master/LICENSE
github.com_kylelemons_godebug;https://raw.githubusercontent.com/kylelemons/godebug/master/LICENSE
github.com_leodido_go_urn;https://raw.githubusercontent.com/leodido/go-urn/master/LICENSE
github.com_leodido_ragel_machinery;https://raw.githubusercontent.com/leodido/ragel-machinery/master/LICENSE
github.com_lib_pq;https://raw.githubusercontent.com/lib/pq/master/LICENSE.md
github.com_liggitt_tabwriter;https://raw.githubusercontent.com/liggitt/tabwriter/master/LICENSE
github.com_linode_linodego;https://raw.githubusercontent.com/linode/linodego/master/LICENSE
github.com_lucasb_eyer_go_colorful;https://raw.githubusercontent.com/lucasb-eyer/go-colorful/master/LICENSE
github.com_magiconair_properties;https://raw.githubusercontent.com/magiconair/properties/master/LICENSE.md
github.com_mailru_easyjson;https://raw.githubusercontent.com/mailru/easyjson/master/LICENSE
github.com_mattn_go_colorable;https://raw.githubusercontent.com/mattn/go-colorable/master/LICENSE
github.com_mattn_go_isatty;https://raw.githubusercontent.com/mattn/go-isatty/master/LICENSE
github.com_mattn_go_localereader;https://raw.githubusercontent.com/mattn/go-localereader/master/LICENSE
github.com_mattn_go_runewidth;https://raw.githubusercontent.com/mattn/go-runewidth/master/LICENSE
github.com_matttproud_golang_protobuf_extensions;https://raw.githubusercontent.com/matttproud/golang_protobuf_extensions/master/LICENSE
github.com_matttproud_golang_protobuf_extensions_v2;https://raw.githubusercontent.com/matttproud/golang_protobuf_extensions/master/LICENSE
github.com_mgutz_ansi;https://raw.githubusercontent.com/mgutz/ansi/master/LICENSE
github.com_mholt_archiver_v3;https://raw.githubusercontent.com/mholt/archiver/master/LICENSE
github.com_microsoft_go_rustaudit;https://raw.githubusercontent.com/microsoft/go-rustaudit/master/LICENSE
github.com_miekg_dns;https://raw.githubusercontent.com/miekg/dns/master/LICENSE
github.com_mitchellh_copystructure;https://raw.githubusercontent.com/mitchellh/copystructure/master/LICENSE
github.com_mitchellh_go_homedir;https://raw.githubusercontent.com/mitchellh/go-homedir/master/LICENSE
github.com_mitchellh_go_testing_interface;https://raw.githubusercontent.com/mitchellh/go-testing-interface/master/LICENSE
github.com_mitchellh_go_wordwrap;https://raw.githubusercontent.com/mitchellh/go-wordwrap/master/LICENSE.md
github.com_mitchellh_hashstructure;https://raw.githubusercontent.com/mitchellh/hashstructure/master/LICENSE
github.com_mitchellh_hashstructure_v2;https://raw.githubusercontent.com/mitchellh/hashstructure/master/LICENSE
github.com_mitchellh_mapstructure;https://raw.githubusercontent.com/mitchellh/mapstructure/master/LICENSE
github.com_mitchellh_reflectwalk;https://raw.githubusercontent.com/mitchellh/reflectwalk/master/LICENSE
github.com_moby_locker;https://raw.githubusercontent.com/moby/locker/master/LICENSE
github.com_moby_spdystream;https://raw.githubusercontent.com/moby/spdystream/master/LICENSE
github.com_moby_sys_mountinfo;https://raw.githubusercontent.com/moby/sys/master/LICENSE
github.com_moby_sys_signal;https://raw.githubusercontent.com/moby/sys/master/LICENSE
github.com_moby_term;https://raw.githubusercontent.com/moby/term/master/LICENSE
github.com_modern_go_concurrent;https://raw.githubusercontent.com/modern-go/concurrent/master/LICENSE
github.com_modern_go_reflect2;https://github.com/modern-go/reflect2
github.com_monochromegane_go_gitignore;https://raw.githubusercontent.com/monochromegane/go-gitignore/master/LICENSE
github.com_montanaflynn_stats;https://raw.githubusercontent.com/montanaflynn/stats/master/LICENSE
github.com_mostynb_go_grpc_compression;https://raw.githubusercontent.com/mostynb/go-grpc-compression/master/LICENSE
github.com_mtibben_percent;https://raw.githubusercontent.com/mtibben/percent/master/LICENSE
github.com_muesli_ansi;https://raw.githubusercontent.com/muesli/ansi/master/LICENSE
github.com_muesli_cancelreader;https://raw.githubusercontent.com/muesli/cancelreader/master/LICENSE
github.com_muesli_reflow;https://raw.githubusercontent.com/muesli/reflow/master/LICENSE
github.com_muesli_termenv;https://raw.githubusercontent.com/muesli/termenv/master/LICENSE
github.com_munnerz_goautoneg;https://raw.githubusercontent.com/munnerz/goautoneg/master/LICENSE
github.com_mwitkow_go_conntrack;https://raw.githubusercontent.com/mwitkow/go-conntrack/master/LICENSE
github.com_nasa9084_go_openapi;https://github.com/nasa9084/go-openapi
github.com_nginxinc_nginx_prometheus_exporter;https://raw.githubusercontent.com/nginxinc/nginx-prometheus-exporter/master/LICENSE
github.com_nwaples_rardecode;https://raw.githubusercontent.com/nwaples/rardecode/master/LICENSE
github.com_oklog_run;https://raw.githubusercontent.com/oklog/run/master/LICENSE
github.com_olekukonko_tablewriter;https://raw.githubusercontent.com/olekukonko/tablewriter/master/LICENSE.md
github.com_open_telemetry_opentelemetry_collector_contrib_exporter_fileexporter;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_exporter_googlecloudexporter;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_internal_aws_ecsutil;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_internal_common;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_internal_coreinternal;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_internal_filter;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_internal_k8sconfig;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_internal_metadataproviders;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_internal_sharedcomponent;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_pkg_ottl;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_pkg_pdatautil;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_pkg_stanza;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_pkg_translator_prometheus;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_processor_filterprocessor;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_processor_groupbyattrsprocessor;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_processor_metricstransformprocessor;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_processor_resourcedetectionprocessor;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_processor_resourceprocessor;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_processor_transformprocessor;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_activedirectorydsreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_aerospikereceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_apachereceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_couchdbreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_elasticsearchreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_filelogreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_flinkmetricsreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_hostmetricsreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_iisreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_jmxreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_memcachedreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_mysqlreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_nginxreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_postgresqlreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_rabbitmqreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_redisreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_saphanareceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_sqlqueryreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_sqlserverreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_windowsperfcountersreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_open_telemetry_opentelemetry_collector_contrib_receiver_zookeeperreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/master/LICENSE
github.com_opencontainers_go_digest;https://raw.githubusercontent.com/opencontainers/go-digest/master/LICENSE
github.com_opencontainers_image_spec;https://raw.githubusercontent.com/opencontainers/image-spec/master/LICENSE
github.com_opencontainers_runc;https://raw.githubusercontent.com/opencontainers/runc/master/LICENSE
github.com_opencontainers_runtime_spec;https://raw.githubusercontent.com/opencontainers/runtime-spec/master/LICENSE
github.com_opencontainers_selinux;https://raw.githubusercontent.com/opencontainers/selinux/master/LICENSE
github.com_openshift_api;https://raw.githubusercontent.com/openshift/api/master/LICENSE
github.com_openshift_client_go;https://raw.githubusercontent.com/openshift/client-go/master/LICENSE
github.com_otiai10_copy;https://github.com/otiai10/copy
github.com_ovh_go_ovh;https://raw.githubusercontent.com/ovh/go-ovh/master/LICENSE
github.com_pborman_indent;https://raw.githubusercontent.com/pborman/indent/master/LICENSE
github.com_pborman_uuid;https://raw.githubusercontent.com/pborman/uuid/master/LICENSE
github.com_pelletier_go_toml;https://raw.githubusercontent.com/pelletier/go-toml/master/LICENSE
github.com_pelletier_go_toml_v2;https://raw.githubusercontent.com/pelletier/go-toml/master/LICENSE
github.com_peterbourgon_diskv;https://raw.githubusercontent.com/peterbourgon/diskv/master/LICENSE
github.com_pierrec_lz4_v4;https://github.com/pierrec/lz4
github.com_pjbgf_sha1cd;https://github.com/pjbgf/sha1cd
github.com_pkg_browser;https://raw.githubusercontent.com/pkg/browser/master/LICENSE
github.com_pkg_errors;https://raw.githubusercontent.com/pkg/errors/master/LICENSE
github.com_pkg_profile;https://raw.githubusercontent.com/pkg/profile/master/LICENSE
github.com_pmezard_go_difflib;https://raw.githubusercontent.com/pmezard/go-difflib/master/LICENSE
github.com_prometheus_client_golang;https://raw.githubusercontent.com/prometheus/client_golang/master/LICENSE
github.com_prometheus_client_model;https://raw.githubusercontent.com/prometheus/client_model/master/LICENSE
github.com_prometheus_common;https://raw.githubusercontent.com/prometheus/common/master/LICENSE
github.com_prometheus_common_sigv4;https://raw.githubusercontent.com/prometheus/common/master/LICENSE
github.com_prometheus_procfs;https://raw.githubusercontent.com/prometheus/procfs/master/LICENSE
github.com_prometheus_prometheus;https://raw.githubusercontent.com/prometheus/prometheus/master/LICENSE
github.com_prometheus_statsd_exporter;https://raw.githubusercontent.com/prometheus/statsd_exporter/master/LICENSE
github.com_redis_go_redis_v9;https://raw.githubusercontent.com/redis/go-redis/master/LICENSE
github.com_remyoudompheng_bigfft;https://raw.githubusercontent.com/remyoudompheng/bigfft/master/LICENSE
github.com_rivo_uniseg;https://github.com/rivo/uniseg
github.com_robfig_cron_v3;https://raw.githubusercontent.com/robfig/cron/master/LICENSE
github.com_rs_cors;https://raw.githubusercontent.com/rs/cors/master/LICENSE
github.com_russross_blackfriday;https://github.com/russross/blackfriday
github.com_saferwall_pe;https://raw.githubusercontent.com/saferwall/pe/master/LICENSE
github.com_saintfish_chardet;https://raw.githubusercontent.com/saintfish/chardet/master/LICENSE
github.com_sassoftware_go_rpmutils;https://raw.githubusercontent.com/sassoftware/go-rpmutils/master/LICENSE
github.com_scaleway_scaleway_sdk_go;https://raw.githubusercontent.com/scaleway/scaleway-sdk-go/master/LICENSE
github.com_scylladb_go_set;https://raw.githubusercontent.com/scylladb/go-set/master/LICENSE
github.com_sergi_go_diff;https://raw.githubusercontent.com/sergi/go-diff/master/LICENSE
github.com_shirou_gopsutil;https://raw.githubusercontent.com/shirou/gopsutil/master/LICENSE
github.com_shirou_gopsutil_v3;https://raw.githubusercontent.com/shirou/gopsutil/master/LICENSE
github.com_shopspring_decimal;https://raw.githubusercontent.com/shopspring/decimal/master/LICENSE
github.com_sijms_go_ora_v2;https://raw.githubusercontent.com/sijms/go-ora/master/LICENSE
github.com_sirupsen_logrus;https://raw.githubusercontent.com/sirupsen/logrus/master/LICENSE
github.com_skeema_knownhosts;https://raw.githubusercontent.com/skeema/knownhosts/master/LICENSE
github.com_snowflakedb_gosnowflake;https://raw.githubusercontent.com/snowflakedb/gosnowflake/master/LICENSE
github.com_spdx_tools_golang;https://github.com/spdx/tools-golang
github.com_spf13_afero;https://github.com/spf13/afero
github.com_spf13_cast;https://github.com/spf13/cast
github.com_spf13_cobra;https://github.com/spf13/cobra
github.com_spf13_jwalterweatherman;https://github.com/spf13/jwalterweatherman
github.com_spf13_pflag;https://github.com/spf13/pflag
github.com_spf13_viper;https://github.com/spf13/viper
github.com_stretchr_objx;https://raw.githubusercontent.com/stretchr/objx/master/LICENSE
github.com_stretchr_testify;https://raw.githubusercontent.com/stretchr/testify/master/LICENSE
github.com_subosito_gotenv;https://raw.githubusercontent.com/subosito/gotenv/master/LICENSE
github.com_sylabs_sif_v2;https://raw.githubusercontent.com/sylabs/sif/master/LICENSE.md
github.com_sylabs_squashfs;https://raw.githubusercontent.com/sylabs/squashfs/master/LICENSE
github.com_tarm_serial;https://raw.githubusercontent.com/tarm/serial/master/LICENSE
github.com_therootcompany_xz;https://raw.githubusercontent.com/therootcompany/xz/master/LICENSE
github.com_tidwall_gjson;https://raw.githubusercontent.com/tidwall/gjson/master/LICENSE
github.com_tidwall_match;https://raw.githubusercontent.com/tidwall/match/master/LICENSE
github.com_tidwall_pretty;https://raw.githubusercontent.com/tidwall/pretty/master/LICENSE
github.com_tidwall_tinylru;https://raw.githubusercontent.com/tidwall/tinylru/master/LICENSE
github.com_tidwall_wal;https://raw.githubusercontent.com/tidwall/wal/master/LICENSE
github.com_tklauser_go_sysconf;https://raw.githubusercontent.com/tklauser/go-sysconf/master/LICENSE
github.com_tklauser_numcpus;https://raw.githubusercontent.com/tklauser/numcpus/master/LICENSE
github.com_ulikunitz_xz;https://raw.githubusercontent.com/ulikunitz/xz/master/LICENSE
github.com_vbatts_go_mtree;https://raw.githubusercontent.com/vbatts/go-mtree/master/LICENSE
github.com_vbatts_tar_split;https://raw.githubusercontent.com/vbatts/tar-split/master/LICENSE
github.com_vifraa_gopom;https://raw.githubusercontent.com/vifraa/gopom/master/LICENSE
github.com_vmihailenco_msgpack;https://raw.githubusercontent.com/vmihailenco/msgpack/master/LICENSE
github.com_vmihailenco_msgpack_v4;https://raw.githubusercontent.com/vmihailenco/msgpack/master/LICENSE
github.com_vmihailenco_tagparser;https://raw.githubusercontent.com/vmihailenco/tagparser/master/LICENSE
github.com_vultr_govultr_v2;https://raw.githubusercontent.com/vultr/govultr/master/LICENSE
github.com_wagoodman_go_partybus;https://raw.githubusercontent.com/wagoodman/go-partybus/master/LICENSE
github.com_wagoodman_go_progress;https://raw.githubusercontent.com/wagoodman/go-progress/master/LICENSE
github.com_xanzy_ssh_agent;https://raw.githubusercontent.com/xanzy/ssh-agent/master/LICENSE
github.com_xdg_go_pbkdf2;https://github.com/xdg-go/pbkdf2
github.com_xdg_go_scram;https://raw.githubusercontent.com/xdg-go/scram/master/LICENSE
github.com_xdg_go_stringprep;https://raw.githubusercontent.com/xdg-go/stringprep/master/LICENSE
github.com_xi2_xz;https://github.com/xi2/xz
github.com_xlab_treeprint;https://raw.githubusercontent.com/xlab/treeprint/master/LICENSE
github.com_xo_terminfo;https://raw.githubusercontent.com/xo/terminfo/master/LICENSE
github.com_youmark_pkcs8;https://github.com/youmark/pkcs8/blob/master/LICENSE
github.com_yuin_gopher_lua;https://raw.githubusercontent.com/yuin/gopher-lua/master/LICENSE
github.com_zclconf_go_cty;https://raw.githubusercontent.com/zclconf/go-cty/master/LICENSE
github.com_zeebo_xxh3;https://github.com/zeebo/xxh3
github.com_zyedidia_generic;https://raw.githubusercontent.com/zyedidia/generic/master/LICENSE
github_codeql_action_analyze;https://github.com/github/codeql-action/blob/main/LICENSE
github_codeql_action_autobuild;https://github.com/github/codeql-action/blob/main/LICENSE
github_codeql_action_init;https://github.com/github/codeql-action/blob/main/LICENSE
go.chromium.org_luci;https://chromium.googlesource.com/infra/luci/luci-go
go.mongodb.org_mongo_driver;https://raw.githubusercontent.com/mongodb/mongo-go-driver/master/LICENSE
go.mozilla.org_pkcs7;https://github.com/mozilla-services/pkcs7
go.opencensus.io;https://raw.githubusercontent.com/census-instrumentation/opencensus-go/master/LICENSE
go.opentelemetry.io_collector;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_component;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_config_configauth;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_config_configcompression;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_config_configgrpc;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_config_confighttp;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_config_confignet;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_config_configopaque;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_config_configtelemetry;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_config_configtls;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_config_internal;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_confmap;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_connector;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_consumer;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_exporter;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_exporter_loggingexporter;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_exporter_otlpexporter;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_exporter_otlphttpexporter;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_extension;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_extension_auth;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_extension_ballastextension;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_extension_zpagesextension;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_featuregate;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_otelcol;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_pdata;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_processor;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_processor_batchprocessor;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_processor_memorylimiterprocessor;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_receiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_receiver_otlpreceiver;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_semconv;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_collector_service;https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/LICENSE
go.opentelemetry.io_contrib_config;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go-contrib/master/LICENSE
go.opentelemetry.io_contrib_detectors_gcp;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go-contrib/master/LICENSE
go.opentelemetry.io_contrib_instrumentation_google.golang.org_grpc_otelgrpc;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go-contrib/master/LICENSE
go.opentelemetry.io_contrib_instrumentation_net_http_otelhttp;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go-contrib/master/LICENSE
go.opentelemetry.io_contrib_propagators_b3;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go-contrib/master/LICENSE
go.opentelemetry.io_contrib_zpages;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go-contrib/master/LICENSE
go.opentelemetry.io_otel;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_bridge_opencensus;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_exporters_otlp_otlpmetric_otlpmetricgrpc;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_exporters_otlp_otlpmetric_otlpmetrichttp;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_exporters_otlp_otlptrace;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_exporters_otlp_otlptrace_otlptracegrpc;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_exporters_otlp_otlptrace_otlptracehttp;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_exporters_prometheus;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_exporters_stdout_stdoutmetric;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_exporters_stdout_stdouttrace;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_metric;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_sdk;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_sdk_metric;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_otel_trace;https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/master/LICENSE
go.opentelemetry.io_proto_otlp;https://raw.githubusercontent.com/open-telemetry/opentelemetry-proto-go/master/LICENSE
go.starlark.net;https://raw.githubusercontent.com/google/starlark-go/master/LICENSE
go.uber.org_atomic;https://github.com/uber-go/atomic
go.uber.org_multierr;https://github.com/uber-go/multierr
go.uber.org_zap;https://raw.githubusercontent.com/uber-go/zap/master/LICENSE
golang.org_x_crypto;https://go.googlesource.com/crypto
golang.org_x_exp;https://go.googlesource.com/exp
golang.org_x_mod;https://go.googlesource.com/mod
golang.org_x_net;https://go.googlesource.com/net
golang.org_x_oauth2;https://go.googlesource.com/oauth2
golang.org_x_sync;https://go.googlesource.com/sync
golang.org_x_sys;https://go.googlesource.com/sys
golang.org_x_term;https://go.googlesource.com/term
golang.org_x_text;https://go.googlesource.com/text
golang.org_x_time;https://go.googlesource.com/time
golang.org_x_xerrors;https://go.googlesource.com/xerrors
gonum.org_v1_gonum;https://raw.githubusercontent.com/gonum/gonum/master/LICENSE
google_api_core;https://raw.githubusercontent.com/googleapis/python-api-core/master/LICENSE
google_auth;https://raw.githubusercontent.com/googleapis/google-auth-library-python/master/LICENSE
google_cloud_compute;https://raw.githubusercontent.com/googleapis/python-compute/master/LICENSE
google_cloud_core;https://raw.githubusercontent.com/googleapis/python-cloud-core/master/LICENSE
google_cloud_storage;https://raw.githubusercontent.com/googleapis/python-storage/master/LICENSE
google_crc32c;https://github.com/googleapis/python-crc32c
google_resumable_media;https://raw.githubusercontent.com/googleapis/google-resumable-media-python/master/LICENSE
google.golang.org_api;https://raw.githubusercontent.com/googleapis/google-api-go-client/master/LICENSE
google.golang.org_appengine;https://raw.githubusercontent.com/golang/appengine/master/LICENSE
google.golang.org_genproto;https://raw.githubusercontent.com/googleapis/go-genproto/master/LICENSE
google.golang.org_genproto_googleapis_api;https://raw.githubusercontent.com/googleapis/go-genproto/master/LICENSE
google.golang.org_genproto_googleapis_rpc;https://raw.githubusercontent.com/googleapis/go-genproto/master/LICENSE
google.golang.org_grpc;https://raw.githubusercontent.com/grpc/grpc-go/master/LICENSE
google.golang.org_protobuf;https://go.googlesource.com/protobuf
googleapis_common_protos;https://raw.githubusercontent.com/googleapis/python-api-common-protos/master/LICENSE
gopkg.in_inf.v0;https://gopkg.in/inf.v0
gopkg.in_ini.v1;https://gopkg.in/ini.v1
gopkg.in_natefinch_lumberjack.v2;https://gopkg.in/natefinch/lumberjack.v2
gopkg.in_warnings.v0;https://gopkg.in/warnings.v0
gopkg.in_yaml.v2;https://gopkg.in/yaml.v2
gopkg.in_yaml.v3;https://gopkg.in/yaml.v3
greenlet;https://raw.githubusercontent.com/python-greenlet/greenlet/master/LICENSE
grpcio;https://raw.githubusercontent.com/grpc/grpc/master/LICENSE
gson;https://raw.githubusercontent.com/google/gson/master/LICENSE
guava;https://raw.githubusercontent.com/google/guava/master/LICENSE
httpbin;https://raw.githubusercontent.com/requests/httpbin/master/LICENSE
httplib2;https://github.com/httplib2/httplib2
idna;https://raw.githubusercontent.com/kjd/idna/master/LICENSE.md
importlib_metadata;https://raw.githubusercontent.com/python/importlib_metadata/master/LICENSE
isodate;https://raw.githubusercontent.com/gweis/isodate/master/LICENSE
jaraco_classes;https://github.com/jaraco/jaraco.classes
jctools_core;https://raw.githubusercontent.com/JCTools/JCTools/master/LICENSE
jeepney;https://gitlab.com/takluyver/jeepney
jinja2;https://raw.githubusercontent.com/pallets/jinja/master/LICENSE.rst
jmxremote_optional_tc;https://central.sonatype.com/artifact/io.opentelemetry.contrib/opentelemetry-java-contrib-jmx-metrics
jsr305;https://code.google.com/p/jsr-305/
k8s.io_api;https://raw.githubusercontent.com/kubernetes/api/master/LICENSE
k8s.io_apiextensions_apiserver;https://raw.githubusercontent.com/kubernetes/apiextensions-apiserver/master/LICENSE
k8s.io_apimachinery;https://raw.githubusercontent.com/kubernetes/apimachinery/master/LICENSE
k8s.io_cli_runtime;https://raw.githubusercontent.com/kubernetes/cli-runtime/master/LICENSE
k8s.io_client_go;https://raw.githubusercontent.com/kubernetes/client-go/master/LICENSE
k8s.io_component_base;https://raw.githubusercontent.com/kubernetes/component-base/master/LICENSE
k8s.io_klog_v2;https://raw.githubusercontent.com/kubernetes/klog/master/LICENSE
k8s.io_kube_openapi;https://raw.githubusercontent.com/kubernetes/kube-openapi/master/LICENSE
k8s.io_kubectl;https://raw.githubusercontent.com/kubernetes/kubectl/master/LICENSE
k8s.io_utils;https://raw.githubusercontent.com/kubernetes/utils/master/LICENSE
keyring;https://raw.githubusercontent.com/jaraco/keyring/master/LICENSE
libintl;https://mvnrepository.com/artifact/org.gnu.gettext/libintl/0.18.3
libsass;https://github.com/sass/libsass-python/blob/main/LICENSE
lxml;https://github.com/lxml/lxml
markupsafe;https://raw.githubusercontent.com/pallets/markupsafe/master/LICENSE.rst
mock;https://github.com/testing-cabal/mock
mock;https://raw.githubusercontent.com/uber/mock/master/LICENSE
modernc.org_libc;https://gitlab.com/cznic/libc
modernc.org_mathutil;https://gitlab.com/cznic/mathutil
modernc.org_memory;https://gitlab.com/cznic/memory
modernc.org_sqlite;https://gitlab.com/cznic/sqlite
more_itertools;https://raw.githubusercontent.com/more-itertools/more-itertools/master/LICENSE
mypy;https://raw.githubusercontent.com/python/mypy/master/LICENSE
nginx;http://nginx.org/LICENSE
nox;https://raw.githubusercontent.com/wntrblm/nox/master/LICENSE
num2words;https://github.com/savoirfairelinux/num2words
odoo;https://github.com/odoo/odoo/blob/17.0/LICENSE
ofxparse;https://github.com/jseutter/ofxparse/blob/master/LICENSE
olefile;https://github.com/decalage2/olefile/blob/master/LICENSE.txt
opentelemetry_java_contrib_jmx_metrics;https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/LICENSE
packaging;https://raw.githubusercontent.com/pypa/packaging/master/LICENSE
passlib;https://pypi.org/project/passlib/
peter_evans_create_pull_request;https://github.com/peter-evans/create-pull-request/blob/main/LICENSE
pip;https://github.com/pypa/pip
pkginfo;https://github.com/jwilk-mirrors/python-pkginfo/blob/master/LICENSE.txt
platformdirs;https://raw.githubusercontent.com/platformdirs/platformdirs/master/LICENSE
polib;http://bitbucket.org/izi/polib
postgresql;https://github.com/postgres/postgres/blob/master/COPYRIGHT
pre_commit_action;https://github.com/pre-commit/action/blob/main/LICENSE
protobuf;https://raw.githubusercontent.com/golang/protobuf/master/LICENSE
psutil;https://raw.githubusercontent.com/giampaolo/psutil/master/LICENSE
psycopg2;https://raw.githubusercontent.com/psycopg/psycopg2/master/LICENSE
psycopg2;https://github.com/psycopg/psycopg2
pyOpenSSL;https://raw.githubusercontent.com/pyca/pyopenssl/master/LICENSE
pyaes;https://github.com/ricmoo/pyaes
pyasn1;https://github.com/etingof/pyasn1
pyasn1_modules;https://github.com/etingof/pyasn1-modules
pycparser;https://raw.githubusercontent.com/eliben/pycparser/master/LICENSE
pycurl;https://github.com/pycurl/pycurl/blob/master/COPYING-MIT
pydot;https://raw.githubusercontent.com/pydot/pydot/master/LICENSE
pygments;https://raw.githubusercontent.com/pygments/pygments/master/LICENSE
pyjwt;https://raw.githubusercontent.com/jpadilla/pyjwt/master/LICENSE
pyldap;https://github.com/pyldap/pyldap
pyopenssl;https://raw.githubusercontent.com/pyca/pyopenssl/master/LICENSE
pypa_gh_action_pypi_publish;https://github.com/pypa/gh-action-pypi-publish/blob/unstable/v1/LICENSE.md
pyparsing;https://raw.githubusercontent.com/pyparsing/pyparsing/master/LICENSE
pyperclip;https://github.com/asweigart/pyperclip
pyserial;https://github.com/pyserial/pyserial
pytest;https://raw.githubusercontent.com/pytest-dev/pytest/master/LICENSE
pytest_cov;https://raw.githubusercontent.com/pytest-dev/pytest-cov/master/LICENSE
pytest_forked;https://raw.githubusercontent.com/pytest-dev/pytest-forked/master/LICENSE
pytest_freezegun;https://raw.githubusercontent.com/ktosiek/pytest-freezegun/master/LICENSE
pytest_httpbin;https://github.com/kevin1024/pytest-httpbin
pytest_mock;https://raw.githubusercontent.com/pytest-dev/pytest-mock/master/LICENSE
pytest_randomly;https://raw.githubusercontent.com/adamchainz/pytest-randomly/master/LICENSE
pytest_timeout;http://github.com/pytest-dev/pytest-timeout
pytest_xdist;https://raw.githubusercontent.com/pytest-dev/pytest-xdist/master/LICENSE
python;https://raw.githubusercontent.com/rthalley/dnspython/master/LICENSE
python_apt;https://github.com/excid3/python-apt/blob/master/COPYING.GPL
python_dateutil;https://raw.githubusercontent.com/dateutil/dateutil/master/LICENSE
python_debian;https://raw.githubusercontent.com/venthur/python-debianbts/master/LICENSE
python_debianbts;https://raw.githubusercontent.com/venthur/python-debianbts/master/LICENSE
python_ldap;https://raw.githubusercontent.com/python-ldap/python-ldap/main/LICENCE
python_stdnum;https://github.com/arthurdejong/python-stdnum
pytz;https://raw.githubusercontent.com/stub42/pytz/master/LICENSE.txt
pyusb;https://github.com/pyusb/pyusb/blob/master/LICENSE
qrcode;https://raw.githubusercontent.com/lincolnloop/python-qrcode/master/LICENSE
readme_renderer;https://raw.githubusercontent.com/pypa/readme_renderer/master/LICENSE
reportbug;https://github.com/venthur/reportbug-ng/blob/master/LICENSE
reportlab;https://github.com/Distrotech/reportlab/blob/master/LICENSE.txt
requests;https://raw.githubusercontent.com/psf/requests/master/LICENSE
requests_file;http://github.com/dashea/requests-file
requests_toolbelt;https://raw.githubusercontent.com/requests/toolbelt/master/LICENSE
rfc3986;https://raw.githubusercontent.com/python-hyper/rfc3986/main/LICENSE
rich;https://raw.githubusercontent.com/willmcgugan/rich/master/LICENSE
roman;https://github.com/zopefoundation/roman/blob/master/LICENSE.txt
rsa;https://raw.githubusercontent.com/go-playground/universal-translator/master/LICENSE
rsa;https://raw.githubusercontent.com/sybrenstuvel/python-rsa/master/LICENSE
secretstorage;https://github.com/mitya57/secretstorage
setuptools;https://raw.githubusercontent.com/pypa/setuptools/master/LICENSE
sigs.k8s.io_cli_utils;https://raw.githubusercontent.com/kubernetes-sigs/cli-utils/master/LICENSE
sigs.k8s.io_controller_runtime;https://raw.githubusercontent.com/kubernetes-sigs/controller-runtime/master/LICENSE
sigs.k8s.io_json;https://raw.githubusercontent.com/kubernetes-sigs/json/master/LICENSE
sigs.k8s.io_kustomize_api;https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/LICENSE
sigs.k8s.io_kustomize_kyaml;https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/LICENSE
sigs.k8s.io_structured_merge_diff_v4;https://raw.githubusercontent.com/kubernetes-sigs/structured-merge-diff/master/LICENSE
sigs.k8s.io_yaml;https://raw.githubusercontent.com/kubernetes-sigs/yaml/master/LICENSE
simpleclient;git@github.com:prometheus/client_java.git
simpleclient_common;git@github.com:prometheus/client_java.git
simpleclient_httpserver;git@github.com:prometheus/client_java.git
simpleclient_tracer_common;git@github.com:prometheus/client_java.git
simpleclient_tracer_otel;git@github.com:prometheus/client_java.git
simpleclient_tracer_otel_agent;git@github.com:prometheus/client_java.git
simplejson;http://github.com/simplejson/simplejson
six;https://raw.githubusercontent.com/benjaminp/six/master/LICENSE
slf4j_api;https://github.com/qos-ch/slf4j
slf4j_simple;https://github.com/qos-ch/slf4j
soupsieve;https://raw.githubusercontent.com/facelessuser/soupsieve/master/LICENSE.md
sslcrypto;https://raw.githubusercontent.com/imachug/sslcrypto/master/LICENSE
stdlib;https://pkg.go.dev/github.com/radisvaliullin/test-golang/stdlib?tab=licenses
tornado;https://raw.githubusercontent.com/tornadoweb/tornado/master/LICENSE
tox;https://raw.githubusercontent.com/FasterXML/woodstox/master/LICENSE
trustme;https://raw.githubusercontent.com/python-trio/trustme/master/LICENSE
twine;https://raw.githubusercontent.com/pypa/twine/master/LICENSE
typing_extensions;https://raw.githubusercontent.com/python/typing_extensions/master/LICENSE
unattended_upgrades;https://github.com/mvo5/unattended-upgrades/blob/master/COPYING
urllib3;https://github.com/urllib3/urllib3
virtualenv;https://raw.githubusercontent.com/pypa/virtualenv/master/LICENSE
vobject;https://github.com/skarim/vobject/blob/master/LICENSE-2.0.txt
watchdog;http://github.com/gorakhargosh/watchdog
webencodings;https://raw.githubusercontent.com/SimonSapin/python-webencodings/master/LICENSE
wheel;https://github.com/pypa/wheel
win_inet_pton;https://raw.githubusercontent.com/hickeroar/win_inet_pton/master/LICENSE
wrapt;https://raw.githubusercontent.com/GrahamDumpleton/wrapt/master/LICENSE
xlrd;https://github.com/python-excel/xlrd/blob/master/LICENSE
xlwt;https://github.com/python-excel/xlwt/blob/master/LICENSE
zeep;https://github.com/mvantellingen/python-zeep/blob/main/LICENSE
zipp;https://raw.githubusercontent.com/jaraco/zipp/master/LICENSE
zope.event;http://github.com/zopefoundation/zope.event
zope.interface;https://github.com/zopefoundation/zope.interface
EOF
end
