#!/bin/bash -eu
#
# Copyright 2021 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/c2d-utils || exit 1

export COMPOSER_HOME="/root/.config/composer"
export COMPOSER_MEMORY_LIMIT=-1

declare -r mysql_password="$(get_attribute_value "mysql-root-password")"
declare -r oro_db_password="$(get_attribute_value "oro-db-password")"
declare -r oro_db_user="oro"
declare -r oro_db_name="oro_crm"
declare -r oro_admin_user="admin"
declare -r oro_admin_password="$(get_attribute_value "oro-admin-password")"
declare -r oro_project="my_project"
declare -r oro_folder="/opt/orocrm"
declare -r oro_url="http://$(get_internal_ip)/"

function wait_for_app() {
  local max_retries=10
  local retry=1
  local http_code=0

  while [[ "${http_code}" -ne 200 && "${retry}" -le "${max_retries}" ]]; do
    http_code="$(curl -s -L -o /dev/null -w "%{http_code}" http://localhost)"
    (( retry=retry+1 ))
  done

  if [[ "${retry}" -gt "${max_retries}" ]]; then
    echo "Max retries exceeded."
    exit 1
  fi
}

# Creates Orocrm database user
mysql --user="root" --password="${mysql_password}" --database="mysql" <<-EOSQL
  CREATE USER '${oro_db_user}'@'localhost' IDENTIFIED BY '${oro_db_password}';
  GRANT ALL ON ${oro_db_name}.* TO '${oro_db_user}'@'localhost';
EOSQL

echo "[mysqld]" >> /etc/my.cnf
echo "default-authentication-plugin=mysql_native_password" >> /etc/my.cnf
echo "innodb_file_per_table = 0" >> /etc/my.cnf
echo "wait_timeout = 28800" >> /etc/my.cnf

service mysql restart
echo "Restarting Mysql..."

mkdir "${oro_folder}"
cd "${oro_folder}/"
composer create-project oro/crm-application ${oro_project} -n

# Install Oro_crm
cd "${oro_folder}/${oro_project}/"

echo "Adding DB user and password to config file..."
sed -i "s/database_user: .*$/database_user: ${oro_db_user}/" config/parameters.yml
sed -i "s/database_password: .*$/database_password: ${oro_db_password}/" config/parameters.yml

rm -rf var/cache/*

echo "Installing OroCRM..."
php bin/console oro:install -vv \
--application-url=${oro_url} \
  --user-name="${oro_admin_user}" \
  --user-password="${oro_admin_password}" \
  --user-email=example@example.com \
  --user-lastname=Test \
  --user-firstname=User \
  --env=prod \
  --no-interaction \

# Assign permission to Apache user
echo "Assign permission to Apache user..."
chown -R www-data:www-data "${oro_folder}/"

# Configure Apache
rm -f /etc/apache2/sites-enabled/000-default.conf
envsubst '\$oro_project' < /opt/c2d/apache-orocrm.conf \
  > /etc/apache2/sites-enabled/orocrm.conf

# Restart Apache
echo "Restarting Apache..."
systemctl restart apache2

echo "Installation complete!"
