#!/bin/bash -eu
#
# Copyright 2023 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/c2d-utils || exit 1

declare -r password="${password:-$(get_attribute_value "mysql-root-password")}"

mysql --protocol=socket --user="root"  <<-EOSQL
  ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${password}';
EOSQL

mysql --user="root" --password="${password}" --database="mysql" <<-EOSQL
  DROP USER IF EXISTS 'mysql.infoschema'@'localhost';
  CREATE USER 'mysql.infoschema'@'localhost' IDENTIFIED BY '${password}';
  UPDATE user SET select_priv = 'Y' WHERE user = 'mysql.infoschema';
  FLUSH PRIVILEGES;
EOSQL
