#!/bin/bash -eu
#
# Copyright 2020 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/c2d-utils || exit 1
source /opt/mattermost-utils || exit 1

# Get all settings from metadata
readonly metadata_db_host="$(get_attribute_value "mattermost-database-host")"
readonly metadata_db_name="$(get_attribute_value "mattermost-database-name")"
readonly metadata_db_user="$(get_attribute_value "mattermost-database-user")"
readonly metadata_db_pwd="$(get_attribute_value "mattermost-database-pwd")"
readonly metadata_sitename="$(get_attribute_value "mattermost-sitename")"
readonly metadata_domain="$(get_attribute_value "mattermost-site")"
readonly metadata_email="$(get_attribute_value "mattermost-email")"

# Create user in MySQL database
create_db_user \
  "${metadata_db_host}" "${metadata_db_name}" "${metadata_db_user}" "${metadata_db_pwd}"

# Build Data Source config
database_dsn="${metadata_db_user}:${metadata_db_pwd}@tcp(${metadata_db_host}:3306)/${metadata_db_name}?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s"

# Update DSN and Sitename
update_config "${database_dsn}" "${metadata_sitename}"

# Setup nginx
setup_nginx "${metadata_domain}" "${metadata_email}"

# Start mattermost
systemctl start mattermost
