#!/bin/bash -eu
#
### BEGIN INIT INFO
# Provides:          liferay
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/ Stop Liferay Community Server daemon
# Description:       This service script facilitates startup and shutdown of
#                    liferay daemon throught tomcat
### END INIT INFO
#

# Copyright 2021 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

TOMCAT_BIN_PATH="/opt/liferay/tomcat*/bin"
LIFERAY_USER="liferay"

start() {
  sudo -u $LIFERAY_USER $TOMCAT_BIN_PATH/startup.sh
}

stop(){
  sudo -u $LIFERAY_USER $TOMCAT_BIN_PATH/shutdown.sh
}

case "$1" in
  start)
    echo "Starting liferay server"
    start
    ;;
  stop)
    echo "Stoping liferay server"
    stop
    ;;
  restart)
    echo "Restarting liferay server"
    stop
    start
    ;;
  *)
    echo "Usage: /etc/init.d/liferay {start|stop|restart}"
esac
