#!/bin/bash -eu
#
# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/c2d-utils || exit 1

readonly user=admin
readonly pass="$(get_metadata_value "instance/attributes/jenkins-admin-password")"

readonly salt=$(dd if=/dev/urandom bs=16 count=1 2>/dev/null | base64 - | tr -d / | fold -w 16 | head -n1)
readonly hash=$(echo -n "${pass}{$salt}" | sha256sum | sed "s/\(.*\)...$/$salt:\1/")

token=$(dd if=/dev/urandom bs=72 count=1 2>/dev/null | base64 - | tr -d \\n)

rm -fr /var/lib/jenkins/users/admin*
rm -fr /var/lib/jenkins/users/*

mkdir /var/lib/jenkins/users/${user}

cat <<EOF >/var/lib/jenkins/users/${user}/config.xml
<?xml version='1.0' encoding='UTF-8'?>
<user>
  <fullName>admin</fullName>
  <properties>
    <jenkins.security.ApiTokenProperty>
      <apiToken>${token}</apiToken>
    </jenkins.security.ApiTokenProperty>
    <hudson.model.MyViewsProperty>
      <views>
        <hudson.model.AllView>
          <owner class="hudson.model.MyViewsProperty" reference="../../.."/>
          <name>all</name>
          <filterExecutors>false</filterExecutors>
          <filterQueue>false</filterQueue>
          <properties class="hudson.model.View\$PropertyList"/>
        </hudson.model.AllView>
      </views>
    </hudson.model.MyViewsProperty>
    <hudson.model.PaneStatusProperties>
      <collapsed/>
    </hudson.model.PaneStatusProperties>
    <hudson.search.UserSearchProperty>
      <insensitiveSearch>false</insensitiveSearch>
    </hudson.search.UserSearchProperty>
    <hudson.security.HudsonPrivateSecurityRealm_-Details>
      <passwordHash>${hash}</passwordHash>
    </hudson.security.HudsonPrivateSecurityRealm_-Details>
  </properties>

EOF
chown -R jenkins:jenkins /var/lib/jenkins/users/${user}
sed -i -e 's/<isSetupComplete>false/<isSetupComplete>true/' -e 's/<installStateName>NEW/<installStateName>RUNNING/' /var/lib/jenkins/config.xml

systemctl stop jenkins
systemctl start jenkins
