#!/bin/bash
#
# Copyright 2021 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/c2d-utils

declare kafka_mode="$(get_attribute_value "kafka-mode")"
declare kafka_nodes="$(get_attribute_value "kafka-nodes")"

declare -r zookeeper_config="/opt/kafka/config/zookeeper.properties"

# Define default value for Kafka mode
: ${kafka_mode:-"standalone"}

echo "Kafka Mode: ${kafka_mode}"

# Configure Kafka in Cluster mode
if [[ "${kafka_mode}" == "cluster" ]]; then
  declare -r current_id="hostname -a | rev | cut -d '-' -f 1 | rev"

  # Stop Kafka
  systemctl stop kafka

  # Configure Zookeeper
  mkdir -p /var/data/kafka

  # Set data dir
  sed -i 's/dataDir=\/tmp\/zookeeper/data=\/var\/data\/kafka/g' "${zookeeper_config}"

  # server.properties
  # broker.id = autonumber of instance suffix (integer) -> replace
  # broker.rack = cluster id RACK1 , RACK 2  -> append
  # log.dirs = /var/data/kafka -> replace
  # zookeeper.connect = "ip:port"
  # optional
  # offsets.topic.num.partitions = 3
  # offsets.topic.replication.factor = 2
  # min.insync.replicas = 2
  # default.replication.factor

  # check logging.

  # tests
  #   root@armadom-kafka-16196:/opt/kafka/bin# ./kafka-topics.sh --create --zookeeper 10.128.0.28 --replication-factor 2 --partitions 2 --topic test
  # Created topic test.

  #   root@armadom-kafka-16196:/opt/kafka/bin# ./kafka-topics.sh --list --zookeeper 10.128.0.28
  # test

  # .zookeeper-shell ip:port ls /brokers/ids
  #   root@armadom-kafka-16196:/opt/kafka/bin# ./zookeeper-shell.sh 10.128.0.28:2181 ls /brokers/ids
  # Connecting to 10.128.0.28:2181

  # WATCHER::

  # WatchedEvent state:SyncConnected type:None path:null
  # [1, 2]

  # 103 echo "dasdasd" > ./kafka-console-producer.sh --broker-list $MY_IP:9092 --topic test
  # 104  ./kafka-console-consumer.sh --boostrap-server $MY_IP:9092 --topic test --from-beginning

  # kafkacat for testing
  # kafkacat -b $MY_IP:9092 -t test -e

fi

