#!/bin/bash -eu
#
# Copyright 2021 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "zookeeper.set.acl=true" >> /opt/kafka/config/zookeeper.properties
systemctl restart zookeeper

/usr/share/zookeeper/bin/zkCli.sh -timeout 3000 -server localhost:2181 <<EOF
setAcl /controller world:anyone:r
setAcl /brokers world:anyone:cdrwa
setAcl /admin world:anyone:cdrwa
setAcl /isr_change_notification world:anyone:r
setAcl /controller_epoch world:anyone:cdrwa
setAcl /consumers world:anyone:cdrwa
setAcl /config world:anyone:cdrwa
setAcl /latest_producer_id_block world:anyone:cdrwa
setAcl /log_dir_event_notification world:anyone:cdrwa
setAcl /feature world:anyone:cdrwa
setAcl /cluster world:anyone:cdrwaquit
quit
EOF
