#!/bin/bash -eu
#
# Copyright 2021 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/c2d-utils || exit 1

# Create database and user

readonly db_password="$(get_attribute_value "weblate-db-password")"
readonly db_username="weblate"
readonly db_name="weblate"

sudo -u postgres psql -c "CREATE USER ${db_username} WITH PASSWORD '${db_password}';"
sudo -u postgres psql -c "CREATE DATABASE ${db_name} OWNER ${db_username};"


# Create configuration file
local python_folder="$(ls -la /opt/weblate-env/lib | grep "python" | awk '{ print $9 }')"
local config_file="/opt/weblate-env/lib/${python_folder}/site-packages/weblate/settings.py"

# Apply configuration

declare -a substitutions=(
  "\$WEBLATE_SITE_TITLE"
  "\$WEBLATE_ADMIN_NAME"
  "\$WEBLATE_ADMIN_EMAIL"
  "\$WEBLATE_DB_NAME"
  "\$WEBLATE_DB_USER"
  "\$WEBLATE_DB_PASSWORD"
  "\$WEBLATE_REDIS_PASSWORD"
  "\$DJANGO_SECRET_KEY"
)
envsubst "${substitutions[*]}" > "${config_file}"

# Setup Weblate

weblate migrate
weblate createadmin
weblate collectstatic
weblate compress
/opt/weblate-env/lib/python3.5/site-packages/weblate/examples/celery start
weblate runserver
