load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "1868ff68d6079e31b2f09b828b58d62e57ca8e9636edff699247c9108518570b",
    urls = [
        "https://github.com/bazelbuild/rules_go/releases/download/0.11.1/rules_go-0.11.1.tar.gz",
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/0.11.1/rules_go-0.11.1.tar.gz",
    ],
)

http_archive(
    name = "bazel_gazelle",
    sha256 = "92a3c59734dad2ef85dc731dbcb2bc23c4568cded79d4b87ebccd787eb89e8d0",
    urls = [
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/0.11.0/bazel-gazelle-0.11.0.tar.gz",
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/0.11.0/bazel-gazelle-0.11.0.tar.gz",
    ],
)

load("@io_bazel_rules_go//go:def.bzl", "go_repository", "go_rules_dependencies", "go_register_toolchains")

go_repository(
    name = "com_github_gopkg_v2",
    importpath = "gopkg.in/yaml.v2",
    tag = "v2.3.0",
)

go_rules_dependencies()

load("@io_bazel_rules_go//go:private/sdk.bzl", "go_download_sdk")
go_download_sdk(
    name = "go_sdk",
    sdks = {
        "linux_amd64": [
            "go1.12.17.linux-amd64.tar.gz",
            "3993f416629cb8c0146f34585c5b96495b45f448c9735d49a0d8f07fb08170c0",
        ],
    },
    urls = {
        "go1.12.17.linux-amd64.tar.gz": [
            "https://storage.googleapis.com/golang/go1.12.17.linux-amd64.tar.gz",
        ],
    },
)

go_register_toolchains()

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")
gazelle_dependencies()

git_repository(
    name = "io_bazel_rules_docker",
    commit = "8bbe2a8abd382641e65ff7127a3700a8530f02ce",
    remote = "https://github.com/bazelbuild/rules_docker.git",
)

git_repository(
    name = "containerregistry",
    commit = "6b250f0bae8cce028df939010ee3118c8f2977ba",
    remote = "https://github.com/google/containerregistry",
)

load(
    "@io_bazel_rules_docker//docker:docker.bzl",
    "docker_repositories",
    "docker_pull",
)

docker_repositories()

load(
    "@io_bazel_rules_docker//container:container.bzl",
    "repositories",
)

repositories()
