load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# 1. rules_go v0.23.10: Compatible with old Bazel, uses multiple mirrors to bypass 404s
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "d9a9d51999acc7d60a5b58e20b391b907b3eaa9c670c1faa07c5e4a93bd8da36",
    urls = [
        "https://github.com/bazelbuild/rules_go/releases/download/v0.23.10/rules_go-v0.23.10.tar.gz",
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.23.10/rules_go-v0.23.10.tar.gz",
    ],
)

# 2. bazel_gazelle v0.21.1: Matches the v0.23.x rules_go ecosystem perfectly
http_archive(
    name = "bazel_gazelle",
    sha256 = "cdcd1511942d99f0e0a5da30901e18cc61bf961f65d6fe62071239f60f606bf9",
    urls = [
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.21.1/bazel-gazelle-v0.21.1.tar.gz",
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.21.1/bazel-gazelle-v0.21.1.tar.gz",
    ],
)

load("@io_bazel_rules_go//go:def.bzl", "go_repository", "go_rules_dependencies", "go_register_toolchains")

# Declare Go direct dependencies.
go_repository(
    name = "com_github_gopkg_v2",
    importpath = "gopkg.in/yaml.v2",
    tag = "v2.3.0",
)

go_rules_dependencies()

# Force an active Go SDK that is still hosted publicly (v0.23 supports 1.15 out of the box)
go_register_toolchains(version = "1.15.15")

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")
gazelle_dependencies()

git_repository(
    name = "io_bazel_rules_docker",
    commit = "8bbe2a8abd382641e65ff7127a3700a8530f02ce",
    remote = "https://github.com/bazelbuild/rules_docker.git",
)

git_repository(
    name = "containerregistry",
    commit = "6b250f0bae8cce028df939010ee3118c8f2977ba",
    remote = "https://github.com/google/containerregistry",
)

load(
    "@io_bazel_rules_docker//docker:docker.bzl",
    "docker_repositories",
    "docker_pull",
)

docker_repositories()

load(
    "@io_bazel_rules_docker//container:container.bzl",
    "repositories",
)

repositories()
