http_archive(
    name = "io_bazel_rules_go",
    sha256 = "66395349e59d87042a04875960d705c935d2da3cf63b2cf2be78a25c385b0d0c",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.40.0/rules_go-v0.40.0.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.40.0/rules_go-v0.40.0.tar.gz",
    ],
)

http_archive(
    name = "bazel_gazelle",
    sha256 = "7bb15799955735178fd331f3d85d761669657be46ee9994191425e4e5bfa601a",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.32.0/bazel-gazelle-0.32.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.32.0/bazel-gazelle-0.32.0.tar.gz",
    ],
)

load("@io_bazel_rules_go//go:def.bzl", "go_repository", "go_rules_dependencies", "go_register_toolchains")

# Declare Go direct dependencies.
go_repository(
    name = "com_github_gopkg_v2",
    importpath = "gopkg.in/yaml.v2",
    tag = "v2.3.0",
)

go_rules_dependencies()

go_register_toolchains(version = "1.22.0")

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")

gazelle_dependencies()

git_repository(
    name = "io_bazel_rules_docker",
    commit = "8bbe2a8abd382641e65ff7127a3700a8530f02ce",
    remote = "https://github.com/bazelbuild/rules_docker.git",
)

git_repository(
    name = "containerregistry",
    commit = "6b250f0bae8cce028df939010ee3118c8f2977ba",
    remote = "https://github.com/google/containerregistry",
)

load(
    "@io_bazel_rules_docker//docker:docker.bzl",
    "docker_repositories",
    "docker_pull",
)

docker_repositories()

load(
    "@io_bazel_rules_docker//container:container.bzl",
    "repositories",
)

repositories()
