#!/bin/bash -eu
#
# Copyright 2022 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/influxdb-utils || exit 1

export INFLUXDB_ADMIN_PASSWORD="$(get_attribute_value "influxdb-admin-password")"
export INFLUXDB_ORG="$(get_attribute_value "influxdb-organization")"
export INFLUXDB_BUCKET="$(get_attribute_value "influxdb-bucket")"
export INFLUX_TOKEN="$(get_attribute_value "influxdb-token")"

if [[ -z "${INFLUX_TOKEN}" ]]; then
   export INFLUX_TOKEN="$(openssl rand -hex 64)"
fi

# Run the CLI installer for InfluxDB
declare -a args=(
  --skip-verify \
  --force \
  --username admin \
  --password "${INFLUXDB_ADMIN_PASSWORD}" \
  --org "${INFLUXDB_ORG}" \
  --bucket "${INFLUXDB_BUCKET}" \
  --retention 0 \
  --token "${INFLUX_TOKEN}" \
)

if [[ "$(get_attribute_value "enable-https")" = True ]]; then
  chown root:influxdb /etc/ssl/private
  chown root:influxdb /etc/ssl/private/c2d-temporary-self-signed-cert.key
  chmod 650 /etc/ssl/private
  chmod 640 /etc/ssl/private/c2d-temporary-self-signed-cert.key
  args+=(--host=https://localhost:8086)
  echo "tls-cert = \"/etc/ssl/certs/c2d-temporary-self-signed-cert.pem\"" >> /etc/influxdb/config.toml
  echo "tls-key = \"/etc/ssl/private/c2d-temporary-self-signed-cert.key\"" >> /etc/influxdb/config.toml
else
  args+=(--host=http://localhost:8086)
fi

systemctl restart influxdb.service

influx setup "${args[@]}"

# Await for app be ready
wait_for_app

echo "Installation complete."
