#!/bin/bash -eu
#
# Copyright 2022 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#######################################
# Awaits for website at localhost be ready.
#######################################
function wait_for_app() {
  local max_retries=10
  local retry=1
  local http_code=0
  local host_ip=""

  # Prevent exit on error in case of request max-time reached.
  set +e

  echo "Checking for app readiness..."

  while [[ "${http_code}" -ne 200 && "${retry}" -le "${max_retries}" ]]; do
    echo "Retry: ${retry}"
    http_code="$(curl --max-time 5 -s -L -o /dev/null -w "%{http_code}" http://localhost:8086)"
    echo "Http Code: ${http_code}"
    (( retry=retry+1 ))

    if [[ "${http_code}" -ne 200 ]]; then
      systemctl stop influxd
      systemctl start influxd
      sleep 30
    fi
  done

  if [[ "${retry}" -gt "${max_retries}" ]]; then
    echo "Max retries exceeded."
    exit 1
  else
    echo "App is ready."
  fi

  set -e
}

source /opt/c2d/c2d-utils || exit 1

export INFLUXDB_ADMIN_PASSWORD="$(get_attribute_value "influxdb-admin-password")"

# Run the CLI installer for InfluxDB
declare -a args=(
  --skip-verify \
  --username admin \
  --password "${INFLUXDB_ADMIN_PASSWORD}" \
  --org Google_C2D_InfluxDB \
  --bucket influxdb_bucket \
  --retention 0 \
  --force \
  --name influxdb_config \
)

if [[ "$(get_attribute_value "enable-https")" = True ]]; then
  chown root:influxdb /etc/ssl/private
  chown root:influxdb /etc/ssl/private/c2d-temporary-self-signed-cert.key
  chmod 650 /etc/ssl/private
  chmod 640 /etc/ssl/private/c2d-temporary-self-signed-cert.key
  influx_url="https://localhost:8086"
  args+=(--host="${influx_url}")
  echo "tls-cert = \"/etc/ssl/certs/c2d-temporary-self-signed-cert.pem\"" >> /etc/influxdb/config.toml
  echo "tls-key = \"/etc/ssl/private/c2d-temporary-self-signed-cert.key\"" >> /etc/influxdb/config.toml
else

  influx_url="http://localhost:8086"
  args+=(--host="${influx_url}")
fi

systemctl restart influxdb.service

influx setup "${args[@]}"

# Await for app be ready
wait_for_app

echo "Installation complete."

