#!/bin/bash -eu
#
# Copyright 2021 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/c2d-utils || exit 1

readonly db_username="kong"
readonly db_password="$(get_attribute_value "kong-db-password")"
readonly db_name="kong"

# Set PostgreSQL Auth method to md5 which is supported by Kong
echo "Setting up pgsql password encryption:"
sed -i 's/scram-sha-256/md5/g' /etc/postgresql/*/main/pg_hba.conf
echo "password_encryption = md5" >> /etc/postgresql/*/main/postgresql.conf

# Ensure configuration is properly set before set up Kong
declare password_encryption=""
while [[ "${password_encryption}" != "md5" ]]; do
  echo "Reloading PostgreSQL..."
  systemctl restart postgresql

  password_encryption="$(sudo -u postgres psql -t --csv -c "show password_encryption;")"
  echo "Password Encryption: ${password_encryption}"
done

# Create user and database
sudo -u postgres psql -c "CREATE USER ${db_username} WITH PASSWORD '${db_password}';"
sudo -u postgres psql -c "CREATE DATABASE ${db_name} OWNER ${db_username};"
