#!/bin/bash -eu
#
# Copyright 2021 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/c2d-utils || exit 1

readonly db_username="kong"
readonly db_password="$(get_attribute_value "kong-db-password")"
readonly db_name="kong"
readonly external_ip="$(get_external_ip)"
readonly config_file="/etc/kong/kong.conf"

# Create kong.conf file
cp /etc/kong/kong.conf.default "${config_file}"
sed -i "s/#database =.*/database = postgres/" "${config_file}"
sed -i "s/#pg_user =.*/pg_user = ${db_username}/" "${config_file}"
sed -i "s/#pg_password =.*/pg_password = ${db_password}/" "${config_file}"
sed -i "s/#pg_database = .*/pg_database = kong/" "${config_file}"

# Run kong migration script and enable service
kong migrations bootstrap
systemctl enable kong
systemctl start kong

# Update motd banner with external ip
sed -i "s/EXTERNAL_IP/${external_ip}/g" /etc/motd
