#!/bin/bash -eu
#
# Copyright 2021 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /opt/c2d/joomla-utils || exit 1

declare -r joomla_db_password="$(get_attribute_value "joomla-db-password")"
declare -r mysql_password="$(get_attribute_value "mysql-root-password")"
declare -r joomla_db_name="joomla_db"
declare -r joomla_db_username="joomla"

echo "Creating database user..."
create_db_user "${mysql_password}" "${joomla_db_password}" "${joomla_db_name}" "${joomla_db_username}"

echo "Waiting application to be ready..."
wait_for_app

echo "Installation complete!"
